// demos/react/src/examples/slickgrid/Example41.tsx
import React, { useEffect, useRef, useState } from 'react';
import {
  type Column,
  Formatters,
  type GridOption,
  SlickGlobalEditorLock,
  SlickgridReact,
  type SlickgridReactInstance,
} from 'slickgrid-react';

import './example41.scss';

const Example41: React.FC = () => {
  const [columnDefinitions, setColumnDefinitions] = useState<Column[]>([]);
  const [dataset, setDataset] = useState<any[]>(getData());
  const [gridOptions, setGridOptions] = useState<GridOption | undefined>(undefined);
  const [hideSubTitle, setHideSubTitle] = useState(false);

  const dragHelperRef = useRef<HTMLElement>(null);
  const dragRowsRef = useRef<number[]>([]);
  const dragModeRef = useRef('');
  const reactGridRef = useRef<SlickgridReactInstance | null>(null);

  useEffect(() => {
    defineGrid();
  }, []);

  function reactGridReady(reactGrid: SlickgridReactInstance) {
    reactGridRef.current = reactGrid;
  }

  function defineGrid() {
    const columnDefinitions: Column[] = [
      {
        id: 'name',
        name: 'Name',
        field: 'name',
        width: 300,
        cssClass: 'cell-title',
      },
      {
        id: 'complete',
        name: 'Complete',
        width: 60,
        cssClass: 'cell-effort-driven',
        field: 'complete',
        formatter: Formatters.checkmarkMaterial,
      },
    ];

    const gridOptions: GridOption = {
      enableAutoResize: false,
      gridHeight: 225,
      gridWidth: 800,
      rowHeight: 33,
      enableCellNavigation: true,
      enableRowSelection: true,
      enableRowMoveManager: true,
      rowSelectionOptions: {
        // True (Single Selection), False (Multiple Selections)
        selectActiveRow: false,
      },
      rowMoveManager: {
        columnIndexPosition: 0,
        cancelEditOnDrag: true,
        disableRowSelection: true,
        hideRowMoveShadow: false,
        onBeforeMoveRows,
        onMoveRows,

        // you can also override the usability of the rows, for example make every 2nd row the only moveable rows,
        // usabilityOverride: (row, dataContext, grid) => dataContext.id % 2 === 1
      },
    };

    setColumnDefinitions(columnDefinitions);
    setGridOptions(gridOptions);
  }

  function getData() {
    return [
      { id: 0, name: 'Make a list', complete: true },
      { id: 1, name: 'Check it twice', complete: false },
      { id: 2, name: `Find out who's naughty`, complete: false },
      { id: 3, name: `Find out who's nice`, complete: false },
    ];
  }

  function onBeforeMoveRows(e: MouseEvent | TouchEvent, data: { rows: number[]; insertBefore: number }) {
    for (const dataRow of data.rows) {
      // no point in moving before or after itself
      if (dataRow === data.insertBefore || dataRow === data.insertBefore - 1) {
        e.stopPropagation();
        return false;
      }
    }
    return true;
  }

  function onMoveRows(_e: MouseEvent | TouchEvent, args: { rows: number[]; insertBefore: number }) {
    const extractedRows: any[] = [];
    const rows = args.rows;
    const insertBefore = args.insertBefore;
    const tmpDataset = dataset || [];
    const left = tmpDataset.slice(0, insertBefore);
    const right = tmpDataset.slice(insertBefore, tmpDataset.length);

    rows.sort((a, b) => a - b);

    for (const row of rows) {
      extractedRows.push(tmpDataset[row]);
    }

    rows.reverse();

    for (const row of rows) {
      if (row < insertBefore) {
        left.splice(row, 1);
      } else {
        right.splice(row - insertBefore, 1);
      }
    }

    const finalDataset = left.concat(extractedRows.concat(right));
    const selectedRows: number[] = [];
    for (let i = 0; i < rows.length; i++) {
      selectedRows.push(left.length + i);
    }

    reactGridRef.current?.dataView.setItems(finalDataset);
    reactGridRef.current?.slickGrid?.resetActiveCell();
    reactGridRef.current?.slickGrid?.invalidate();
  }

  function handleOnDragInit(e: CustomEvent) {
    // prevent the grid from cancelling drag'n'drop by default
    e.stopImmediatePropagation();
  }

  function handleOnDragStart(e: CustomEvent) {
    const cell = reactGridRef.current?.slickGrid?.getCellFromEvent(e);

    if (!cell || cell.cell === 0) {
      dragModeRef.current = '';
      return;
    }

    const row = cell.row;
    if (!dataset?.[row]) {
      return;
    }

    if (SlickGlobalEditorLock.isActive()) {
      return;
    }

    e.stopImmediatePropagation();
    dragModeRef.current = 'recycle';

    let selectedRows: number[] = reactGridRef.current?.slickGrid?.getSelectedRows() || [];

    if (!selectedRows.length || selectedRows.findIndex((row) => row === row) === -1) {
      selectedRows = [row];
      reactGridRef.current?.slickGrid?.setSelectedRows(selectedRows);
    }

    dragRowsRef.current = selectedRows;
    const dragCount = selectedRows.length;

    const dragMsgElm = document.createElement('span');
    dragMsgElm.className = 'drag-message';
    dragMsgElm.textContent = `Drag to Recycle Bin to delete ${dragCount} selected row(s)`;
    dragHelperRef.current = dragMsgElm;
    document.body.appendChild(dragMsgElm);
    document.querySelector<HTMLDivElement>('#dropzone')?.classList.add('drag-dropzone');

    return dragMsgElm;
  }

  function handleOnDrag(e: MouseEvent, args: any) {
    if (dragModeRef.current !== 'recycle') {
      return;
    }
    if (dragHelperRef.current instanceof HTMLElement) {
      dragHelperRef.current.style.top = `${e.pageY + 5}px`;
      dragHelperRef.current.style.left = `${e.pageX + 5}px`;
    }

    // add/remove pink background color when hovering recycle bin
    const dropzoneElm = document.querySelector<HTMLDivElement>('#dropzone')!;
    if (args.target instanceof HTMLElement && (args.target.id === 'dropzone' || args.target === dropzoneElm)) {
      dropzoneElm.classList.add('drag-hover'); // OR: dd.target.style.background = 'pink';
    } else {
      dropzoneElm.classList.remove('drag-hover');
    }
  }

  function handleOnDragEnd(e: CustomEvent, args: any) {
    if (dragModeRef.current !== 'recycle') {
      return;
    }
    dragHelperRef.current?.remove();
    document.querySelector<HTMLDivElement>('#dropzone')?.classList.remove('drag-dropzone', 'drag-hover');

    if (dragModeRef.current !== 'recycle' || args.target.id !== 'dropzone') {
      return;
    }

    // reaching here means that we'll remove the row that we started dragging from the dataset
    const tmpDataset: any[] = reactGridRef.current?.dataView.getItems() || [];
    const rowsToDelete = dragRowsRef.current.sort().reverse();
    for (const rowToDelete of rowsToDelete) {
      tmpDataset.splice(rowToDelete, 1);
    }
    reactGridRef.current?.slickGrid?.invalidate();
    reactGridRef.current?.slickGrid?.setSelectedRows([]);
    setDataset([...tmpDataset]);
  }

  function toggleSubTitle() {
    const newHideSubTitle = !hideSubTitle;
    setHideSubTitle(newHideSubTitle);
    const action = newHideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    reactGridRef.current?.resizerService.resizeGrid(0);
  }

  return !gridOptions ? (
    ''
  ) : (
    <div className="demo41">
      <div id="demo-container" className="container-fluid">
        <h2>
          Example 41: Drag & Drop
          <span className="float-end font18">
            see&nbsp;
            <a
              target="_blank"
              href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/react/src/examples/slickgrid/Example41.tsx"
            >
              <span className="mdi mdi-link-variant"></span> code
            </a>
          </span>
          <button
            className="ms-2 btn btn-outline-secondary btn-sm btn-icon"
            type="button"
            data-test="toggle-subtitle"
            onClick={() => toggleSubTitle()}
          >
            <span className="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
          </button>
        </h2>

        <div className="subtitle">
          <ul>
            <li>Click to select, Ctrl-click to toggle selection(s).</li>
            <li>Drag one or more rows by the handle icon (1st column) to reorder.</li>
            <li>Drag one or more rows by selection (2nd or 3rd column) and drag to the recycle bin to delete.</li>
          </ul>
        </div>

        <div className="row">
          <div className="col">
            <SlickgridReact
              gridId="grid41"
              columns={columnDefinitions}
              options={gridOptions}
              dataset={dataset}
              onReactGridCreated={($event) => reactGridReady($event.detail)}
              onDragInit={($event) => handleOnDragInit($event.detail.eventData)}
              onDragStart={($event) => handleOnDragStart($event.detail.eventData)}
              onDrag={($event) => handleOnDrag($event.detail.eventData, $event.detail.args)}
              onDragEnd={($event) => handleOnDragEnd($event.detail.eventData, $event.detail.args)}
            />
          </div>
        </div>
        <div className="col">
          <div id="dropzone" className="recycle-bin mt-4">
            Recycle Bin
          </div>
        </div>
      </div>
    </div>
  );
};

export default Example41;

// frameworks/angular-slickgrid/src/demos/examples/example41.component.ts
import { Component, type OnInit, ViewEncapsulation } from '@angular/core';
import {
  type AngularGridInstance,
  type Column,
  Editors,
  Formatters,
  type GridOption,
  isDefined,
  SlickGlobalEditorLock,
} from '../../library';

@Component({
  templateUrl: './example41.component.html',
  styleUrls: ['./example41.component.scss'],
  encapsulation: ViewEncapsulation.None,
  standalone: false,
})
export class Example41Component implements OnInit {
  angularGrid!: AngularGridInstance;
  gridOptions!: GridOption;
  columnDefinitions!: Column[];
  dataset!: any[];
  dragHelper?: HTMLElement;
  dragRows: number[] = [];
  dragMode = '';
  hideSubTitle = false;

  ngOnInit(): void {
    this.defineGrids();

    // mock a dataset
    this.dataset = this.mockData();
  }

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
  }

  isBrowserDarkModeEnabled() {
    return window.matchMedia?.('(prefers-color-scheme: dark)').matches ?? false;
  }

  /* Define grid Options and Columns */
  defineGrids() {
    this.columnDefinitions = [
      {
        id: 'name',
        name: 'Name',
        field: 'name',
        width: 300,
        cssClass: 'cell-title',
        editor: { model: Editors.Text },
        validator: this.requiredFieldValidator,
      },
      {
        id: 'complete',
        name: 'Complete',
        width: 60,
        cssClass: 'cell-effort-driven',
        field: 'complete',
        cannotTriggerInsert: true,
        formatter: Formatters.checkmarkMaterial,
        editor: { model: Editors.Checkbox },
      },
    ];

    this.gridOptions = {
      enableAutoResize: false,
      gridHeight: 225,
      gridWidth: 800,
      rowHeight: 33,
      enableCellNavigation: true,
      enableRowSelection: true,
      enableRowMoveManager: true,
      rowSelectionOptions: {
        // True (Single Selection), False (Multiple Selections)
        selectActiveRow: false,
      },
      rowMoveManager: {
        columnIndexPosition: 0,
        cancelEditOnDrag: true,
        disableRowSelection: true,
        hideRowMoveShadow: false,
        onBeforeMoveRows: this.onBeforeMoveRows.bind(this),
        onMoveRows: this.onMoveRows.bind(this),

        // you can also override the usability of the rows, for example make every 2nd row the only moveable rows,
        // usabilityOverride: (row, dataContext, grid) => dataContext.id % 2 === 1
      },
    };
  }

  mockData() {
    return [
      { id: 0, name: 'Make a list', complete: true },
      { id: 1, name: 'Check it twice', complete: false },
      { id: 2, name: `Find out who's naughty`, complete: false },
      { id: 3, name: `Find out who's nice`, complete: false },
    ];
  }

  onBeforeMoveRows(e: MouseEvent | TouchEvent, data: { rows: number[]; insertBefore: number }) {
    for (const dataRow of data.rows) {
      // no point in moving before or after itself
      if (dataRow === data.insertBefore || dataRow === data.insertBefore - 1) {
        e.stopPropagation();
        return false;
      }
    }
    return true;
  }

  onMoveRows(_e: MouseEvent | TouchEvent, args: { rows: number[]; insertBefore: number }) {
    const extractedRows: any[] = [];
    const rows = args.rows;
    const insertBefore = args.insertBefore;
    const left = this.dataset.slice(0, insertBefore);
    const right = this.dataset.slice(insertBefore, this.dataset.length);

    rows.sort((a, b) => a - b);

    for (const row of rows) {
      extractedRows.push(this.dataset[row]);
    }

    rows.reverse();

    for (const row of rows) {
      if (row < insertBefore) {
        left.splice(row, 1);
      } else {
        right.splice(row - insertBefore, 1);
      }
    }

    this.dataset = left.concat(extractedRows.concat(right));

    const selectedRows: number[] = [];
    for (let i = 0; i < rows.length; i++) {
      selectedRows.push(left.length + i);
    }

    this.angularGrid.slickGrid?.resetActiveCell();
    this.dataset = [...this.dataset];
  }

  handleOnDragInit(e: CustomEvent) {
    // prevent the grid from cancelling drag'n'drop by default
    e.stopImmediatePropagation();
  }

  handleOnDragStart(e: CustomEvent) {
    const cell = this.angularGrid.slickGrid?.getCellFromEvent(e);

    if (!cell || cell.cell === 0) {
      this.dragMode = '';
      return;
    }

    const row = cell.row;
    if (!this.dataset[row]) {
      return;
    }

    if (SlickGlobalEditorLock.isActive()) {
      return;
    }

    e.stopImmediatePropagation();
    this.dragMode = 'recycle';

    let selectedRows: number[] = this.angularGrid.slickGrid?.getSelectedRows() || [];

    if (!selectedRows.length || selectedRows.findIndex((row) => row === row) === -1) {
      selectedRows = [row];
      this.angularGrid.slickGrid?.setSelectedRows(selectedRows);
    }

    this.dragRows = selectedRows;
    const dragCount = selectedRows.length;

    const dragMsgElm = document.createElement('span');
    dragMsgElm.className = 'drag-message';
    dragMsgElm.textContent = `Drag to Recycle Bin to delete ${dragCount} selected row(s)`;
    this.dragHelper = dragMsgElm;
    document.body.appendChild(dragMsgElm);
    document.querySelector<HTMLDivElement>('#dropzone')?.classList.add('drag-dropzone');

    return dragMsgElm;
  }

  handleOnDrag(e: MouseEvent, args: any) {
    if (this.dragMode !== 'recycle') {
      return;
    }
    if (this.dragHelper instanceof HTMLElement) {
      this.dragHelper.style.top = `${e.pageY + 5}px`;
      this.dragHelper.style.left = `${e.pageX + 5}px`;
    }

    // add/remove pink background color when hovering recycle bin
    const dropzoneElm = document.querySelector<HTMLDivElement>('#dropzone')!;
    if (args.target instanceof HTMLElement && (args.target.id === 'dropzone' || args.target === dropzoneElm)) {
      dropzoneElm.classList.add('drag-hover'); // OR: dd.target.style.background = 'pink';
    } else {
      dropzoneElm.classList.remove('drag-hover');
    }
  }

  handleOnDragEnd(e: CustomEvent, args: any) {
    if (this.dragMode !== 'recycle') {
      return;
    }
    this.dragHelper?.remove();
    document.querySelector<HTMLDivElement>('#dropzone')?.classList.remove('drag-dropzone', 'drag-hover');

    if (this.dragMode !== 'recycle' || args.target.id !== 'dropzone') {
      return;
    }

    // reaching here means that we'll remove the row that we started dragging from the dataset
    const rowsToDelete = this.dragRows.sort().reverse();
    for (const rowToDelete of rowsToDelete) {
      this.dataset.splice(rowToDelete, 1);
    }
    this.angularGrid.slickGrid?.invalidate();
    this.angularGrid.slickGrid?.setSelectedRows([]);
    this.dataset = [...this.dataset];
  }

  requiredFieldValidator(value: any) {
    if (isDefined(value)) {
      return { valid: false, msg: 'This is a required field' };
    } else {
      return { valid: true, msg: null };
    }
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    this.angularGrid.resizerService.resizeGrid(0);
  }
}

<div class="container-fluid">
  <h2>
    Example 41: Drag & Drop
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example41.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <h6 class="subtitle italic">
    <ul>
      <li>Click to select, Ctrl-click to toggle selection(s).</li>
      <li>Drag one or more rows by the handle icon to reorder.</li>
      <li>Drag one or more rows by selection and drag to the recycle bin to delete.</li>
    </ul>
  </h6>

  <div class="row">
    <div class="col">
      <div class="grid41">
        <angular-slickgrid
          gridId="grid41"
          [columns]="columnDefinitions"
          [options]="gridOptions"
          [dataset]="dataset"
          (onAngularGridCreated)="angularGridReady($event.detail)"
          (onDragInit)="handleOnDragInit($event.detail.eventData)"
          (onDragStart)="handleOnDragStart($event.detail.eventData)"
          (onDrag)="handleOnDrag($event.detail.eventData, $event.detail.args)"
          (onDragEnd)="handleOnDragEnd($event.detail.eventData, $event.detail.args)"
        >
          <ng-template #slickgridHeader>
            <div class="grid-header">
              <label>Santa's TODO list:</label>
            </div>
          </ng-template>
        </angular-slickgrid>
      </div>
    </div>

    <div class="col">
      <div id="dropzone" class="recycle-bin mt-4">Recycle Bin</div>
    </div>
  </div>
</div>
