// demos/vue/src/components/Example48.vue
<script setup lang="ts">
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { Formatters, SlickEventHandler, SlickgridVue, type Column, type GridOption, type SlickgridVueInstance } from 'slickgrid-vue';
import { onBeforeMount, ref, type Ref } from 'vue';

const NB_ITEMS = 995;

const _eventHandler = new SlickEventHandler();
const gridOptions1 = ref<GridOption>();
const gridOptions2 = ref<GridOption>();
const columns1: Ref<Column[]> = ref([]);
const columns2: Ref<Column[]> = ref([]);
const dataset1 = ref<any[]>([]);
const dataset2 = ref<any[]>([]);
const showSubTitle = ref(true);
const enableMultiSelection = ref(false);
const vueGrid1 = ref<SlickgridVueInstance>();
const vueGrid2 = ref<SlickgridVueInstance>();

onBeforeMount(() => {
  defineGrids();
  // mock some data (different in each dataset)
  dataset1.value = mockData(NB_ITEMS);
  dataset2.value = mockData(NB_ITEMS);
});

function vueGrid1Ready(vueGrid: SlickgridVueInstance) {
  vueGrid1.value = vueGrid;
  const cellSelectionModel1 = vueGrid.slickGrid!.getSelectionModel()!;
  _eventHandler.subscribe(cellSelectionModel1.onSelectedRangesChanged, (_e, args) => {
    const targetRange = document.querySelector('#selectionRange1') as HTMLSpanElement;
    if (targetRange) {
      targetRange.textContent = '';
      for (const slickRange of args) {
        targetRange.textContent += JSON.stringify(slickRange);
      }
    }
  });
}

function vueGrid2Ready(vueGrid: SlickgridVueInstance) {
  vueGrid2.value = vueGrid;
  const cellSelectionModel2 = vueGrid.slickGrid!.getSelectionModel()!;
  _eventHandler.subscribe(cellSelectionModel2.onSelectedRangesChanged, (_e, args) => {
    const targetRange = document.querySelector('#selectionRange2') as HTMLSpanElement;
    if (targetRange) {
      targetRange.textContent = '';
      for (const slickRange of args) {
        targetRange.textContent += JSON.stringify(slickRange);
      }
    }
  });
}

/* Define grid Options and Columns */
function defineGrids() {
  const colDefs1: Column[] = [
    { id: 'id', name: '#', field: 'id', width: 32, maxWidth: 40, excludeFromHeaderMenu: true },
    { id: 'title', name: 'Title', field: 'title', width: 90, cssClass: 'cell-title' },
    { id: 'complete', name: '% Complete', field: 'percentComplete', sortable: true, width: 90 },
    { id: 'start', name: 'Start', field: 'start', type: 'date', sortable: true, formatter: Formatters.dateUs },
    { id: 'finish', name: 'Finish', field: 'finish', type: 'date', sortable: true, formatter: Formatters.dateUs },
    {
      id: 'priority',
      name: 'Priority',
      field: 'priority',
      width: 80,
      resizable: false,
      sortable: true,
      type: 'number',
      sortComparer: (x, y, direction) => {
        return (direction ?? 0) * (x === y ? 0 : x > y ? 1 : -1);
      },
      formatter: (_row, _cell, value) => {
        if (!value) {
          return '';
        }
        const count = +(value >= 3 ? 3 : value);
        return count === 3 ? 'High' : count === 2 ? 'Medium' : 'Low';
      },
    },
    {
      id: 'effortDriven',
      name: 'Effort Driven',
      field: 'effortDriven',
      cssClass: 'text-center',
      width: 95,
      maxWidth: 120,
      type: 'boolean',
      sortable: true,
      exportCustomFormatter: (_row, _cell, value) => (value ? 'Yes' : 'No'),
      formatter: Formatters.checkmarkMaterial,
    },
  ];

  // assign both column definitions
  columns1.value = colDefs1;
  columns2.value = [...colDefs1];

  gridOptions1.value = {
    autoResize: {
      container: '.demo-container',
    },
    gridHeight: 250,
    gridWidth: 800,
    enableCellNavigation: true,
    autoEdit: true,
    editable: true,
    headerRowHeight: 35,
    rowHeight: 35,
    enableExcelExport: true,
    excelExportOptions: {
      exportWithFormatter: true,
    },
    externalResources: [new ExcelExportService()],

    // enable new hybrid selection model (rows & cells)
    enableSelection: true,
    selectionOptions: {
      rowSelectColumnIds: ['id'],
      selectionType: 'mixed',
      enableMultiSelection: false,
      // showDragHandle: 'hover', // can also be true (default) or false
    },

    // when using the ExcelCopyBuffer, you can see what the selection range is
    enableExcelCopyBuffer: true,
    excelCopyBufferOptions: {
      copyActiveEditorCell: true,
      removeDoubleQuotesOnPaste: true,
      replaceNewlinesWith: ' ',
    },
  };

  // copy the same Grid Options and Column Definitions to 2nd grid
  gridOptions2.value = {
    ...gridOptions1.value,
    // you can also enable checkbox selection & row selection, make sure to use `rowSelectColumnIds: ['id', '_checkbox_selector']`
    enableCheckboxSelector: true,
    enableSelection: true,
    selectionOptions: {
      // True (Single Selection), False (Multiple Selections)
      selectActiveRow: false,

      // you could use "row" selection to override the hybrid mode
      selectionType: 'row',

      // allow using the mouse drag selection to select multiple rows
      dragToSelect: true,
      enableMultiSelection: false,
    },
  };
}

function toggleMultiSelection(event: Event) {
  const enabled = (event.target as HTMLInputElement).checked;
  enableMultiSelection.value = enabled;

  const selectionOptions1 = { ...gridOptions1.value?.selectionOptions, enableMultiSelection: enabled };
  const selectionOptions2 = { ...gridOptions2.value?.selectionOptions, enableMultiSelection: enabled };
  gridOptions1.value = { ...gridOptions1.value, selectionOptions: selectionOptions1 } as GridOption;
  gridOptions2.value = { ...gridOptions2.value, selectionOptions: selectionOptions2 } as GridOption;

  vueGrid1.value?.slickGrid?.setOptions({ selectionOptions: selectionOptions1 }, true);
  vueGrid2.value?.slickGrid?.setOptions({ selectionOptions: selectionOptions2 }, true);
  const selectionModel1 = vueGrid1.value?.slickGrid?.getSelectionModel();
  const selectionModel2 = vueGrid2.value?.slickGrid?.getSelectionModel();
  if (selectionModel1) {
    selectionModel1.setOptions({ enableMultiSelection: enabled });
  }
  if (selectionModel2) {
    selectionModel2.setOptions({ enableMultiSelection: enabled });
  }
}

function mockData(itemCount: number) {
  const data: any[] = [];
  for (let i = 0; i < itemCount; i++) {
    const randomYear = 2000 + Math.floor(Math.random() * 10);
    const randomMonth = Math.floor(Math.random() * 11);
    const randomDay = Math.floor(Math.random() * 29);
    const randomFinishYear = randomYear + Math.floor(Math.random() * 10);
    const randomFinish = new Date(randomFinishYear, randomMonth + 1, randomDay);

    data[i] = {
      id: i,
      title: 'Task ' + i,
      duration: Math.floor(Math.random() * 25) + ' days',
      percentComplete: Math.floor(Math.random() * 100),
      start: new Date(randomYear, randomMonth, randomDay, randomDay),
      finish: randomFinish,
      priority: i % 3 ? 2 : i % 5 ? 3 : 1,
      effortDriven: i % 4 === 0,
    };
  }
  return data;
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
}
</script>

<template>
  <h2>
    Example 48: Hybrid Selection Model
    <span class="float-end font18">
      see&nbsp;
      <a target="_blank" href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example01.vue">
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    <code>SlickHybridSelectionModel</code> This Selection Model is an hybrid approach that uses a combination of the row or cell selections
    depending on certain conditions.
    <ul>
      <li>
        1. clicking on the first column (<code>id</code>) will use <code>RowSelectionModel</code> because of our configuration of
        <code>rowSelectColumnIds: ['id']</code> as the columns that will trigger row selection.
      </li>
      <li>2. clicking on the any other columns will use <code>CellSelectionModel</code> by default</li>
    </ul>
  </div>

  <h3>
    Grid 1
    <small class="subtitle ms-3 text-italic">
      <label>Range Selection</label>
      <span id="selectionRange1"></span>
    </small>
  </h3>

  <div class="grid-container1">
    <SlickgridVue
      v-model:options="gridOptions1!"
      v-model:columns="columns1"
      v-model:dataset="dataset1"
      grid-id="grid48-1"
      @onVueGridCreated="vueGrid1Ready($event.detail)"
    >
    </SlickgridVue>
  </div>

  <label class="checkbox-inline control-label mb-3">
    <input type="checkbox" data-test="enable-multi-selection" :checked="enableMultiSelection" @change="toggleMultiSelection" />
    Enable multi-selection (Ctrl/Cmd-click or drag)
  </label>

  <h3>
    Grid 2
    <small class="subtitle ms-3 text-italic">
      <label>Range Selection</label>
      <span id="selectionRange2"></span>
    </small>
  </h3>

  <slickgrid-vue
    v-model:options="gridOptions2!"
    v-model:columns="columns2"
    v-model:dataset="dataset2"
    grid-id="grid48-2"
    @onVueGridCreated="vueGrid2Ready($event.detail)"
  >
  </slickgrid-vue>
</template>

// frameworks/angular-slickgrid/src/demos/examples/example48.component.ts
import { Component, type OnInit } from '@angular/core';
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import {
  AngularSlickgridComponent,
  Formatters,
  SlickEventHandler,
  type AngularGridInstance,
  type Column,
  type GridOption,
} from '../../library';

const NB_ITEMS = 995;

@Component({
  templateUrl: './example48.component.html',
  // styles: ['#grid48-1 { .slick-row .slick-cell:first-child { border-right: 1px solid #d4d4d4; } }'],
  imports: [AngularSlickgridComponent],
})
export class Example48Component implements OnInit {
  protected _eventHandler = new SlickEventHandler();
  angularGrid1!: AngularGridInstance;
  angularGrid2!: AngularGridInstance;
  columns1: Column[] = [];
  columns2: Column[] = [];
  gridOptions1!: GridOption;
  gridOptions2!: GridOption;
  dataset1!: any[];
  dataset2!: any[];
  hideSubTitle = false;
  enableMultiSelection = false;

  ngOnInit(): void {
    this.defineGrids();
    // mock some data (different in each dataset)
    this.dataset1 = this.mockData(NB_ITEMS);
    this.dataset2 = this.mockData(NB_ITEMS);
  }

  angularGridReady1(angularGrid1: AngularGridInstance) {
    this.angularGrid1 = angularGrid1;

    const cellSelectionModel1 = angularGrid1.slickGrid!.getSelectionModel()!;
    this._eventHandler.subscribe(cellSelectionModel1.onSelectedRangesChanged, (_e, args) => {
      const targetRange = document.querySelector('#selectionRange1') as HTMLSpanElement;
      if (targetRange) {
        targetRange.textContent = '';
        for (const slickRange of args) {
          targetRange.textContent += JSON.stringify(slickRange);
        }
      }
    });
  }

  angularGridReady2(angularGrid2: AngularGridInstance) {
    this.angularGrid2 = angularGrid2;

    const cellSelectionModel2 = angularGrid2.slickGrid!.getSelectionModel()!;
    this._eventHandler.subscribe(cellSelectionModel2.onSelectedRangesChanged, (_e, args) => {
      const targetRange = document.querySelector('#selectionRange2') as HTMLSpanElement;
      if (targetRange) {
        targetRange.textContent = '';
        for (const slickRange of args) {
          targetRange.textContent += JSON.stringify(slickRange);
        }
      }
    });
  }

  defineGrids() {
    this.columns1 = [
      { id: 'id', name: '#', field: 'id', width: 32, maxWidth: 40, excludeFromHeaderMenu: true },
      { id: 'title', name: 'Title', field: 'title', width: 90, cssClass: 'cell-title' },
      { id: 'complete', name: '% Complete', field: 'percentComplete', sortable: true, width: 90 },
      { id: 'start', name: 'Start', field: 'start', type: 'date', sortable: true, formatter: Formatters.dateUs },
      { id: 'finish', name: 'Finish', field: 'finish', type: 'date', sortable: true, formatter: Formatters.dateUs },
      {
        id: 'priority',
        name: 'Priority',
        field: 'priority',
        width: 80,
        resizable: false,
        sortable: true,
        type: 'number',
        sortComparer: (x, y, direction) => {
          return (direction ?? 0) * (x === y ? 0 : x > y ? 1 : -1);
        },
        formatter: (_row, _cell, value) => {
          if (!value) {
            return '';
          }
          const count = +(value >= 3 ? 3 : value);
          return count === 3 ? 'High' : count === 2 ? 'Medium' : 'Low';
        },
      },
      {
        id: 'effortDriven',
        name: 'Effort Driven',
        field: 'effortDriven',
        cssClass: 'text-center',
        width: 95,
        maxWidth: 120,
        type: 'boolean',
        sortable: true,
        exportCustomFormatter: (_row, _cell, value) => (value ? 'Yes' : 'No'),
        formatter: Formatters.checkmarkMaterial,
      },
    ];
    this.columns2 = [...this.columns1];

    this.gridOptions1 = {
      autoResize: {
        container: '.demo-container',
      },
      gridHeight: 250,
      gridWidth: 800,
      enableCellNavigation: true,
      autoEdit: true,
      editable: true,
      headerRowHeight: 35,
      rowHeight: 35,
      enableExcelExport: true,
      excelExportOptions: {
        exportWithFormatter: true,
      },
      externalResources: [new ExcelExportService()],

      // enable new hybrid selection model (rows & cells)
      enableSelection: true,
      selectionOptions: {
        rowSelectColumnIds: ['id'],
        selectionType: 'mixed',
        enableMultiSelection: false,
        // showDragHandle: 'hover', // can also be true (default) or false
      },

      // when using the ExcelCopyBuffer, you can see what the selection range is
      enableExcelCopyBuffer: true,
      excelCopyBufferOptions: {
        copyActiveEditorCell: true,
        removeDoubleQuotesOnPaste: true,
        replaceNewlinesWith: ' ',
      },
    };
    this.gridOptions2 = {
      ...this.gridOptions1,
      // you can also enable checkbox selection & row selection, make sure to use `rowSelectColumnIds: ['id', '_checkbox_selector']`
      enableCheckboxSelector: true,
      enableSelection: true,
      selectionOptions: {
        // True (Single Selection), False (Multiple Selections)
        selectActiveRow: false,

        // you could use "row" selection to override the hybrid mode
        selectionType: 'row',

        // allow using the mouse drag selection to select multiple rows
        dragToSelect: true,
        enableMultiSelection: false,
      },
    };
  }

  toggleMultiSelection(event: Event) {
    this.enableMultiSelection = (event.target as HTMLInputElement).checked;

    const selectionOptions1 = { ...this.gridOptions1.selectionOptions, enableMultiSelection: this.enableMultiSelection };
    const selectionOptions2 = { ...this.gridOptions2.selectionOptions, enableMultiSelection: this.enableMultiSelection };
    this.gridOptions1.selectionOptions = selectionOptions1;
    this.gridOptions2.selectionOptions = selectionOptions2;

    this.angularGrid1?.slickGrid?.setOptions({ selectionOptions: selectionOptions1 }, true);
    this.angularGrid2?.slickGrid?.setOptions({ selectionOptions: selectionOptions2 }, true);
    const selectionModel1 = this.angularGrid1?.slickGrid?.getSelectionModel();
    const selectionModel2 = this.angularGrid2?.slickGrid?.getSelectionModel();
    if (selectionModel1) {
      selectionModel1.setOptions({ enableMultiSelection: this.enableMultiSelection });
    }
    if (selectionModel2) {
      selectionModel2.setOptions({ enableMultiSelection: this.enableMultiSelection });
    }
  }

  mockData(itemCount: number) {
    const data: any[] = [];
    for (let i = 0; i < itemCount; i++) {
      const randomYear = 2000 + Math.floor(Math.random() * 10);
      const randomMonth = Math.floor(Math.random() * 11);
      const randomDay = Math.floor(Math.random() * 29);
      const randomFinishYear = randomYear + Math.floor(Math.random() * 10);
      const randomFinish = new Date(randomFinishYear, randomMonth + 1, randomDay);

      data[i] = {
        id: i,
        title: 'Task ' + i,
        duration: Math.floor(Math.random() * 25) + ' days',
        percentComplete: Math.floor(Math.random() * 100),
        start: new Date(randomYear, randomMonth, randomDay, randomDay),
        finish: randomFinish,
        priority: i % 3 ? 2 : i % 5 ? 3 : 1,
        effortDriven: i % 4 === 0,
      };
    }
    return data;
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
  }
}

<div class="container-fluid">
  <h2>
    Example 48: Hybrid Selection Model
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example48.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    <code>SlickHybridSelectionModel</code> This Selection Model is an hybrid approach that uses a combination of the row or cell selections
    depending on certain conditions.
    <ul>
      <li>
        1. clicking on the first column (<code>id</code>) will use <code>RowSelectionModel</code> because of our configuration of
        <code>rowSelectColumnIds: ['id']</code> as the columns that will trigger row selection.
      </li>
      <li>2. clicking on the any other columns will use <code>CellSelectionModel</code> by default</li>
    </ul>
  </div>

  <h3>
    Grid 1
    <small class="subtitle ms-3 text-italic">
      <label>Range Selection</label>
      <span id="selectionRange1"></span>
    </small>
  </h3>
  <div class="grid-container1">
    <angular-slickgrid
      gridId="grid48-1"
      [columns]="columns1"
      [options]="gridOptions1"
      [dataset]="dataset1"
      (onAngularGridCreated)="angularGridReady1($event.detail)"
    >
    </angular-slickgrid>
  </div>

  <label class="checkbox-inline control-label mb-3">
    <input type="checkbox" data-test="enable-multi-selection" [checked]="enableMultiSelection" (change)="toggleMultiSelection($event)" />
    Enable multi-selection (Ctrl/Cmd-click or drag)
  </label>

  <h3>
    Grid 2
    <small class="subtitle ms-3 text-italic">
      <label>Range Selection</label>
      <span id="selectionRange2"></span>
    </small>
  </h3>
  <div class="grid-container">
    <angular-slickgrid
      gridId="grid48-2"
      [columns]="columns2"
      [options]="gridOptions2"
      [dataset]="dataset2"
      (onAngularGridCreated)="angularGridReady2($event.detail)"
    >
    </angular-slickgrid>
  </div>
</div>
