// frameworks/angular-slickgrid/src/demos/examples/example34.component.ts
import { Component, type OnDestroy, type OnInit, ViewEncapsulation } from '@angular/core';
import { faker } from '@faker-js/faker';
import sparkline from '@fnando/sparkline';
import {
  Aggregators,
  type AngularGridInstance,
  type Column,
  createDomElement,
  deepCopy,
  Filters,
  type Formatter,
  Formatters,
  type GridOption,
  GroupTotalFormatters,
} from '../../library';

const NB_ROWS = 200;

const currencyFormatter: Formatter = (cell: number, row: number, value: string) =>
  `<img src="https://flags.fmcdn.net/data/flags/mini/${value.substr(0, 2).toLowerCase()}.png" width="20"/> ${value}`;

const priceFormatter: Formatter = (_cell, _row, value, _col, dataContext) => {
  const direction = dataContext.priceChange >= 0 ? 'up' : 'down';
  const fragment = new DocumentFragment();
  const divElm = document.createElement('div');
  divElm.className = `d-inline-flex align-items-center text-${direction === 'up' ? 'success' : 'danger'}`;
  const spanElm = document.createElement('span');
  spanElm.className = `mdi mdi-arrow-${direction}`;
  divElm.appendChild(spanElm);
  fragment.appendChild(divElm);
  if (value instanceof HTMLElement) {
    divElm.appendChild(value);
  } else {
    divElm.appendChild(document.createTextNode(value));
  }
  return fragment;
};

const transactionTypeFormatter: Formatter = (_row, _cell, value: string) =>
  `<div class="d-inline-flex align-items-center"><span class="me-1 mdi mdi-16px mdi-${value === 'Buy' ? 'plus' : 'minus'}-circle ${value === 'Buy' ? 'text-info' : 'text-warning'}"></span> ${value}</div>`;

const historicSparklineFormatter: Formatter = (_row, _cell, _value: string, _col, dataContext) => {
  if (dataContext.historic.length < 2) {
    return '';
  }
  const svgElem = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svgElem.setAttributeNS(null, 'width', '135');
  svgElem.setAttributeNS(null, 'height', '30');
  svgElem.setAttributeNS(null, 'stroke-width', '2');
  svgElem.classList.add('sparkline');
  sparkline(svgElem, dataContext.historic, {
    cursorwidth: 2,
    onmousemove: (event, datapoint) => {
      const svg = (event.target as HTMLElement).closest('svg');
      const tooltip = svg?.nextElementSibling as HTMLElement;
      if (tooltip) {
        tooltip.hidden = false;
        tooltip.textContent = `$${((datapoint.value * 100) / 100).toFixed(2)}`;
        tooltip.style.top = `${event.offsetY}px`;
        tooltip.style.left = `${event.offsetX + 20}px`;
      }
    },
    onmouseout: (event) => {
      const svg = (event.target as HTMLElement).closest('svg');
      const tooltip = svg?.nextElementSibling as HTMLElement;
      if (tooltip) {
        tooltip.hidden = true;
      }
    },
  });
  const div = document.createElement('div');
  div.appendChild(svgElem);
  div.appendChild(createDomElement('div', { className: 'trading-tooltip', hidden: true }));
  return div;
};

@Component({
  templateUrl: './example34.component.html',
  styleUrls: ['./example34.component.scss'],
  encapsulation: ViewEncapsulation.None,
  standalone: false,
})
export class Example34Component implements OnDestroy, OnInit {
  private _darkMode = false;
  angularGrid!: AngularGridInstance;
  gridOptions!: GridOption;
  columnDefinitions: Column[] = [];
  dataset: any[] = [];
  hideSubTitle = false;
  isFullScreen = false;
  highlightDuration = 150;
  itemCount = 200;
  minChangePerCycle = 0;
  maxChangePerCycle = 10;
  refreshRate = 75;
  timer: any;

  ngOnInit(): void {
    this.defineGrid();

    // mock a dataset
    this.dataset = this.loadData(NB_ROWS);

    setTimeout(() => {
      this.startSimulation();
    }, this.refreshRate);
  }

  ngOnDestroy(): void {
    this.stopSimulation();
    document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
  }

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
  }

  /* Define grid Options and Columns */
  defineGrid() {
    // the columns field property is type-safe, try to add a different string not representing one of DataItems properties
    this.columnDefinitions = [
      {
        id: 'currency',
        name: 'Currency',
        field: 'currency',
        filterable: true,
        sortable: true,
        minWidth: 65,
        width: 65,
        formatter: currencyFormatter,
        filter: {
          model: Filters.singleSelect,
          collection: [
            { label: '', value: '' },
            { label: 'CAD', value: 'CAD' },
            { label: 'USD', value: 'USD' },
          ],
        },
        grouping: {
          getter: 'currency',
          formatter: (g) =>
            `Currency: <span style="var(--slick-primary-color); font-weight: bold;">${g.value}</span>  <span style="color: #659bff;">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('amount')],
          aggregateCollapsed: true,
          collapsed: false,
        },
      },
      { id: 'symbol', name: 'Symbol', field: 'symbol', filterable: true, sortable: true, minWidth: 65, width: 65 },
      {
        id: 'market',
        name: 'Market',
        field: 'market',
        filterable: true,
        sortable: true,
        minWidth: 75,
        width: 75,
        grouping: {
          getter: 'market',
          formatter: (g) =>
            `Market: <span style="var(--slick-primary-color); font-weight: bold;">${g.value}</span>  <span style="color: #659bff;">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('amount')],
          aggregateCollapsed: true,
          collapsed: false,
        },
      },
      { id: 'company', name: 'Company', field: 'company', filterable: true, sortable: true, minWidth: 80, width: 130 },
      {
        id: 'trsnType',
        name: 'Type',
        field: 'trsnType',
        filterable: true,
        sortable: true,
        minWidth: 60,
        width: 60,
        formatter: transactionTypeFormatter,
        filter: {
          model: Filters.singleSelect,
          collection: [
            { label: '', value: '' },
            { label: 'Buy', value: 'Buy' },
            { label: 'Sell', value: 'Sell' },
          ],
        },
        grouping: {
          getter: 'trsnType',
          formatter: (g) =>
            `Type: <span style="var(--slick-primary-color); font-weight: bold;">${g.value}</span>  <span style="color: #659bff;">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('amount')],
          aggregateCollapsed: true,
          collapsed: false,
        },
      },
      {
        id: 'priceChange',
        name: 'Change',
        field: 'priceChange',
        filterable: true,
        sortable: true,
        minWidth: 80,
        width: 80,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.multiple,
        params: {
          formatters: [Formatters.dollar, priceFormatter],
          maxDecimal: 2,
        },
      },
      {
        id: 'price',
        name: 'Price',
        field: 'price',
        filterable: true,
        sortable: true,
        minWidth: 70,
        width: 70,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.dollar,
        params: { maxDecimal: 2 },
      },
      {
        id: 'quantity',
        name: 'Quantity',
        field: 'quantity',
        filterable: true,
        sortable: true,
        minWidth: 70,
        width: 70,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
      },
      {
        id: 'amount',
        name: 'Amount',
        field: 'amount',
        filterable: true,
        sortable: true,
        minWidth: 70,
        width: 60,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.dollar,
        params: { maxDecimal: 2 },
        groupTotalsFormatter: GroupTotalFormatters.sumTotalsDollarBold,
      },
      {
        id: 'historic',
        name: 'Price History',
        field: 'historic',
        minWidth: 100,
        width: 150,
        maxWidth: 150,
        formatter: historicSparklineFormatter,
      },
      {
        id: 'execution',
        name: 'Execution Timestamp',
        field: 'execution',
        filterable: true,
        sortable: true,
        minWidth: 125,
        formatter: Formatters.dateTimeIsoAmPm,
        exportWithFormatter: true,
        type: 'dateTimeIsoAM_PM',
        filter: { model: Filters.compoundDate },
      },
    ];

    this.gridOptions = {
      autoResize: {
        container: '.trading-platform',
        autoHeight: false,
        rightPadding: 0,
        bottomPadding: 10,
      },
      formatterOptions: {
        displayNegativeNumberWithParentheses: true,
        thousandSeparator: ',',
      },
      draggableGrouping: {
        dropPlaceHolderText: 'Drop a column header here to group by any of these available columns: Currency, Market or Type',
        deleteIconCssClass: 'mdi mdi-close',
      },
      enableDraggableGrouping: true,
      createPreHeaderPanel: true,
      darkMode: this._darkMode,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 40,
      enableCellNavigation: true,
      enableFiltering: true,
      cellHighlightCssClass: 'changed',
    };
  }

  loadData(itemCount: number): any[] {
    // mock a dataset
    const tmpDataset = [];
    for (let i = 0; i < itemCount; i++) {
      const randomPercent = Math.round(Math.random() * 100);
      const randomLowQty = this.randomNumber(1, 50);
      const randomHighQty = this.randomNumber(125, 255);
      const priceChange = this.randomNumber(-25, 35, false);
      const price = this.randomNumber(priceChange, 300);
      const quantity = price < 5 ? randomHighQty : randomLowQty;
      const amount = price * quantity;
      const now = new Date();
      now.setHours(9, 30, 0);
      const currency = Math.floor(Math.random() * 10) % 2 ? 'CAD' : 'USD';
      const company = faker.company.name();

      tmpDataset[i] = {
        id: i,
        currency,
        trsnType: Math.round(Math.random() * 100) % 2 ? 'Buy' : 'Sell',
        company,
        symbol: currency === 'CAD' ? company.substr(0, 3).toUpperCase() + '.TO' : company.substr(0, 4).toUpperCase(),
        market: currency === 'CAD' ? 'TSX' : price > 200 ? 'Nasdaq' : 'S&P 500',
        duration: i % 33 === 0 ? null : Math.random() * 100 + '',
        percentCompleteNumber: randomPercent,
        priceChange,
        price,
        quantity,
        amount,
        execution: now,
        historic: [price],
      };
    }

    return tmpDataset;
  }

  startSimulation() {
    const changes: any = {};
    const numberOfUpdates = this.randomNumber(this.minChangePerCycle, this.maxChangePerCycle);

    for (let i = 0; i < numberOfUpdates; i++) {
      const randomLowQty = this.randomNumber(1, 50);
      const randomHighQty = this.randomNumber(125, 255);
      const rowNumber = Math.round(Math.random() * (this.dataset.length - 1));
      const priceChange = this.randomNumber(-25, 25, false);
      const prevItem = deepCopy(this.dataset[rowNumber]);
      const itemTmp = { ...this.dataset[rowNumber] };
      itemTmp.priceChange = priceChange;
      itemTmp.price = itemTmp.price + priceChange < 0 ? 0 : itemTmp.price + priceChange;
      itemTmp.quantity = itemTmp.price < 5 ? randomHighQty : randomLowQty;
      itemTmp.amount = itemTmp.price * itemTmp.quantity;
      itemTmp.trsnType = Math.round(Math.random() * 100) % 2 ? 'Buy' : 'Sell';
      itemTmp.execution = new Date();
      itemTmp.historic.push(itemTmp.price);
      itemTmp.historic = itemTmp.historic.slice(-20); // keep a max of X historic values

      if (!changes[rowNumber]) {
        changes[rowNumber] = {};
      }

      // highlight whichever cell is being changed
      changes[rowNumber]['id'] = 'changed';
      this.renderCellHighlighting(itemTmp, this.findColumnById('priceChange'), priceChange);
      if ((prevItem.priceChange < 0 && itemTmp.priceChange > 0) || (prevItem.priceChange > 0 && itemTmp.priceChange < 0)) {
        this.renderCellHighlighting(itemTmp, this.findColumnById('price'), priceChange);
      }
      // if (prevItem.trsnType !== itemTmp.trsnType) {
      //   this.renderCellHighlighting(itemTmp, this.findColumnById('trsnType'), priceChange);
      // }

      // update the data
      this.angularGrid.dataView.updateItem(itemTmp.id, itemTmp);
      // NOTE: we should also invalidate/render the row after updating cell data to see the new data rendered in the UI
      // but the cell highlight actually does that for us so we can skip it
    }

    this.timer = setTimeout(this.startSimulation.bind(this), this.refreshRate || 0);
  }

  stopSimulation() {
    clearTimeout(this.timer);
  }

  findColumnById(columnName: string): Column {
    return this.columnDefinitions.find((col) => col.field === columnName) as Column;
  }

  renderCellHighlighting(item: any, column: Column, priceChange: number) {
    if (item && column) {
      const row = this.angularGrid.dataView.getRowByItem(item) as number;
      if (row >= 0) {
        const hash = { [row]: { [column.id]: priceChange >= 0 ? 'changed-gain' : 'changed-loss' } };
        this.angularGrid.slickGrid.setCellCssStyles(`highlight_${[column.id]}${row}`, hash);

        // remove highlight after x amount of time
        setTimeout(() => this.removeCellStyling(item, column, row), this.highlightDuration);
      }
    }
  }

  /** remove change highlight css class from that cell */
  removeCellStyling(_item: any, column: Column, row: number) {
    this.angularGrid?.slickGrid?.removeCellCssStyles(`highlight_${[column.id]}${row}`);
  }

  toggleFullScreen() {
    const container = document.querySelector('.trading-platform');
    if (container?.classList.contains('full-screen')) {
      container.classList.remove('full-screen');
      this.isFullScreen = false;
    } else if (container) {
      container.classList.add('full-screen');
      this.isFullScreen = true;
    }
    this.angularGrid.resizerService.resizeGrid();
  }

  toggleDarkMode() {
    this._darkMode = !this._darkMode;
    this.toggleBodyBackground();
    this.angularGrid.slickGrid?.setOptions({ darkMode: this._darkMode });
  }

  toggleBodyBackground() {
    if (this._darkMode) {
      document.querySelector<HTMLDivElement>('.panel-wm-content')!.classList.add('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'dark';
    } else {
      document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
    }
  }

  private randomNumber(min: number, max: number, floor = true) {
    const number = Math.random() * (max - min + 1) + min;
    return floor ? Math.floor(number) : number;
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    this.angularGrid.resizerService.resizeGrid(0);
  }
}

<div class="container-fluid">
  <h2>
    Example 34: Real-Time Trading Platform
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="toggleDarkMode()" data-test="toggle-dark-mode">
      <span class="mdi mdi-theme-light-dark"></span>
      <span>Toggle Dark Mode</span>
    </button>
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example34.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
  </h2>

  <div class="subtitle">
    Simulate a stock trading platform with lot of price changes, it is strongly suggested to disable the
    <code>autoResize.autoHeight</code> grid option for this type of grid.
    <ul>
      <li>
        you can start/stop the simulation, you can see SlickGrid huge perf by setting: (1) lower Changes Rate, (2) increase both Changes per
        Cycle, and (3) lower Highlight Duration
      </li>
      <li>optionally change random numbers, between 0 and 10 symbols, per cycle (higher numbers means more changes)</li>
      <li>optionally change the simulation changes refresh rate in ms (lower number means more changes).</li>
      <li>you can Group by 1 of these columns: Currency, Market or Type</li>
    </ul>
  </div>

  <div class="trading-platform">
    <div class="row mb-4 simulation-form">
      <div class="col-sm-12 d-flex align-items-center">
        <div class="range">
          <label for="refreshRateRange" class="form-label me-1">Changes Rate(ms)</label>
          <input type="range" class="form-range" id="refreshRateRange" min="0" max="250" [(ngModel)]="refreshRate" />
          <span class="refresh-rate">
            <input type="number" [(ngModel)]="refreshRate" />
          </span>
        </div>
        <span class="ms-3 me-1">
          <button class="btn btn-outline-secondary btn-sm btn-icon" data-test="start-btn" (click)="startSimulation()">
            <li class="mdi mdi-play-circle-outline"></li>
            Start Simulation
          </button>
        </span>
        <span class="me-3">
          <button class="btn btn-outline-secondary btn-sm btn-icon" data-test="stop-btn" (click)="stopSimulation()">
            <li class="mdi mdi-stop-circle-outline"></li>
            Stop Simulation
          </button>
        </span>
        <span class="mx-1">
          <label for="change-per-cycle-input">Changes p/Cycle</label>
          <input type="number" id="change-per-cycle-input" [(ngModel)]="minChangePerCycle" [max]="maxChangePerCycle" />
          to
          <input type="number" [(ngModel)]="maxChangePerCycle" [min]="minChangePerCycle" />
        </span>
        <span class="ms-2">
          <label for="highlight-input">Highlight Duration(ms)</label>
          <input type="number" id="highlight-input" data-test="highlight-input" [(ngModel)]="highlightDuration" />
        </span>
        <div class="ms-auto">
          <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="toggleFullScreen()">
            <li [class]="isFullScreen ? 'mdi mdi-arrow-collapse' : 'mdi mdi-arrow-expand'"></li>
            Toggle Full-Screen
          </button>
        </div>
      </div>
    </div>

    <angular-slickgrid
      gridId="grid34"
      [columns]="columnDefinitions"
      [options]="gridOptions"
      [dataset]="dataset"
      (onAngularGridCreated)="angularGridReady($event.detail)"
    >
    </angular-slickgrid>
  </div>
</div>

// demos/react/src/examples/slickgrid/Example34.tsx
import { faker } from '@faker-js/faker';
import sparkline from '@fnando/sparkline';
import React, { useEffect, useRef, useState } from 'react';
import {
  Aggregators,
  createDomElement,
  deepCopy,
  Filters,
  Formatters,
  GroupTotalFormatters,
  SlickgridReact,
  type Column,
  type Formatter,
  type GridOption,
  type SlickgridReactInstance,
} from 'slickgrid-react';
import './example34.scss';

const NB_ROWS = 200;

const currencyFormatter: Formatter = (cell: number, row: number, value: string) =>
  `<img src="https://flags.fmcdn.net/data/flags/mini/${value.substr(0, 2).toLowerCase()}.png" width="20"/> ${value}`;

const priceFormatter: Formatter = (_cell, _row, value, _col, dataContext) => {
  const direction = dataContext.priceChange >= 0 ? 'up' : 'down';
  const fragment = new DocumentFragment();
  const divElm = document.createElement('div');
  divElm.className = `d-inline-flex align-items-center text-${direction === 'up' ? 'success' : 'danger'}`;
  const spanElm = document.createElement('span');
  spanElm.className = `mdi mdi-arrow-${direction}`;
  divElm.appendChild(spanElm);
  fragment.appendChild(divElm);
  if (value instanceof HTMLElement) {
    divElm.appendChild(value);
  } else {
    divElm.appendChild(document.createTextNode(value));
  }
  return fragment;
};

const transactionTypeFormatter: Formatter = (_row, _cell, value: string) =>
  `<div class="d-inline-flex align-items-center"><span class="me-1 mdi font-16px mdi-${value === 'Buy' ? 'plus' : 'minus'}-circle ${value === 'Buy' ? 'text-info' : 'text-warning'}"></span> ${value}</div>`;

const historicSparklineFormatter: Formatter = (_row, _cell, _value: string, _col, dataContext) => {
  if (dataContext.historic.length < 2) {
    return '';
  }
  const svgElem = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svgElem.setAttributeNS(null, 'width', '135');
  svgElem.setAttributeNS(null, 'height', '30');
  svgElem.setAttributeNS(null, 'stroke-width', '2');
  svgElem.classList.add('sparkline');
  sparkline(svgElem, dataContext.historic, {
    cursorwidth: 2,
    onmousemove: (event, datapoint) => {
      const svg = (event.target as HTMLElement).closest('svg');
      const tooltip = svg?.nextElementSibling as HTMLElement;
      if (tooltip) {
        tooltip.hidden = false;
        tooltip.textContent = `$${((datapoint.value * 100) / 100).toFixed(2)}`;
        tooltip.style.top = `${event.offsetY}px`;
        tooltip.style.left = `${event.offsetX + 20}px`;
      }
    },
    onmouseout: (event) => {
      const svg = (event.target as HTMLElement).closest('svg');
      const tooltip = svg?.nextElementSibling as HTMLElement;
      if (tooltip) {
        tooltip.hidden = true;
      }
    },
  });
  const div = document.createElement('div');
  div.appendChild(svgElem);
  div.appendChild(createDomElement('div', { className: 'trading-tooltip', hidden: true }));
  return div;
};

const Example34: React.FC = () => {
  const [dataset] = useState<any[]>(loadData(NB_ROWS));
  const [darkMode, setDarkMode] = useState<boolean>(false);
  const [gridOptions, setGridOptions] = useState<GridOption | undefined>(undefined);
  const [highlightDuration, setHighlightDuration] = useState(150);
  const [isFullScreen, setIsFullScreen] = useState(false);
  const [minChangePerCycle, setMinChangePerCycle] = useState(0);
  const [maxChangePerCycle, setMaxChangePerCycle] = useState(10);
  const [refreshRate, setRefreshRate] = useState(75);
  const [hideSubTitle, setHideSubTitle] = useState(false);

  const columnDefinitionsRef = useRef<Column[]>([]);
  const minChangePerCycleRef = useRef(minChangePerCycle);
  const maxChangePerCycleRef = useRef(maxChangePerCycle);
  const highlightDurationRef = useRef(highlightDuration);
  const refreshRateRef = useRef(refreshRate);
  const timerRef = useRef<any>(null);
  const reactGridRef = useRef<SlickgridReactInstance | null>(null);

  useEffect(() => {
    defineGrid();
    setTimeout(() => {
      startSimulation();
    }, refreshRateRef.current);

    // make sure it's back to light mode before unmounting
    return () => {
      stopSimulation();
      document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
    };
  }, []);

  function reactGridReady(reactGrid: SlickgridReactInstance) {
    reactGridRef.current = reactGrid;
  }

  function defineGrid() {
    const columnDefinitions: Column[] = [
      {
        id: 'currency',
        name: 'Currency',
        field: 'currency',
        filterable: true,
        sortable: true,
        minWidth: 65,
        width: 65,
        formatter: currencyFormatter,
        filter: {
          model: Filters.singleSelect,
          collection: [
            { label: '', value: '' },
            { label: 'CAD', value: 'CAD' },
            { label: 'USD', value: 'USD' },
          ],
        },
        grouping: {
          getter: 'currency',
          formatter: (g) =>
            `Currency: <span style="var(--slick-primary-color); font-weight: bold;">${g.value}</span>  <span style="color: #659bff;">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('amount')],
          aggregateCollapsed: true,
          collapsed: false,
        },
      },
      { id: 'symbol', name: 'Symbol', field: 'symbol', filterable: true, sortable: true, minWidth: 65, width: 65 },
      {
        id: 'market',
        name: 'Market',
        field: 'market',
        filterable: true,
        sortable: true,
        minWidth: 75,
        width: 75,
        grouping: {
          getter: 'market',
          formatter: (g) =>
            `Market: <span style="var(--slick-primary-color); font-weight: bold;">${g.value}</span>  <span style="color: #659bff;">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('amount')],
          aggregateCollapsed: true,
          collapsed: false,
        },
      },
      { id: 'company', name: 'Company', field: 'company', filterable: true, sortable: true, minWidth: 80, width: 130 },
      {
        id: 'trsnType',
        name: 'Type',
        field: 'trsnType',
        filterable: true,
        sortable: true,
        minWidth: 60,
        width: 60,
        formatter: transactionTypeFormatter,
        filter: {
          model: Filters.singleSelect,
          collection: [
            { label: '', value: '' },
            { label: 'Buy', value: 'Buy' },
            { label: 'Sell', value: 'Sell' },
          ],
        },
        grouping: {
          getter: 'trsnType',
          formatter: (g) =>
            `Type: <span style="var(--slick-primary-color); font-weight: bold;">${g.value}</span>  <span style="color: #659bff;">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('amount')],
          aggregateCollapsed: true,
          collapsed: false,
        },
      },
      {
        id: 'priceChange',
        name: 'Change',
        field: 'priceChange',
        filterable: true,
        sortable: true,
        minWidth: 80,
        width: 80,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.multiple,
        params: {
          formatters: [Formatters.dollar, priceFormatter],
          maxDecimal: 2,
        },
      },
      {
        id: 'price',
        name: 'Price',
        field: 'price',
        filterable: true,
        sortable: true,
        minWidth: 70,
        width: 70,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.dollar,
        params: { maxDecimal: 2 },
      },
      {
        id: 'quantity',
        name: 'Quantity',
        field: 'quantity',
        filterable: true,
        sortable: true,
        minWidth: 70,
        width: 70,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
      },
      {
        id: 'amount',
        name: 'Amount',
        field: 'amount',
        filterable: true,
        sortable: true,
        minWidth: 70,
        width: 60,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.dollar,
        params: { maxDecimal: 2 },
        groupTotalsFormatter: GroupTotalFormatters.sumTotalsDollarBold,
      },
      {
        id: 'historic',
        name: 'Price History',
        field: 'historic',
        minWidth: 100,
        width: 150,
        maxWidth: 150,
        formatter: historicSparklineFormatter,
      },
      {
        id: 'execution',
        name: 'Execution Timestamp',
        field: 'execution',
        filterable: true,
        sortable: true,
        minWidth: 125,
        formatter: Formatters.dateTimeIsoAmPm,
        exportWithFormatter: true,
        type: 'dateTimeIsoAM_PM',
        filter: { model: Filters.compoundDate },
      },
    ];

    const gridOptions: GridOption = {
      autoResize: {
        container: '.trading-platform',
        autoHeight: false,
        rightPadding: 0,
        bottomPadding: 10,
      },
      formatterOptions: {
        displayNegativeNumberWithParentheses: true,
        thousandSeparator: ',',
      },
      draggableGrouping: {
        dropPlaceHolderText: 'Drop a column header here to group by any of these available columns: Currency, Market or Type',
        deleteIconCssClass: 'mdi mdi-close color-danger',
        sortAscIconCssClass: 'mdi mdi-arrow-up',
        sortDescIconCssClass: 'mdi mdi-arrow-down',
      },
      enableDraggableGrouping: true,
      createPreHeaderPanel: true,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 40,
      enableCellNavigation: true,
      enableFiltering: true,
      cellHighlightCssClass: 'changed',
    };

    columnDefinitionsRef.current = columnDefinitions;
    setGridOptions(gridOptions);
  }

  function loadData(itemCount: number) {
    // mock a dataset
    const tmpData: any[] = [];
    for (let i = 0; i < itemCount; i++) {
      const randomPercent = Math.round(Math.random() * 100);
      const randomLowQty = randomNumber(1, 50);
      const randomHighQty = randomNumber(125, 255);
      const priceChange = randomNumber(-25, 35, false);
      const price = randomNumber(priceChange, 300);
      const quantity = price < 5 ? randomHighQty : randomLowQty;
      const amount = price * quantity;
      const now = new Date();
      now.setHours(9, 30, 0);
      const currency = Math.floor(Math.random() * 10) % 2 ? 'CAD' : 'USD';
      const company = faker.company.name();

      tmpData[i] = {
        id: i,
        currency,
        trsnType: Math.round(Math.random() * 100) % 2 ? 'Buy' : 'Sell',
        company,
        symbol: currency === 'CAD' ? company.substr(0, 3).toUpperCase() + '.TO' : company.substr(0, 4).toUpperCase(),
        market: currency === 'CAD' ? 'TSX' : price > 200 ? 'Nasdaq' : 'S&P 500',
        duration: i % 33 === 0 ? null : Math.random() * 100 + '',
        percentCompleteNumber: randomPercent,
        priceChange,
        price,
        quantity,
        amount,
        execution: now,
        historic: [price],
      };
    }
    return tmpData;
  }

  function startSimulation() {
    const changes: any = {};
    const numberOfUpdates = randomNumber(minChangePerCycleRef.current, maxChangePerCycleRef.current);

    for (let i = 0; i < numberOfUpdates; i++) {
      const randomLowQty = randomNumber(1, 50);
      const randomHighQty = randomNumber(125, 255);
      const rowNumber = Math.round(Math.random() * (dataset?.length ?? 0 - 1));
      const priceChange = randomNumber(-25, 25, false);
      const prevItem = deepCopy(dataset?.[rowNumber]);
      if (!prevItem) {
        continue;
      }
      const itemTmp = { ...dataset?.[rowNumber] };
      itemTmp.priceChange = priceChange;
      itemTmp.price = itemTmp.price + priceChange < 0 ? 0 : itemTmp.price + priceChange;
      itemTmp.quantity = itemTmp.price < 5 ? randomHighQty : randomLowQty;
      itemTmp.amount = itemTmp.price * itemTmp.quantity;
      itemTmp.trsnType = Math.round(Math.random() * 100) % 2 ? 'Buy' : 'Sell';
      itemTmp.execution = new Date();
      itemTmp.historic?.push(itemTmp.price);
      itemTmp.historic = itemTmp.historic?.slice(-20); // keep a max of X historic values

      if (!changes[rowNumber]) {
        changes[rowNumber] = {};
      }

      // highlight whichever cell is being changed
      changes[rowNumber]['id'] = 'changed';
      renderCellHighlighting(itemTmp, findColumnById('priceChange'), priceChange);
      if ((prevItem.priceChange < 0 && itemTmp.priceChange > 0) || (prevItem.priceChange > 0 && itemTmp.priceChange < 0)) {
        renderCellHighlighting(itemTmp, findColumnById('price'), priceChange);
      }

      // update the data
      reactGridRef.current?.dataView.updateItem(itemTmp.id, itemTmp);
      // NOTE: we should also invalidate/render the row after updating cell data to see the new data rendered in the UI
      // but the cell highlight actually does that for us so we can skip it
    }

    timerRef.current = setTimeout(startSimulation, refreshRateRef.current || 0);
  }

  function stopSimulation() {
    clearTimeout(timerRef.current);
  }

  function findColumnById(columnName: string): Column {
    return columnDefinitionsRef.current.find((col) => col.field === columnName) as Column;
  }

  function handleRefreshRateChange(elm: HTMLInputElement) {
    const newVal = elm.value;
    setRefreshRate(+newVal);
    refreshRateRef.current = +newVal;

    const inputElmId = elm.type === 'number' ? '#refreshRateSlider' : '#refreshRateInput';
    const otherInputElm = document.querySelector<HTMLInputElement>(inputElmId);
    if (otherInputElm) {
      otherInputElm.value = newVal;
    }
  }

  function handleMinChangePerCycle(val: number) {
    setMinChangePerCycle(val);
    minChangePerCycleRef.current = val;
  }

  function handleMaxChangePerCycle(val: number) {
    setMaxChangePerCycle(val);
    maxChangePerCycleRef.current = val;
  }

  function handleHighlightDuration(val: number) {
    setHighlightDuration(val);
    highlightDurationRef.current = val;
  }

  function renderCellHighlighting(item: any, column: Column, priceChange: number) {
    if (item && column) {
      const row = reactGridRef.current?.dataView.getRowByItem(item) as number;
      if (row >= 0) {
        const hash = { [row]: { [column.id]: priceChange >= 0 ? 'changed-gain' : 'changed-loss' } };
        reactGridRef.current?.slickGrid.setCellCssStyles(`highlight_${[column.id]}${row}`, hash);

        // remove highlight after x amount of time
        setTimeout(() => removeUnsavedStylingFromCell(item, column, row), highlightDurationRef.current);
      }
    }
  }

  /** remove change highlight css class from that cell */
  function removeUnsavedStylingFromCell(_item: any, column: Column, row: number) {
    reactGridRef.current?.slickGrid.removeCellCssStyles(`highlight_${[column.id]}${row}`);
  }

  function toggleFullScreen() {
    const container = document.querySelector('.trading-platform');
    let isFullScreen = false;
    if (container?.classList.contains('full-screen')) {
      container.classList.remove('full-screen');
      isFullScreen = false;
    } else if (container) {
      container.classList.add('full-screen');
      isFullScreen = true;
    }
    setIsFullScreen(isFullScreen);
    reactGridRef.current?.resizerService.resizeGrid();
  }

  function toggleDarkMode() {
    const newDarkMode = !darkMode;
    setDarkMode(newDarkMode);
    toggleBodyBackground(newDarkMode);
    reactGridRef.current?.slickGrid.setOptions({ darkMode: newDarkMode });
  }

  function toggleBodyBackground(darkMode: boolean) {
    if (darkMode) {
      document.querySelector<HTMLDivElement>('.panel-wm-content')!.classList.add('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'dark';
    } else {
      document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
    }
  }

  function randomNumber(min: number, max: number, floor = true) {
    const number = Math.random() * (max - min + 1) + min;
    return floor ? Math.floor(number) : number;
  }

  function toggleSubTitle() {
    const newHideSubTitle = !hideSubTitle;
    setHideSubTitle(newHideSubTitle);
    const action = newHideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    reactGridRef.current?.resizerService.resizeGrid(0);
  }

  return !gridOptions ? (
    ''
  ) : (
    <div>
      <h2>
        Example 34: Real-Time Trading Platform
        <span className="float-end font18">
          see&nbsp;
          <a
            target="_blank"
            href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/react/src/examples/slickgrid/Example34.tsx"
          >
            <span className="mdi mdi-link-variant"></span> code
          </a>
        </span>
        <button
          className="ms-2 btn btn-outline-secondary btn-sm btn-icon"
          type="button"
          data-test="toggle-subtitle"
          onClick={() => toggleSubTitle()}
        >
          <span className="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
        </button>
        <button className="btn btn-outline-secondary btn-sm btn-icon ms-2" onClick={() => toggleDarkMode()} data-test="toggle-dark-mode">
          <i className="mdi mdi-theme-light-dark"></i>
          <span>Toggle Dark Mode</span>
        </button>
      </h2>

      <div className="subtitle">
        Simulate a stock trading platform with lot of price changes, it is strongly suggested to disable the{' '}
        <code>autoResize.autoHeight</code> grid option for this type of grid.
        <ul>
          <li>
            you can start/stop the simulation, you can see SlickGrid huge perf by setting: (1) lower Changes Rate, (2) increase both Changes
            per Cycle, and (3) lower Highlight Duration
          </li>
          <li>optionally change random numbers, between 0 and 10 symbols, per cycle (higher numbers means more changes)</li>
          <li>optionally change the simulation changes refresh rate in ms (lower number means more changes).</li>
          <li>you can Group by 1 of these columns: Currency, Market or Type</li>
        </ul>
      </div>

      <div className="trading-platform">
        <div className="row mb-4 simulation-form">
          <div className="col-sm-12 d-flex align-items-center">
            <div className="range">
              <label htmlFor="refreshRateRange" className="form-label me-1">
                Changes Rate(ms)
              </label>
              <input
                type="range"
                className="form-range"
                id="refreshRateRange"
                min="0"
                max="250"
                value={refreshRate}
                onInput={($event) => handleRefreshRateChange($event.target as HTMLInputElement)}
              />
              <span className="refresh-rate">
                <input
                  type="number"
                  id="refreshRateInput"
                  value={refreshRate}
                  onInput={($event) => handleRefreshRateChange($event.target as HTMLInputElement)}
                />
              </span>
            </div>
            <span className="ms-3 me-1">
              <button className="btn btn-outline-secondary btn-sm btn-icon" data-test="start-btn" onClick={() => startSimulation()}>
                <li className="mdi mdi-play-circle-outline"></li> Start Simulation
              </button>
            </span>
            <span className="me-3">
              <button className="btn btn-outline-secondary btn-sm btn-icon" data-test="stop-btn" onClick={() => stopSimulation()}>
                <li className="mdi mdi-stop-circle-outline"></li> Stop Simulation
              </button>
            </span>
            <span className="mx-1">
              <label htmlFor="change-per-cycle-input" className="me-1">
                Changes p/Cycle
              </label>
              <input
                type="number"
                id="change-per-cycle-input"
                value={minChangePerCycle}
                max={maxChangePerCycle}
                onInput={($event) => handleMinChangePerCycle(+($event.target as HTMLInputElement).value)}
              />
              &nbsp;to&nbsp;
              <input
                type="number"
                min={minChangePerCycle}
                value={maxChangePerCycle}
                onInput={($event) => handleMaxChangePerCycle(+($event.target as HTMLInputElement).value)}
              />
            </span>
            <span className="ms-2">
              <label htmlFor="highlight-input" className="me-1">
                Highlight Duration(ms)
              </label>
              <input
                type="number"
                id="highlight-input"
                data-test="highlight-input"
                value={highlightDuration}
                onInput={($event) => handleHighlightDuration(+($event.target as HTMLInputElement).value)}
              />
            </span>
            <div className="ms-auto">
              <button className="btn btn-outline-secondary btn-sm btn-icon" onClick={() => toggleFullScreen()}>
                <li className={isFullScreen ? 'mdi mdi-arrow-collapse' : 'mdi mdi-arrow-expand'}></li> Toggle Full-Screen
              </button>
            </div>
          </div>
        </div>

        <SlickgridReact
          gridId="grid34"
          columns={columnDefinitionsRef.current}
          options={gridOptions}
          dataset={dataset}
          onReactGridCreated={($event) => reactGridReady($event.detail)}
        />
      </div>
    </div>
  );
};

export default Example34;
