// frameworks/angular-slickgrid/src/demos/examples/example14.component.ts
import { Component, type OnInit } from '@angular/core';
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { PdfExportService } from '@slickgrid-universal/pdf-export';
import { AngularSlickgridComponent, type AngularGridInstance, type Column, type GridOption, type ItemMetadata } from '../../library';

@Component({
  templateUrl: './example14.component.html',
  styleUrls: ['./example14.component.scss'],
  imports: [AngularSlickgridComponent],
})
export class Example14Component implements OnInit {
  angularGrid1!: AngularGridInstance;
  angularGrid2!: AngularGridInstance;
  gridObj2: any;
  columns1!: Column[];
  columns2!: Column[];
  gridOptions1!: GridOption;
  gridOptions2!: GridOption;
  dataset1: any[] = [];
  dataset2: any[] = [];
  hideSubTitle = false;
  isColspanSpreading = false;

  ngOnInit(): void {
    this.prepareGrid1();
    this.prepareGrid2();
  }

  angularGridReady1(angularGrid: AngularGridInstance) {
    this.angularGrid1 = angularGrid;
  }

  angularGridReady2(angularGrid: AngularGridInstance) {
    this.angularGrid2 = angularGrid;
    this.gridObj2 = angularGrid.slickGrid;
  }

  prepareGrid1() {
    this.columns1 = [
      { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
      { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
      { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
      { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
      { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
      { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
    ];

    this.gridOptions1 = {
      gridHeight: 275,
      gridWidth: 800,
      enableAutoResize: false,
      enableCellNavigation: true,
      enableSorting: true,
      createPreHeaderPanel: true,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 28,
      rowHeight: 33,
      explicitInitialization: true,
      dataView: {
        globalItemMetadataProvider: {
          getRowMetadata: (item: any) => this.renderDifferentColspan(item),
        },
      },
      gridMenu: {
        iconButtonContainer: 'preheader', // we can display the grid menu icon in either the preheader or in the column header (default)
      },
      enablePdfExport: true,
      enableExcelExport: true,
      excelExportOptions: {
        exportWithFormatter: false,
      },
      externalResources: [new ExcelExportService(), new PdfExportService()],
      spreadHiddenColspan: this.isColspanSpreading,
    };

    this.dataset1 = this.getData(500);
  }

  prepareGrid2() {
    this.columns2 = [
      {
        id: 'sel',
        name: '#',
        field: 'num',
        behavior: 'select',
        cssClass: 'cell-selection',
        width: 40,
        resizable: false,
        selectable: false,
      },
      { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
      { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
      { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
      { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
      { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
      { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
    ];

    this.gridOptions2 = {
      gridHeight: 275,
      gridWidth: 800,
      enableCellNavigation: true,
      createPreHeaderPanel: true,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 25,
      explicitInitialization: true,
      pinning: { columns: { left: 2 } },
      rowHeight: 33,
      gridMenu: { hideClearPinningCommand: false },
      headerMenu: { hidePinColumnCommand: false, hidePinningColumnsCommand: false },
      enablePdfExport: true,
      enableExcelExport: true,
      excelExportOptions: {
        exportWithFormatter: false,
      },
      externalResources: [new ExcelExportService(), new PdfExportService()],
    };

    this.dataset2 = this.getData(500);
  }

  getData(count: number) {
    // Set up some test columns.
    const mockDataset = [];
    for (let i = 0; i < count; i++) {
      mockDataset[i] = {
        id: i,
        num: i,
        title: 'Task ' + i,
        duration: '5 days',
        percentComplete: Math.round(Math.random() * 100),
        start: '01/01/2009',
        finish: '01/05/2009',
        effortDriven: i % 5 === 0,
      };
    }
    return mockDataset;
  }

  setPinnedColumns2(pinnedCols: number) {
    this.gridObj2.setOptions({ pinning: { columns: { left: pinnedCols } } });
    this.gridOptions2 = this.gridObj2.getOptions();
  }

  /**
   * A callback to render different row column span
   * Your callback will always have the "item" argument which you can use to decide on the colspan
   * Your return must always be in the form of:: return { columns: {}}
   */
  renderDifferentColspan(item: any): ItemMetadata {
    if (item.id % 2 === 1) {
      return {
        columns: {
          duration: {
            colspan: 3, // "duration" will span over 3 columns
          },
        },
      };
    }
    return {
      columns: {
        0: {
          colspan: '*', // starting at column index 0, we will span accross all column (*)
        },
      },
    };
  }

  spreadColspan() {
    this.isColspanSpreading = !this.isColspanSpreading;
    this.angularGrid1.slickGrid?.setOptions({ spreadHiddenColspan: this.isColspanSpreading });
    this.angularGrid1.slickGrid?.resetActiveCell();
    this.angularGrid1.slickGrid?.invalidate();
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    this.angularGrid2.resizerService.resizeGrid(0);
  }
}

<div id="demo-container" class="container-fluid">
  <h2>
    Example 14: Column Span & Header Grouping
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example14.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    This example demonstrates how to easily span a row over multiple columns & how to group header titles.
    <ul>
      <li>
        Note that you can add Sort but remember that it will sort by the data which the row contains, even if the data is visually hidden by
        colspan it will still sort it
      </li>
      <li>
        Header Grouping spanning accross multiple columns is working but has some UI issues on window resize. If anyone can fix it, probably
        some CSS issues, please let us know.
      </li>
    </ul>
  </div>

  <h3>
    Grid 1 <small>(with Header Grouping &amp; Colspan)</small>
    <button
      class="btn btn-outline-secondary btn-sm btn-icon ms-2"
      (click)="spreadColspan()"
      data-test="spread-colspan-button"
      title="Should we always spread the same visible column count with or without hidden columns?"
    >
      <span>Toggle Spreading of ColSpan with/without Hidden Columns</span>
    </button>
  </h3>

  <angular-slickgrid
    gridId="grid1"
    [columns]="columnDefinitions1"
    [options]="gridOptions1"
    [dataset]="dataset1"
    (onAngularGridCreated)="angularGridReady1($event.detail)"
  >
  </angular-slickgrid>

  <hr />

  <h3>Grid 2 <small>(with Header Grouping &amp; Frozen/Pinned Columns)</small></h3>
  <div class="col-sm 12">
    <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="setFrozenColumns2(-1)" data-test="remove-frozen-column-button">
      <i class="mdi mdi-close"></i> Remove Frozen Columns
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="setFrozenColumns2(2)" data-test="set-3frozen-columns">
      <i class="mdi mdi-pin-outline"></i> Set 3 Frozen Columns
    </button>
  </div>
  <angular-slickgrid
    gridId="grid2"
    [columns]="columnDefinitions2"
    [options]="gridOptions2"
    [dataset]="dataset2"
    (onAngularGridCreated)="angularGridReady2($event.detail)"
  >
  </angular-slickgrid>
</div>

// demos/vue/src/components/Example14.vue
<script setup lang="ts">
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { PdfExportService } from '@slickgrid-universal/pdf-export';
import { SlickgridVue, type Column, type GridOption, type ItemMetadata, type SlickgridVueInstance } from 'slickgrid-vue';
import { onBeforeMount, ref, type Ref } from 'vue';

const NB_ITEMS = 500;
const gridOptions1 = ref<GridOption>();
const gridOptions2 = ref<GridOption>();
const columns1: Ref<Column[]> = ref([]);
const columns2: Ref<Column[]> = ref([]);
const dataset1 = ref<any[]>([]);
const dataset2 = ref<any[]>([]);
const showSubTitle = ref(true);
let isColspanSpreading = ref(false);
let vueGrid1!: SlickgridVueInstance;
let vueGrid2!: SlickgridVueInstance;

onBeforeMount(() => {
  definedGrid1();
  definedGrid2();

  // populate the dataset once the grid is ready
  dataset1.value = getData(NB_ITEMS);
  dataset2.value = getData(NB_ITEMS);
});

function definedGrid1() {
  columns1.value = [
    { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
    { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
    { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
    { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
    { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
    { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
  ];

  gridOptions1.value = {
    enableAutoResize: false,
    enableCellNavigation: true,
    enableColumnReorder: false,
    enableSorting: true,
    createPreHeaderPanel: true,
    showPreHeaderPanel: true,
    preHeaderPanelHeight: 28,
    gridHeight: 275,
    gridWidth: 800,
    rowHeight: 33,
    enablePdfExport: true,
    enableExcelExport: true,
    excelExportOptions: {
      exportWithFormatter: false,
    },
    externalResources: [new ExcelExportService(), new PdfExportService()],
    explicitInitialization: true,
    dataView: {
      globalItemMetadataProvider: {
        getRowMetadata: (item: any, row: number) => renderDifferentColspan(item, row),
      },
    },
    gridMenu: {
      iconButtonContainer: 'preheader', // we can display the grid menu icon in either the preheader or in the column header (default)
    },
    spreadHiddenColspan: isColspanSpreading.value,
  };
}

function definedGrid2() {
  columns2.value = [
    {
      id: 'sel',
      name: '#',
      field: 'num',
      behavior: 'select',
      cssClass: 'cell-selection',
      width: 40,
      resizable: false,
      selectable: false,
    },
    { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
    { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
    { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
    { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
    { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
    { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
  ];

  gridOptions2.value = {
    enableCellNavigation: true,
    enableColumnReorder: false,
    createPreHeaderPanel: true,
    showPreHeaderPanel: true,
    preHeaderPanelHeight: 25,
    explicitInitialization: true,
    gridHeight: 275,
    gridWidth: 800,
    rowHeight: 33,
    pinning: { columns: { left: 2 } },
    enablePdfExport: true,
    enableExcelExport: true,
    excelExportOptions: {
      exportWithFormatter: false,
    },
    externalResources: [new ExcelExportService(), new PdfExportService()],
    gridMenu: { hideClearPinningCommand: false },
    headerMenu: { hidePinColumnCommand: false, hidePinningColumnsCommand: false },
  };
}

function getData(count: number) {
  // Set up some test columns.
  const mockDataset: any[] = [];
  for (let i = 0; i < count; i++) {
    mockDataset[i] = {
      id: i,
      num: i,
      title: 'Task ' + i,
      duration: '5 days',
      percentComplete: Math.round(Math.random() * 100),
      start: '01/01/2009',
      finish: '01/05/2009',
      effortDriven: i % 5 === 0,
    };
  }
  return mockDataset;
}

function setPinnedColumns2(pinnedCols: number) {
  vueGrid2.slickGrid.setOptions({
    pinning: {
      columns: {
        left: pinnedCols >= 0 ? pinnedCols : [],
      },
    },
  });
  gridOptions2.value = vueGrid2.slickGrid.getOptions();
}

/**
 * A callback to render different row column span
 * Your callback will always have the "item" argument which you can use to decide on the colspan
 * Your return must always be in the form of:: return { columns: {}}
 */
function renderDifferentColspan(item: any, row: number): ItemMetadata {
  if (item.id % 2 === 1 || row % 2 === 1) {
    return {
      columns: {
        duration: {
          colspan: 3, // "duration" will span over 3 columns
        },
      },
    };
  }
  return {
    columns: {
      0: {
        colspan: '*', // starting at column index 0, we will span accross all column (*)
      },
    },
  };
}

function spreadColspan() {
  isColspanSpreading.value = !isColspanSpreading.value;
  vueGrid1.slickGrid?.setOptions({ spreadHiddenColspan: isColspanSpreading.value });
  vueGrid1.slickGrid?.resetActiveCell();
  vueGrid1.slickGrid?.invalidate();
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
  queueMicrotask(() => {
    vueGrid1.resizerService.resizeGrid();
    vueGrid2.resizerService.resizeGrid();
  });
}

function vueGrid1Ready(grid: SlickgridVueInstance) {
  vueGrid1 = grid;
}
function vueGrid2Ready(grid: SlickgridVueInstance) {
  vueGrid2 = grid;
}
</script>

<template>
  <h2>
    Example 14: Column Span & Header Grouping
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example14.vue"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    This example demonstrates how to easily span a row over multiple columns & how to group header titles.
    <ul>
      <li>
        Note that you can add Sort but remember that it will sort by the data which the row contains, even if the data is visually hidden by
        colspan it will still sort it
      </li>
    </ul>
  </div>

  <h3>
    Grid 1 <small>(with Header Grouping &amp; Colspan)</small>
    <button
      class="btn btn-outline-secondary btn-sm btn-icon ms-2"
      @click="spreadColspan()"
      data-test="spread-colspan-button"
      title="Should we always spread the same visible column count with or without hidden columns?"
    >
      <span>Toggle Spreading of ColSpan with/without Hidden Columns</span>
    </button>
  </h3>

  <slickgrid-vue
    v-model:options="gridOptions1!"
    v-model:columns="columns1"
    v-model:dataset="dataset1"
    grid-id="grid1"
    @onVueGridCreated="vueGrid1Ready($event.detail)"
  >
  </slickgrid-vue>

  <hr />

  <h3>Grid 2 <small>(with Header Grouping &amp; Pinned Columns)</small></h3>

  <div class="col-sm 12">
    <button class="btn btn-outline-secondary btn-sm btn-icon" data-test="remove-pinned-column-button" @click="setPinnedColumns2(-1)">
      <i class="mdi mdi-close"></i> Remove Pinned Columns
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon ms-1" data-test="set-3pinned-columns" @click="setPinnedColumns2(2)">
      <i class="mdi mdi-pin-outline"></i> Set 3 Pinned Columns
    </button>
  </div>

  <slickgrid-vue
    v-model:options="gridOptions2!"
    v-model:columns="columns2"
    v-model:dataset="dataset2"
    grid-id="grid2"
    @onVueGridCreated="vueGrid2Ready($event.detail)"
  >
  </slickgrid-vue>
</template>
