// frameworks/angular-slickgrid/src/demos/examples/example13.component.ts
import { Component, type OnInit } from '@angular/core';
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { PdfExportService } from '@slickgrid-universal/pdf-export';
import { TextExportService } from '@slickgrid-universal/text-export';
import {
  Aggregators,
  AngularSlickgridComponent,
  Filters,
  Formatters,
  GroupTotalFormatters,
  SortComparers,
  SortDirectionNumber,
  type AngularGridInstance,
  type Column,
  type GridOption,
  type Grouping,
} from '../../library';

const NB_ITEMS = 5000;

@Component({
  templateUrl: './example13.component.html',
  styles: ['.slick-column-name { .btn:focus { outline: 2px solid rgba(53, 53, 53, 0.5); } }'],
  imports: [AngularSlickgridComponent],
})
export class Example13Component implements OnInit {
  angularGrid!: AngularGridInstance;
  columns!: Column[];
  gridOptions!: GridOption;
  dataset!: any[];
  gridObj: any;
  dataviewObj: any;
  hideSubTitle = false;
  processing = false;
  excelExportService = new ExcelExportService();
  pdfExportService = new PdfExportService();
  textExportService = new TextExportService();

  ngOnInit(): void {
    this.initializeGrid();
  }

  initializeGrid() {
    // add a simple button with event listener on 1st column for testing purposes
    // a simple button with click event
    const nameElementColumn1 = document.createElement('div');
    const btn = document.createElement('button');
    const btnLabel = document.createElement('span');
    btnLabel.className = 'mdi mdi-help-circle no-padding';
    btn.dataset.test = 'col1-hello-btn';
    btn.className = 'btn btn-outline-secondary btn-xs btn-icon ms-1';
    btn.textContent = 'Click me';
    btn.title = 'simple column header test with a button click listener';
    btn.addEventListener('click', () => alert('Hello World'));
    btn.appendChild(btnLabel);
    nameElementColumn1.appendChild(document.createTextNode('Id '));
    nameElementColumn1.appendChild(btn);

    this.columns = [
      {
        id: 'num',
        name: nameElementColumn1,
        field: 'num',
        type: 'number',
        columnPickerLabel: 'Custom Label', // add a custom label for the ColumnPicker/GridMenu when default header value extractor doesn't work for you ()
        width: 140,
        maxWidth: 150,
        excludeFromExport: true,
        resizable: true,
        filterable: true,
        selectable: false,
      },
      {
        id: 'title',
        name: 'Title',
        field: 'title',
        width: 50,
        minWidth: 50,
        cssClass: 'cell-title',
        filterable: true,
        sortable: true,
      },
      {
        id: 'duration',
        name: 'Duration',
        field: 'duration',
        minWidth: 50,
        width: 60,
        filterable: true,
        filter: { model: Filters.slider, operator: '>=' },
        sortable: true,
        type: 'number',
        groupTotalsFormatter: GroupTotalFormatters.sumTotals,
        params: { groupFormatterPrefix: 'Total: ' },
      },
      {
        id: '%',
        name: '% Complete',
        field: 'percentComplete',
        minWidth: 70,
        width: 90,
        formatter: Formatters.percentCompleteBar,
        filterable: true,
        filter: { model: Filters.compoundSlider },
        sortable: true,
        type: 'number',
        groupTotalsFormatter: GroupTotalFormatters.avgTotalsPercentage,
        params: { groupFormatterPrefix: '<i>Avg</i>: ' },
      },
      {
        id: 'start',
        name: 'Start',
        field: 'start',
        minWidth: 60,
        filterable: true,
        filter: { model: Filters.compoundDate },
        sortable: true,
        type: 'dateIso',
        formatter: Formatters.dateIso,
        exportWithFormatter: true,
      },
      {
        id: 'finish',
        name: 'Finish',
        field: 'finish',
        minWidth: 60,
        filterable: true,
        filter: { model: Filters.compoundDate },
        sortable: true,
        type: 'dateIso',
        formatter: Formatters.dateIso,
        exportWithFormatter: true,
      },
      {
        id: 'cost',
        name: 'Cost',
        field: 'cost',
        minWidth: 70,
        width: 80,
        sortable: true,
        filterable: true,
        filter: { model: Filters.compoundInputNumber },
        type: 'number',
        formatter: Formatters.currency,
        groupTotalsFormatter: GroupTotalFormatters.sumTotalsCurrency,
        params: {
          displayNegativeNumberWithParentheses: true,
          currencyPrefix: '€',
          groupFormatterCurrencyPrefix: '€',
          minDecimal: 2,
          maxDecimal: 4,
          groupFormatterPrefix: '<b>Total</b>: ',
        },
        excelExportOptions: {
          style: {
            font: { outline: true, italic: true },
            format: '€0.00##;[Red](€0.00##)',
          },
          width: 18,
        },
        groupTotalsExcelExportOptions: {
          style: {
            alignment: { horizontal: 'center' },
            font: { bold: true, color: 'FF005289', underline: 'single', fontName: 'Consolas', size: 10 },
            fill: { type: 'pattern', patternType: 'solid', fgColor: 'FFE6F2F6' },
            border: {
              top: { color: 'FFa500ff', style: 'thick' },
              left: { color: 'FFa500ff', style: 'medium' },
              right: { color: 'FFa500ff', style: 'dotted' },
              bottom: { color: 'FFa500ff', style: 'double' },
            },
            format: '"Total: "€0.00##;[Red]"Total: "(€0.00##)',
          },
        },
      },
      {
        id: 'effort-driven',
        name: 'Effort Driven',
        minWidth: 20,
        width: 80,
        maxWidth: 80,
        cssClass: 'cell-effort-driven',
        field: 'effortDriven',
        formatter: Formatters.checkmarkMaterial,
        sortable: true,
        filterable: true,
        filter: {
          collection: [
            { value: '', label: '' },
            { value: true, label: 'True' },
            { value: false, label: 'False' },
          ],
          model: Filters.singleSelect,
        },
      },
    ];

    this.gridOptions = {
      autoResize: {
        container: '#demo-container',
        rightPadding: 10,
      },
      enableExcelExport: true,
      enableFiltering: true,
      // you could debounce/throttle the input text filter if you have lots of data
      // filterTypingDebounce: 250,
      enableGrouping: true,
      enableTextExport: true,
      gridMenu: {
        hideExportTextDelimitedCommand: false,
      },
      excelExportOptions: { sanitizeDataExport: true },
      textExportOptions: { sanitizeDataExport: true },
      externalResources: [this.excelExportService, this.pdfExportService, this.textExportService],
      showCustomFooter: true, // display some metrics in the bottom custom footer
      customFooterOptions: {
        // optionally display some text on the left footer container
        hideMetrics: false,
        hideTotalItemCount: false,
        hideLastUpdateTimestamp: false,
      },
      enablePdfExport: true,
      pdfExportOptions: {
        repeatHeadersOnEachPage: false,
        sanitizeDataExport: true,
        documentTitle: 'Grouping Grid',
      },
    };

    this.loadData(NB_ITEMS);
  }

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    this.gridObj = angularGrid.slickGrid;
    this.dataviewObj = angularGrid.dataView;
    this.groupByDuration(); // group by duration on page load
  }

  loadData(rowCount: number) {
    // mock a dataset
    const tmpData = [];
    for (let i = 0; i < rowCount; i++) {
      const randomYear = 2000 + Math.floor(Math.random() * 10);
      const randomMonth = Math.floor(Math.random() * 11);
      const randomDay = Math.floor(Math.random() * 29);
      const randomPercent = Math.round(Math.random() * 100);
      const randomCost = i % 33 === 0 ? null : Math.round(Math.random() * 10000) / 100;

      tmpData[i] = {
        id: 'id_' + i,
        num: i,
        title: 'Task ' + i,
        duration: Math.round(Math.random() * 100) + '',
        percentComplete: randomPercent,
        percentCompleteNumber: randomPercent,
        start: new Date(randomYear, randomMonth, randomDay),
        finish: new Date(randomYear, randomMonth + 1, randomDay),
        cost: i % 3 ? randomCost : randomCost !== null ? -randomCost : null,
        effortDriven: i % 5 === 0,
      };
    }
    this.dataset = tmpData;
  }

  clearGrouping() {
    this.dataviewObj.setGrouping([]);
  }

  clearFilters() {
    this.angularGrid.filterService.clearFilters();
  }

  collapseAllGroups() {
    this.dataviewObj.collapseAllGroups();
  }

  expandAllGroups() {
    this.dataviewObj.expandAllGroups();
  }

  exportToExcel() {
    this.excelExportService.exportToExcel({
      filename: 'Export',
      format: 'xlsx',
    });
  }

  exportToPdf() {
    this.pdfExportService.exportToPdf({ filename: 'Export' });
  }

  exportToFile(type = 'csv') {
    this.textExportService.exportToFile({
      delimiter: type === 'csv' ? ',' : '\t',
      filename: 'myExport',
      format: type === 'csv' ? 'csv' : 'txt',
    });
  }

  groupByDuration() {
    // you need to manually add the sort icon(s) in UI
    this.angularGrid.filterService.setSortColumnIcons([{ columnId: 'duration', sortAsc: true }]);
    this.dataviewObj.setGrouping({
      getter: 'duration',
      formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
      aggregators: [new Aggregators.Avg('percentComplete'), new Aggregators.Sum('cost')],
      comparer: (a, b) => SortComparers.numeric(a.value, b.value, SortDirectionNumber.asc),
      aggregateCollapsed: false,
      lazyTotalsCalculation: true,
    } as Grouping);
    this.gridObj.invalidate(); // invalidate all rows and re-render
  }

  groupByDurationOrderByCount(aggregateCollapsed: boolean) {
    this.angularGrid.filterService.setSortColumnIcons([]);
    this.dataviewObj.setGrouping({
      getter: 'duration',
      formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
      comparer: (a, b) => {
        return a.count - b.count;
      },
      aggregators: [new Aggregators.Avg('percentComplete'), new Aggregators.Sum('cost')],
      aggregateCollapsed,
      lazyTotalsCalculation: true,
    } as Grouping);
    this.gridObj.invalidate(); // invalidate all rows and re-render
  }

  groupByDurationEffortDriven() {
    // you need to manually add the sort icon(s) in UI
    const sortColumns = [
      { columnId: 'duration', sortAsc: true },
      { columnId: 'effortDriven', sortAsc: true },
    ];
    this.angularGrid.filterService.setSortColumnIcons(sortColumns);
    this.dataviewObj.setGrouping([
      {
        getter: 'duration',
        formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
        aggregateCollapsed: true,
        lazyTotalsCalculation: true,
      },
      {
        getter: 'effortDriven',
        formatter: (g) => `Effort-Driven: ${g.value ? 'True' : 'False'} <span style="color:green">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Avg('percentComplete'), new Aggregators.Sum('cost')],
        collapsed: true,
        lazyTotalsCalculation: true,
      },
    ] as Grouping[]);
    this.gridObj.invalidate(); // invalidate all rows and re-render
  }

  groupByDurationEffortDrivenPercent() {
    // you need to manually add the sort icon(s) in UI
    const sortColumns = [
      { columnId: 'duration', sortAsc: true },
      { columnId: 'effortDriven', sortAsc: true },
      { columnId: 'percentComplete', sortAsc: true },
    ];
    this.angularGrid.filterService.setSortColumnIcons(sortColumns);
    this.dataviewObj.setGrouping([
      {
        getter: 'duration',
        formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
        aggregateCollapsed: true,
        lazyTotalsCalculation: true,
      },
      {
        getter: 'effortDriven',
        formatter: (g) => `Effort-Driven: ${g.value ? 'True' : 'False'}  <span style="color:green">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
        lazyTotalsCalculation: true,
      },
      {
        getter: 'percentComplete',
        formatter: (g) => `% Complete: ${g.value}  <span style="color:green">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Avg('percentComplete')],
        aggregateCollapsed: true,
        collapsed: true,
        lazyTotalsCalculation: true,
      },
    ] as Grouping[]);
    this.gridObj.invalidate(); // invalidate all rows and re-render
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    this.angularGrid.resizerService.resizeGrid(0);
  }
}

<div id="demo-container" class="container-fluid">
  <h2>
    Example 13: Grouping & Aggregators
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example13.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    (<a href="https://ghiscoding.gitbook.io/angular-slickgrid/grid-functionalities/grouping-and-aggregators" target="_blank">Wiki docs</a>)
    <ul>
      <li>Fully dynamic and interactive multi-level grouping with filtering and aggregates over 50'000 items</li>
      <li>Each grouping level can have its own aggregates (over child rows, child groups, or all descendant rows)..</li>
    </ul>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="add-5k-rows-btn" (click)="loadData(5000)">5K rows</button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="add-50k-rows-btn" (click)="loadData(50000)">50K rows</button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="clear-grouping-btn" (click)="clearGrouping()">
        <i class="mdi mdi-close"></i> Clear Grouping
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="clear-filter-btn" (click)="clearFilters()">
        <i class="mdi mdi-close"></i> Clear Filters
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="collapse-all-btn" (click)="collapseAllGroups()">
        <i class="mdi mdi-arrow-collapse"></i> Collapse all groups
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="expand-all-btn" (click)="expandAllGroups()">
        <i class="mdi mdi-arrow-expand"></i> Expand all groups
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="export-excel-btn" (click)="exportToExcel()">
        <i class="mdi mdi-file-excel-outline text-success"></i> Export to Excel
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="export-pdf-btn" (click)="exportToPdf()">
        <i class="mdi mdi-file-pdf-outline text-danger"></i> Export to PDF
      </button>
    </div>
  </div>
  <hr />
  <div class="row">
    <div class="col-sm-12">
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="group-duration-sort-value-btn" (click)="groupByDuration()">
        Group by duration &amp; sort groups by value
      </button>
      <button
        class="btn btn-outline-secondary btn-xs btn-icon"
        data-test="group-duration-sort-count-btn"
        (click)="groupByDurationOrderByCount(false)"
      >
        Group by duration &amp; sort groups by count
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <button
        class="btn btn-outline-secondary btn-xs btn-icon"
        data-test="group-duration-sort-count-collapse-btn"
        (click)="groupByDurationOrderByCount(true)"
      >
        Group by duration &amp; sort groups by count, aggregate collapsed
      </button>
      <button
        class="btn btn-outline-secondary btn-xs btn-icon"
        data-test="group-duration-effort-btn"
        (click)="groupByDurationEffortDriven()"
      >
        Group by duration then effort-driven
      </button>
      <button
        class="btn btn-outline-secondary btn-xs btn-icon"
        data-test="group-duration-effort-percent-btn"
        (click)="groupByDurationEffortDrivenPercent()"
      >
        Group by duration then effort-driven then percent.
      </button>
      <span [hidden]="!processing">
        <i class="mdi mdi-sync mdi-spin-1s"></i>
      </span>
    </div>
  </div>

  <angular-slickgrid
    gridId="grid13"
    [dataset]="dataset"
    [columns]="columns"
    [options]="gridOptions"
    (onBeforeExportToTextFile)="processing = true"
    (onAfterExportToTextFile)="processing = false"
    (onBeforeExportToExcel)="processing = true"
    (onAfterExportToExcel)="processing = false"
    (onBeforeExportToPdf)="processing = true"
    (onAfterExportToPdf)="processing = false"
    (onAngularGridCreated)="angularGridReady($event.detail)"
  >
  </angular-slickgrid>
</div>

// demos/vue/src/components/Example13.vue
<script setup lang="ts">
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { PdfExportService } from '@slickgrid-universal/pdf-export';
import { TextExportService } from '@slickgrid-universal/text-export';
import {
  Aggregators,
  Filters,
  Formatters,
  GroupTotalFormatters,
  SlickgridVue,
  SortComparers,
  SortDirectionNumber,
  type Column,
  type GridOption,
  type Grouping,
  type SlickgridVueInstance,
} from 'slickgrid-vue';
import { onBeforeMount, ref, type Ref } from 'vue';

const NB_ITEMS = 5000;
const gridOptions = ref<GridOption>();
const columns: Ref<Column[]> = ref([]);
const dataset = ref<any[]>([]);
const showSubTitle = ref(true);
const processing = ref(false);
const excelExportService = new ExcelExportService();
const pdfExportService = new PdfExportService();
const textExportService = new TextExportService();
let vueGrid!: SlickgridVueInstance;

onBeforeMount(() => {
  defineGrid();
  // mock some data (different in each dataset)
  loadData(NB_ITEMS);
});

/* Define grid Options and Columns */
function defineGrid() {
  // add a simple button with event listener on 1st column for testing purposes
  // a simple button with click event
  const nameElementColumn1 = document.createElement('div');
  const btn = document.createElement('button');
  const btnLabel = document.createElement('span');
  btnLabel.className = 'mdi mdi-help-circle no-padding';
  btn.dataset.test = 'col1-hello-btn';
  btn.className = 'btn btn-outline-secondary btn-xs btn-icon ms-1';
  btn.textContent = 'Click me';
  btn.title = 'simple column header test with a button click listener';
  btn.addEventListener('click', () => alert('Hello World'));
  btn.appendChild(btnLabel);
  nameElementColumn1.appendChild(document.createTextNode('Id '));
  nameElementColumn1.appendChild(btn);

  columns.value = [
    {
      id: 'num',
      name: nameElementColumn1,
      field: 'num',
      type: 'number',
      columnPickerLabel: 'Custom Label', // add a custom label for the ColumnPicker/GridMenu when default header value extractor doesn't work for you ()
      width: 140,
      maxWidth: 150,
      excludeFromExport: true,
      resizable: true,
      filterable: true,
      selectable: false,
    },
    {
      id: 'title',
      name: 'Title',
      field: 'title',
      width: 50,
      minWidth: 50,
      cssClass: 'cell-title',
      filterable: true,
      sortable: true,
    },
    {
      id: 'duration',
      name: 'Duration',
      field: 'duration',
      minWidth: 50,
      width: 60,
      filterable: true,
      filter: { model: Filters.slider, operator: '>=' },
      sortable: true,
      type: 'number',
      groupTotalsFormatter: GroupTotalFormatters.sumTotals,
      params: { groupFormatterPrefix: 'Total: ' },
    },
    {
      id: 'percentComplete',
      name: '% Complete',
      field: 'percentComplete',
      minWidth: 70,
      width: 90,
      formatter: Formatters.percentCompleteBar,
      filterable: true,
      filter: { model: Filters.compoundSlider },
      sortable: true,
      type: 'number',
      groupTotalsFormatter: GroupTotalFormatters.avgTotalsPercentage,
      params: { groupFormatterPrefix: '<i>Avg</i>: ' },
    },
    {
      id: 'start',
      name: 'Start',
      field: 'start',
      minWidth: 60,
      maxWidth: 130,
      filterable: true,
      filter: { model: Filters.compoundDate },
      sortable: true,
      type: 'dateIso',
      formatter: Formatters.dateIso,
      exportWithFormatter: true,
    },
    {
      id: 'finish',
      name: 'Finish',
      field: 'finish',
      minWidth: 60,
      maxWidth: 130,
      filterable: true,
      filter: { model: Filters.compoundDate },
      sortable: true,
      type: 'dateIso',
      formatter: Formatters.dateIso,
      exportWithFormatter: true,
    },
    {
      id: 'cost',
      name: 'Cost',
      field: 'cost',
      minWidth: 70,
      width: 80,
      sortable: true,
      filterable: true,
      filter: { model: Filters.compoundInputNumber },
      type: 'number',
      formatter: Formatters.currency,
      groupTotalsFormatter: GroupTotalFormatters.sumTotalsCurrency,
      params: {
        displayNegativeNumberWithParentheses: true,
        currencyPrefix: '€',
        groupFormatterCurrencyPrefix: '€',
        minDecimal: 2,
        maxDecimal: 4,
        groupFormatterPrefix: '<b>Total</b>: ',
      },
      excelExportOptions: {
        style: {
          font: { outline: true, italic: true },
          format: '€0.00##;[Red](€0.00##)',
        },
        width: 18,
      },
      groupTotalsExcelExportOptions: {
        style: {
          alignment: { horizontal: 'center' },
          font: { bold: true, color: 'FF005289', underline: 'single', fontName: 'Consolas', size: 10 },
          fill: { type: 'pattern', patternType: 'solid', fgColor: 'FFE6F2F6' },
          border: {
            top: { color: 'FFa500ff', style: 'thick' },
            left: { color: 'FFa500ff', style: 'medium' },
            right: { color: 'FFa500ff', style: 'dotted' },
            bottom: { color: 'FFa500ff', style: 'double' },
          },
          format: '"Total: "€0.00##;[Red]"Total: "(€0.00##)',
        },
      },
    },
    {
      id: 'effortDriven',
      name: 'Effort Driven',
      minWidth: 30,
      width: 80,
      maxWidth: 90,
      cssClass: 'cell-effort-driven',
      field: 'effortDriven',
      formatter: Formatters.checkmarkMaterial,
      sortable: true,
      filterable: true,
      filter: {
        collection: [
          { value: '', label: '' },
          { value: true, label: 'True' },
          { value: false, label: 'False' },
        ],
        model: Filters.singleSelect,
      },
    },
  ];

  gridOptions.value = {
    autoResize: {
      container: '#demo-container',
      rightPadding: 10,
    },
    enableFiltering: true,
    // you could debounce/throttle the input text filter if you have lots of data
    // filterTypingDebounce: 250,
    enableGrouping: true,
    enableExcelExport: true,
    enableTextExport: true,
    excelExportOptions: { sanitizeDataExport: true },
    textExportOptions: { sanitizeDataExport: true },
    externalResources: [excelExportService, pdfExportService, textExportService],
    showCustomFooter: true,
    customFooterOptions: {
      // optionally display some text on the left footer container
      hideMetrics: false,
      hideTotalItemCount: false,
      hideLastUpdateTimestamp: false,
    },
    enablePdfExport: true,
    pdfExportOptions: {
      repeatHeadersOnEachPage: false,
      sanitizeDataExport: true,
      documentTitle: 'Grouping Grid',
    },
  };
}

function loadData(count: number) {
  // mock a dataset
  const tmpData: any[] = [];
  for (let i = 0; i < count; i++) {
    const randomYear = 2000 + Math.floor(Math.random() * 10);
    const randomMonth = Math.floor(Math.random() * 11);
    const randomDay = Math.floor(Math.random() * 29);
    const randomPercent = Math.round(Math.random() * 100);
    const randomCost = i % 33 === 0 ? null : Math.round(Math.random() * 10000) / 100;

    tmpData[i] = {
      id: 'id_' + i,
      num: i,
      title: 'Task ' + i,
      duration: Math.round(Math.random() * 100) + '',
      percentComplete: randomPercent,
      percentCompleteNumber: randomPercent,
      start: new Date(randomYear, randomMonth, randomDay),
      finish: new Date(randomYear, randomMonth + 1, randomDay),
      cost: i % 3 ? randomCost : randomCost !== null ? -randomCost : null,
      effortDriven: i % 5 === 0,
    };
  }
  dataset.value = tmpData;
}

function clearGrouping() {
  vueGrid.dataView.setGrouping([]);
}

function clearFilters() {
  vueGrid.filterService.clearFilters();
}

function collapseAllGroups() {
  vueGrid.dataView.collapseAllGroups();
}

function expandAllGroups() {
  vueGrid.dataView.expandAllGroups();
}

function exportToExcel() {
  excelExportService.exportToExcel({
    filename: 'Export',
    format: 'xlsx',
  });
}

function exportToPdf() {
  pdfExportService.exportToPdf({ filename: 'Export' });
}

function groupByDuration() {
  // you need to manually add the sort icon(s) in UI
  vueGrid.filterService.setSortColumnIcons([{ columnId: 'duration', sortAsc: true }]);
  vueGrid.dataView.setGrouping({
    getter: 'duration',
    formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
    comparer: (a, b) => {
      return SortComparers.numeric(a.value, b.value, SortDirectionNumber.asc);
    },
    aggregators: [new Aggregators.Avg('percentComplete'), new Aggregators.Sum('cost')],
    aggregateCollapsed: false,
    lazyTotalsCalculation: true,
  } as Grouping);
  vueGrid.slickGrid.invalidate(); // invalidate all rows and re-render
}

function groupByDurationOrderByCount(aggregateCollapsed: boolean) {
  vueGrid.filterService.setSortColumnIcons([]);
  vueGrid.dataView.setGrouping({
    getter: 'duration',
    formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
    comparer: (a, b) => {
      return a.count - b.count;
    },
    aggregators: [new Aggregators.Avg('percentComplete'), new Aggregators.Sum('cost')],
    aggregateCollapsed,
    lazyTotalsCalculation: true,
  } as Grouping);
  vueGrid.slickGrid.invalidate(); // invalidate all rows and re-render
}

function groupByDurationEffortDriven() {
  // you need to manually add the sort icon(s) in UI
  const sortColumns = [
    { columnId: 'duration', sortAsc: true },
    { columnId: 'effortDriven', sortAsc: true },
  ];
  vueGrid.filterService.setSortColumnIcons(sortColumns);
  vueGrid.dataView.setGrouping([
    {
      getter: 'duration',
      formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
      aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
      aggregateCollapsed: true,
      lazyTotalsCalculation: true,
    },
    {
      getter: 'effortDriven',
      formatter: (g) => `Effort-Driven: ${g.value ? 'True' : 'False'} <span style="color:green">(${g.count} items)</span>`,
      aggregators: [new Aggregators.Avg('percentComplete'), new Aggregators.Sum('cost')],
      collapsed: true,
      lazyTotalsCalculation: true,
    },
  ] as Grouping[]);
  vueGrid.slickGrid.invalidate(); // invalidate all rows and re-render
}

function groupByDurationEffortDrivenPercent() {
  // you need to manually add the sort icon(s) in UI
  const sortColumns = [
    { columnId: 'duration', sortAsc: true },
    { columnId: 'effortDriven', sortAsc: true },
    { columnId: 'percentComplete', sortAsc: true },
  ];
  vueGrid.filterService.setSortColumnIcons(sortColumns);
  vueGrid.dataView.setGrouping([
    {
      getter: 'duration',
      formatter: (g) => `Duration: ${g.value} <span style="color:green">(${g.count} items)</span>`,
      aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
      aggregateCollapsed: true,
      lazyTotalsCalculation: true,
    },
    {
      getter: 'effortDriven',
      formatter: (g) => `Effort-Driven: ${g.value ? 'True' : 'False'}  <span style="color:green">(${g.count} items)</span>`,
      aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
      lazyTotalsCalculation: true,
    },
    {
      getter: 'percentComplete',
      formatter: (g) => `% Complete: ${g.value}  <span style="color:green">(${g.count} items)</span>`,
      aggregators: [new Aggregators.Avg('percentComplete')],
      aggregateCollapsed: true,
      collapsed: true,
      lazyTotalsCalculation: true,
    },
  ] as Grouping[]);
  vueGrid.slickGrid.invalidate(); // invalidate all rows and re-render
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
  queueMicrotask(() => vueGrid.resizerService.resizeGrid());
}

function vueGridReady(grid: SlickgridVueInstance) {
  vueGrid = grid;
  groupByDuration(); // group by duration on page load
}
</script>

<template>
  <h2>
    Example 13: Grouping & Aggregators
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example13.vue"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    <ul>
      <li>
        <a href="https://ghiscoding.gitbook.io/slickgrid-vue/grid-functionalities/grouping-aggregators" target="_blank">Wiki docs</a>
      </li>
      <li>Fully dynamic and interactive multi-level grouping with filtering and aggregates over 50'000 items</li>
      <li>Each grouping level can have its own aggregates (over child rows, child groups, or all descendant rows)..</li>
      <li>Use "Aggregators" and "GroupTotalFormatters" directly from Slickgrid-Vue</li>
    </ul>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="add-5k-rows-btn" @click="loadData(5000)">5K rows</button>
      <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="add-50k-rows-btn" @click="loadData(50000)">50K rows</button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="clear-grouping-btn" @click="clearGrouping()">
        <i class="mdi mdi-close"></i> Clear Grouping
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="clear-filter-btn" @click="clearFilters()">
        <i class="mdi mdi-close"></i> Clear Filters
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="collapse-all-btn" @click="collapseAllGroups()">
        <i class="mdi mdi-arrow-collapse"></i> Collapse all groups
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="expand-all-btn" @click="expandAllGroups()">
        <i class="mdi mdi-arrow-expand"></i> Expand all groups
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="export-excel-btn" @click="exportToExcel()">
        <i class="mdi mdi-file-excel-outline text-success"></i> Export to Excel
      </button>
      <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="export-pdf-btn" @click="exportToPdf()">
        <i class="mdi mdi-file-pdf-outline text-danger"></i> Export to PDF
      </button>
    </div>
  </div>

  <hr />

  <div class="row mb-2">
    <div class="col-sm-12">
      <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="group-duration-sort-value-btn" @click="groupByDuration()">
        Group by Duration &amp; sort groups by value
      </button>
      <button
        class="btn btn-outline-secondary btn-xs btn-icon mx-1"
        data-test="group-duration-sort-count-btn"
        @click="groupByDurationOrderByCount(false)"
      >
        Group by Duration &amp; sort groups by count
      </button>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-sort-count-collapse-btn"
          @click="groupByDurationOrderByCount(true)"
        >
          Group by Duration &amp; sort groups by count, aggregate collapsed
        </button>
        <button
          class="btn btn-outline-secondary btn-xs btn-icon mx-1"
          data-test="group-duration-effort-btn"
          @click="groupByDurationEffortDriven()"
        >
          Group by Duration then Effort-Driven
        </button>
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-effort-percent-btn"
          @click="groupByDurationEffortDrivenPercent()"
        >
          Group by Duration then Effort-Driven then Percent.
        </button>
        <span :hidden="!processing">
          <i class="mdi mdi-sync mdi-spin"></i>
        </span>
      </div>
    </div>
  </div>

  <slickgrid-vue
    v-model:options="gridOptions"
    v-model:columns="columns"
    v-model:dataset="dataset"
    grid-id="grid13"
    @onBeforeExportToExcel="processing = true"
    @onAfterExportToExcel="processing = false"
    @onBeforeExportToPdf="processing = true"
    @onAfterExportToPdf="processing = false"
    @onVueGridCreated="vueGridReady($event.detail)"
  >
  </slickgrid-vue>
</template>
<style lang="scss">
.slick-column-name {
  .btn:focus {
    outline: 2px solid rgba(53, 53, 53, 0.5);
  }
}
</style>
