// frameworks/angular-slickgrid/src/demos/examples/example18.component.ts
import { Component, type OnDestroy, type OnInit } from '@angular/core';
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { TextExportService } from '@slickgrid-universal/text-export';

import {
  type AngularGridInstance,
  Aggregators,
  type Column,
  DelimiterType,
  Editors,
  Filters,
  Formatters,
  type GridOption,
  type Grouping,
  type GroupingGetterFunction,
  GroupTotalFormatters,
  SortDirectionNumber,
  SortComparers,
} from '../../library';

const NB_ITEMS = 5000;

@Component({
  templateUrl: './example18.component.html',
  standalone: false,
})
export class Example18Component implements OnInit, OnDestroy {
  private _darkMode = false;
  angularGrid!: AngularGridInstance;
  columnDefinitions!: Column[];
  dataset!: any[];
  dataviewObj: any;
  draggableGroupingPlugin: any;
  durationOrderByCount = false;
  gridObj: any;
  gridOptions!: GridOption;
  hideSubTitle = false;
  processing = false;
  selectedGroupingFields: Array<string | GroupingGetterFunction> = ['', '', ''];
  excelExportService = new ExcelExportService();
  textExportService = new TextExportService();

  constructor() {
    // define the grid options & columns and then create the grid itself
    this.loadData(NB_ITEMS);
    this.defineGrid();
  }

  ngOnInit(): void {
    // populate the dataset once the grid is ready
    this.defineGrid();
  }

  ngOnDestroy() {
    document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
  }

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    this.gridObj = angularGrid.slickGrid; // grid object
    this.dataviewObj = angularGrid.dataView;
  }

  /* Define grid Options and Columns */
  defineGrid() {
    this.columnDefinitions = [
      {
        id: 'title',
        name: 'Title',
        field: 'title',
        columnGroup: 'Common Factor',
        width: 70,
        minWidth: 50,
        cssClass: 'cell-title',
        filterable: true,
        sortable: true,
        grouping: {
          getter: 'title',
          formatter: (g) => `Title: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('cost')],
          aggregateCollapsed: false,
          collapsed: false,
        },
      },
      {
        id: 'duration',
        name: 'Duration',
        field: 'duration',
        columnGroup: 'Common Factor',
        width: 70,
        sortable: true,
        filterable: true,
        editor: {
          model: Editors.float,
          // required: true,
          decimal: 2,
          valueStep: 1,
          maxValue: 10000,
          alwaysSaveOnEnterKey: true,
        },
        filter: { model: Filters.slider, operator: '>=' },
        type: 'number',
        groupTotalsFormatter: GroupTotalFormatters.sumTotals,
        grouping: {
          getter: 'duration',
          formatter: (g) => `Duration: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
          comparer: (a, b) => {
            return this.durationOrderByCount ? a.count - b.count : SortComparers.numeric(a.value, b.value, SortDirectionNumber.asc);
          },
          aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
          aggregateCollapsed: false,
          collapsed: false,
        },
      },
      {
        id: 'start',
        name: 'Start',
        field: 'start',
        columnGroup: 'Period',
        minWidth: 60,
        sortable: true,
        filterable: true,
        filter: { model: Filters.compoundDate },
        formatter: Formatters.dateIso,
        type: 'dateUtc',
        outputType: 'dateIso',
        exportWithFormatter: true,
        grouping: {
          getter: 'start',
          formatter: (g) => `Start: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('cost')],
          aggregateCollapsed: false,
          collapsed: false,
        },
      },
      {
        id: 'finish',
        name: 'Finish',
        field: 'finish',
        columnGroup: 'Period',
        minWidth: 60,
        sortable: true,
        filterable: true,
        filter: { model: Filters.compoundDate },
        formatter: Formatters.dateIso,
        type: 'dateUtc',
        outputType: 'dateIso',
        exportWithFormatter: true,
        grouping: {
          getter: 'finish',
          formatter: (g) => `Finish: ${g.value} <span class="text-primary">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('cost')],
          aggregateCollapsed: false,
          collapsed: false,
        },
      },
      {
        id: 'cost',
        name: 'Cost',
        field: 'cost',
        columnGroup: 'Analysis',
        width: 90,
        sortable: true,
        filterable: true,
        filter: { model: Filters.compoundInput },
        formatter: Formatters.dollar,
        groupTotalsFormatter: GroupTotalFormatters.sumTotalsDollar,
        type: 'number',
        grouping: {
          getter: 'cost',
          formatter: (g) => `Cost: ${g.value} <span class="text-primary">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('cost')],
          aggregateCollapsed: true,
          collapsed: true,
        },
      },
      {
        id: 'percentComplete',
        name: '% Complete',
        field: 'percentComplete',
        columnGroup: 'Analysis',
        minWidth: 70,
        width: 90,
        formatter: Formatters.percentCompleteBar,
        type: 'number',
        filterable: true,
        filter: { model: Filters.compoundSlider },
        sortable: true,
        groupTotalsFormatter: GroupTotalFormatters.avgTotalsPercentage,
        grouping: {
          getter: 'percentComplete',
          formatter: (g) => `% Complete: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('cost')],
          aggregateCollapsed: false,
          collapsed: false,
        },
        params: { groupFormatterPrefix: '<i>Avg</i>: ' },
      },
      {
        id: 'effortDriven',
        name: 'Effort-Driven',
        field: 'effortDriven',
        columnGroup: 'Analysis',
        width: 80,
        minWidth: 20,
        maxWidth: 100,
        cssClass: 'cell-effort-driven',
        sortable: true,
        filterable: true,
        filter: {
          collection: [
            { value: '', label: '' },
            { value: true, label: 'True' },
            { value: false, label: 'False' },
          ],
          model: Filters.singleSelect,
        },
        formatter: Formatters.checkmarkMaterial,
        grouping: {
          getter: 'effortDriven',
          formatter: (g) => `Effort-Driven: ${g.value ? 'True' : 'False'} <span class="text-primary">(${g.count} items)</span>`,
          aggregators: [new Aggregators.Sum('duration'), new Aggregators.Sum('cost')],
          collapsed: false,
        },
      },
    ];

    this.gridOptions = {
      autoResize: {
        container: '#demo-container',
        rightPadding: 10,
      },
      enableDraggableGrouping: true,
      autoEdit: true, // true single click (false for double-click)
      autoCommitEdit: true,
      editable: true,
      enableCellNavigation: true,

      // pre-header will include our Header Grouping (i.e. "Common Factor")
      // Draggable Grouping could be located in either the Pre-Header OR the new Top-Header
      createPreHeaderPanel: true,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 30,

      // when Top-Header is created, it will be used by the Draggable Grouping (otherwise the Pre-Header will be used)
      createTopHeaderPanel: true,
      showTopHeaderPanel: true,
      topHeaderPanelHeight: 35,

      showCustomFooter: true,
      enableFiltering: true,
      // you could debounce/throttle the input text filter if you have lots of data
      // filterTypingDebounce: 250,
      enableSorting: true,
      textExportOptions: {
        sanitizeDataExport: true,
      },
      gridMenu: {
        onCommand: (e, args) => {
          if (args.command === 'toggle-preheader') {
            // in addition to the grid menu pre-header toggling (internally), we will also clear grouping
            this.clearGrouping();
          }
        },
      },
      draggableGrouping: {
        dropPlaceHolderText: 'Drop a column header here to group by the column',
        // groupIconCssClass: 'mdi mdi-drag-vertical',
        deleteIconCssClass: 'mdi mdi-close color-danger',
        sortAscIconCssClass: 'mdi mdi-arrow-up',
        sortDescIconCssClass: 'mdi mdi-arrow-down',
        onGroupChanged: (e, args) => this.onGroupChanged(args),
        onExtensionRegistered: (extension) => (this.draggableGroupingPlugin = extension),
        initialGroupBy: ['duration'],
      },
      darkMode: this._darkMode,
      enableTextExport: true,
      enableExcelExport: true,
      excelExportOptions: { sanitizeDataExport: true },
      externalResources: [this.excelExportService, this.textExportService],
    };

    this.loadData(500);
  }

  loadData(rowCount: number) {
    // mock a dataset
    const tmpData = [];
    for (let i = 0; i < rowCount; i++) {
      const randomYear = 2000 + Math.floor(Math.random() * 10);
      const randomMonth = Math.floor(Math.random() * 11);
      const randomDay = Math.floor(Math.random() * 29);
      const randomPercent = Math.round(Math.random() * 100);
      const randomCost = Math.round(Math.random() * 10000) / 100;

      tmpData[i] = {
        id: 'id_' + i,
        num: i,
        title: 'Task ' + i,
        duration: Math.round(Math.random() * 100) + '',
        percentComplete: randomPercent,
        percentCompleteNumber: randomPercent,
        start: new Date(randomYear, randomMonth, randomDay),
        finish: new Date(randomYear, randomMonth + 1, randomDay),
        cost: i % 33 === 0 ? -randomCost : randomCost,
        effortDriven: i % 5 === 0,
      };
    }
    this.dataset = tmpData;
  }

  clearGroupsAndSelects() {
    this.clearGroupingSelects();
    this.clearGrouping();
  }

  clearGrouping(invalidateRows = true) {
    this.draggableGroupingPlugin?.clearDroppedGroups();
    if (invalidateRows) {
      this.gridObj?.invalidate(); // invalidate all rows and re-render
    }
  }

  clearGroupingSelects() {
    this.selectedGroupingFields.forEach((g, i) => (this.selectedGroupingFields[i] = ''));
  }

  collapseAllGroups() {
    this.dataviewObj.collapseAllGroups();
  }

  expandAllGroups() {
    this.dataviewObj.expandAllGroups();
  }

  exportToExcel() {
    this.excelExportService.exportToExcel({
      filename: 'Export',
      format: 'xlsx',
    });
  }

  exportToCsv(type = 'csv') {
    this.textExportService.exportToFile({
      delimiter: type === 'csv' ? DelimiterType.comma : DelimiterType.tab,
      filename: 'myExport',
      format: type === 'csv' ? 'csv' : 'txt',
    });
  }

  groupByDurationOrderByCount(sortedByCount = false) {
    this.durationOrderByCount = sortedByCount;
    this.clearGrouping(false);

    if (this.draggableGroupingPlugin?.setDroppedGroups) {
      this.showPreHeader();
      this.draggableGroupingPlugin.setDroppedGroups('duration');

      // you need to manually add the sort icon(s) in UI
      const sortColumns = sortedByCount ? [] : [{ columnId: 'duration', sortAsc: true }];
      this.gridObj?.setSortColumns(sortColumns);
      this.gridObj?.invalidate(); // invalidate all rows and re-render
    }
  }

  groupByDurationEffortDriven() {
    this.clearGrouping(false);
    if (this.draggableGroupingPlugin?.setDroppedGroups) {
      this.showPreHeader();
      this.draggableGroupingPlugin.setDroppedGroups(['duration', 'effortDriven']);
      this.gridObj?.invalidate(); // invalidate all rows and re-render
    }
  }

  groupByFieldName(_fieldName: string, _index: number) {
    this.clearGrouping();
    if (this.draggableGroupingPlugin && this.draggableGroupingPlugin.setDroppedGroups) {
      // get the field names from Group By select(s) dropdown, but filter out any empty fields
      const groupedFields = this.selectedGroupingFields.filter((g) => g !== '');

      this.showPreHeader();
      this.draggableGroupingPlugin.setDroppedGroups(groupedFields);
      this.gridObj.invalidate(); // invalidate all rows and re-render
    }
  }

  onGroupChanged(change: { caller?: string; groupColumns: Grouping[] }) {
    // the "caller" property might not be in the SlickGrid core lib yet, reference PR https://github.com/6pac/SlickGrid/pull/303
    const caller = (change && change.caller) || [];
    const groups = (change && change.groupColumns) || [];

    if (Array.isArray(this.selectedGroupingFields) && Array.isArray(groups) && groups.length > 0) {
      // update all Group By select dropdown
      this.selectedGroupingFields.forEach((g, i) => (this.selectedGroupingFields[i] = (groups[i] && groups[i].getter) || ''));
    } else if (groups.length === 0 && caller === 'remove-group') {
      this.clearGroupingSelects();
    }
  }

  onCellChanged() {
    // when user changes a cell, we need to advise the DataView for the grouping to update its totals
    this.angularGrid.dataView?.refresh();
  }

  showPreHeader() {
    this.gridObj.setPreHeaderPanelVisibility(true);
  }

  selectTrackByFn(index: number, _item: any) {
    return index;
  }

  setFiltersDynamically() {
    // we can Set Filters Dynamically (or different filters) afterward through the FilterService
    this.angularGrid.filterService.updateFilters([
      { columnId: 'percentComplete', operator: '>=', searchTerms: ['55'] },
      { columnId: 'cost', operator: '<', searchTerms: ['80'] },
    ]);
  }

  setSortingDynamically() {
    this.angularGrid.sortService.updateSorting([
      // orders matter, whichever is first in array will be the first sorted column
      { columnId: 'percentComplete', direction: 'ASC' },
    ]);
  }

  toggleDraggableGroupingRow() {
    this.clearGrouping();
    this.gridObj.setPreHeaderPanelVisibility(!this.gridObj.getOptions().showPreHeaderPanel);
  }

  toggleDarkMode() {
    this._darkMode = !this._darkMode;
    this.toggleBodyBackground();
    this.angularGrid.slickGrid?.setOptions({ darkMode: this._darkMode });
  }

  toggleBodyBackground() {
    if (this._darkMode) {
      document.querySelector<HTMLDivElement>('.panel-wm-content')!.classList.add('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'dark';
    } else {
      document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
    }
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    this.angularGrid.resizerService.resizeGrid(0);
  }
}

<div id="demo-container" class="container-fluid">
  <h2>
    Example 18: Draggable Grouping & Aggregators
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
    <button class="btn btn-outline-secondary btn-sm" (click)="toggleDarkMode()" data-test="toggle-dark-mode">
      <span class="mdi mdi-theme-light-dark"></span>
      <span>Toggle Dark Mode</span>
    </button>
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example18.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
  </h2>

  <div class="subtitle">
    <ul>
      <li>
        <a href="https://ghiscoding.gitbook.io/angular-slickgrid/grid-functionalities/grouping-and-aggregators" target="_blank"
          >Wiki docs</a
        >
      </li>
      <li>This example shows 3 ways of grouping</li>
      <ol>
        <li>
          Drag any Column Header on the top placeholder to group by that column (support moti-columns grouping by adding more columns to the
          drop area).
        </li>
        <li>Use buttons and defined functions to group by wichever field you want</li>
        <li>Use the Select dropdown to group, the position of the Selects represent the grouping level</li>
      </ol>
      <li>Fully dynamic and interactive multi-level grouping with filtering and aggregates ovor 50'000 items</li>
      <li>Each grouping level can have its own aggregates (over child rows, child groups, or all descendant rows)..</li>
      <li>Use "Aggregators" and "GroupTotalFormatters" directly from Angular-Slickgrid</li>
    </ul>
  </div>

  <form class="form-inline">
    <div class="row">
      <div class="col-sm-12">
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="add-5k-rows-btn" (click)="loadData(5000)">5K rows</button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="add-50k-rows-btn" (click)="loadData(50000)">50K rows</button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="clear-grouping-btn" (click)="clearGroupsAndSelects()">
          <i class="mdi mdi-close"></i> Clear grouping
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="collapse-all-btn" (click)="collapseAllGroups()">
          <i class="mdi mdi-arrow-collapse"></i> Collapse all groups
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="expand-all-btn" (click)="expandAllGroups()">
          <i class="mdi mdi-arrow-expand"></i> Expand all groups
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" (click)="toggleDraggableGroupingRow()">
          Toggle Draggable Grouping Row
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" (click)="exportToExcel()">
          <i class="mdi mdi-file-excel-outline text-success"></i> Export to Excel
        </button>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-sort-value-btn"
          (click)="groupByDurationOrderByCount(false)"
        >
          Group by duration &amp; sort groups by value
        </button>
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-sort-count-btn"
          (click)="groupByDurationOrderByCount(true)"
        >
          Group by duration &amp; sort groups by count
        </button>
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-effort-btn"
          (click)="groupByDurationEffortDriven()"
        >
          Group by Duration &amp; then Effort-Driven
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="set-dynamic-filter" (click)="setFiltersDynamically()">
          <span class="mdi mdi-filter-outline"></span>
          <span> Set Filters Dynamically </span>
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="set-dynamic-sorting" (click)="setSortingDynamically()">
          <span class="mdi mdi-sort-ascending"></span>
          <span> Set Sorting Dynamically </span>
        </button>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-sm-12">
        <div class="form-row">
          <div class="row form-group">
            <label for="field1" class="col-sm-3 mb-2">Group by field(s)</label>
            <div
              class="form-group col-md-3 grouping-selects"
              *ngFor="let groupField of selectedGroupingFields; let i = index; trackBy: selectTrackByFn"
            >
              <select
                class="form-select"
                name="group-field-{{ i }}"
                [(ngModel)]="selectedGroupingFields[i]"
                (ngModelChange)="groupByFieldName($event, i)"
              >
                <option value=""></option>
                <option [ngValue]="field.id" *ngFor="let field of columnDefinitions">{{ field.name }}</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
  <div class="row mt-1 mb-1">
    <hr />
  </div>

  <angular-slickgrid
    gridId="grid18"
    [dataset]="dataset"
    [columns]="columnDefinitions"
    [options]="gridOptions"
    (onCellChange)="onCellChanged()"
    (onAngularGridCreated)="angularGridReady($event.detail)"
  >
  </angular-slickgrid>
</div>

// demos/vue/src/components/Example18.vue
<script setup lang="ts">
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { TextExportService } from '@slickgrid-universal/text-export';
import {
  type GridOption,
  type Grouping,
  type GroupingGetterFunction,
  type SlickgridVueInstance,
  Aggregators,
  type Column,
  Filters,
  Formatters,
  GroupTotalFormatters,
  SlickgridVue,
  SortComparers,
  SortDirectionNumber,
} from 'slickgrid-vue';
import { onBeforeMount, onUnmounted, ref, type Ref } from 'vue';

const NB_ITEMS = 5000;
const darkMode = ref(false);
const gridOptions = ref<GridOption>();
const columnDefinitions: Ref<Column[]> = ref([]);
const dataset = ref<any[]>([]);
let draggableGroupingPlugin: any;
let durationOrderByCount = false;
const selectedGroupingFields = ref<Array<string | GroupingGetterFunction>>(['', '', '']);
const excelExportService = new ExcelExportService();
const textExportService = new TextExportService();
const showSubTitle = ref(true);
let vueGrid!: SlickgridVueInstance;

onBeforeMount(() => {
  defineGrid();
  // mock some data (different in each dataset)
  loadData(NB_ITEMS);
});

onUnmounted(() => {
  document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
  document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
});

/* Define grid Options and Columns */
function defineGrid() {
  columnDefinitions.value = [
    {
      id: 'title',
      name: 'Title',
      field: 'title',
      columnGroup: 'Common Factor',
      width: 70,
      minWidth: 50,
      cssClass: 'cell-title',
      filterable: true,
      sortable: true,
      grouping: {
        getter: 'title',
        formatter: (g) => `Title: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('cost')],
        aggregateCollapsed: false,
        collapsed: false,
      },
    },
    {
      id: 'duration',
      name: 'Duration',
      field: 'duration',
      columnGroup: 'Common Factor',
      width: 70,
      sortable: true,
      filterable: true,
      filter: { model: Filters.slider, operator: '>=' },
      type: 'number',
      groupTotalsFormatter: GroupTotalFormatters.sumTotals,
      grouping: {
        getter: 'duration',
        formatter: (g) => `Duration: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
        comparer: (a, b) => {
          return durationOrderByCount ? a.count - b.count : SortComparers.numeric(a.value, b.value, SortDirectionNumber.asc);
        },
        aggregators: [new Aggregators.Sum('cost')],
        aggregateCollapsed: false,
        collapsed: false,
      },
    },
    {
      id: 'start',
      name: 'Start',
      field: 'start',
      columnGroup: 'Period',
      minWidth: 60,
      sortable: true,
      filterable: true,
      filter: { model: Filters.compoundDate },
      formatter: Formatters.dateIso,
      type: 'dateUtc',
      outputType: 'dateIso',
      exportWithFormatter: true,
      grouping: {
        getter: 'start',
        formatter: (g) => `Start: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('cost')],
        aggregateCollapsed: false,
        collapsed: false,
      },
    },
    {
      id: 'finish',
      name: 'Finish',
      field: 'finish',
      columnGroup: 'Period',
      minWidth: 60,
      sortable: true,
      filterable: true,
      filter: { model: Filters.compoundDate },
      formatter: Formatters.dateIso,
      type: 'dateUtc',
      outputType: 'dateIso',
      exportWithFormatter: true,
      grouping: {
        getter: 'finish',
        formatter: (g) => `Finish: ${g.value} <span class="text-primary">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('cost')],
        aggregateCollapsed: false,
        collapsed: false,
      },
    },
    {
      id: 'cost',
      name: 'Cost',
      field: 'cost',
      columnGroup: 'Analysis',
      width: 90,
      sortable: true,
      filterable: true,
      filter: { model: Filters.compoundInput },
      formatter: Formatters.dollar,
      exportWithFormatter: true,
      groupTotalsFormatter: GroupTotalFormatters.sumTotalsDollar,
      type: 'number',
      grouping: {
        getter: 'cost',
        formatter: (g) => `Cost: ${g.value} <span class="text-primary">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('cost')],
        aggregateCollapsed: true,
        collapsed: true,
      },
    },
    {
      id: 'percentComplete',
      name: '% Complete',
      field: 'percentComplete',
      columnGroup: 'Analysis',
      minWidth: 70,
      width: 90,
      formatter: Formatters.percentCompleteBar,
      type: 'number',
      filterable: true,
      filter: { model: Filters.compoundSlider },
      sortable: true,
      groupTotalsFormatter: GroupTotalFormatters.avgTotalsPercentage,
      grouping: {
        getter: 'percentComplete',
        formatter: (g) => `% Complete: ${g.value}  <span class="text-primary">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('cost')],
        aggregateCollapsed: false,
        collapsed: false,
      },
      params: { groupFormatterPrefix: '<i>Avg</i>: ' },
    },
    {
      id: 'effortDriven',
      name: 'Effort-Driven',
      field: 'effortDriven',
      columnGroup: 'Analysis',
      width: 80,
      minWidth: 20,
      maxWidth: 100,
      cssClass: 'cell-effort-driven',
      sortable: true,
      filterable: true,
      filter: {
        collection: [
          { value: '', label: '' },
          { value: true, label: 'True' },
          { value: false, label: 'False' },
        ],
        model: Filters.singleSelect,
      },
      formatter: Formatters.checkmarkMaterial,
      grouping: {
        getter: 'effortDriven',
        formatter: (g) => `Effort-Driven: ${g.value ? 'True' : 'False'} <span class="text-primary">(${g.count} items)</span>`,
        aggregators: [new Aggregators.Sum('cost')],
        collapsed: false,
      },
    },
  ];

  gridOptions.value = {
    autoResize: {
      container: '#demo-container',
      rightPadding: 10,
    },
    enableDraggableGrouping: true,

    // pre-header will include our Header Grouping (i.e. "Common Factor")
    // Draggable Grouping could be located in either the Pre-Header OR the new Top-Header
    createPreHeaderPanel: true,
    showPreHeaderPanel: true,
    preHeaderPanelHeight: 30,

    // when Top-Header is created, it will be used by the Draggable Grouping (otherwise the Pre-Header will be used)
    createTopHeaderPanel: true,
    showTopHeaderPanel: true,
    topHeaderPanelHeight: 35,

    showCustomFooter: true,
    enableFiltering: true,
    // you could debounce/throttle the input text filter if you have lots of data
    // filterTypingDebounce: 250,
    enableSorting: true,
    enableColumnReorder: true,
    gridMenu: {
      onCommand: (_e, args) => {
        if (args.command === 'toggle-preheader') {
          // in addition to the grid menu pre-header toggling (internally), we will also clear grouping
          clearGrouping();
        }
      },
    },
    draggableGrouping: {
      dropPlaceHolderText: 'Drop a column header here to group by the column',
      // groupIconCssClass: 'mdi mdi-drag-vertical',
      deleteIconCssClass: 'mdi mdi-close color-danger',
      sortAscIconCssClass: 'mdi mdi-arrow-up',
      sortDescIconCssClass: 'mdi mdi-arrow-down',
      onGroupChanged: (_e, args) => onGroupChanged(args),
      onExtensionRegistered: (extension) => (draggableGroupingPlugin = extension),
      initialGroupBy: ['duration'],
    },
    darkMode: darkMode.value,
    enableTextExport: true,
    enableExcelExport: true,
    excelExportOptions: { sanitizeDataExport: true },
    textExportOptions: { sanitizeDataExport: true },
    externalResources: [excelExportService, textExportService],
  };
}

function loadData(rowCount: number) {
  // mock a dataset
  const tmpData: any[] = [];
  for (let i = 0; i < rowCount; i++) {
    const randomYear = 2000 + Math.floor(Math.random() * 10);
    const randomMonth = Math.floor(Math.random() * 11);
    const randomDay = Math.floor(Math.random() * 29);
    const randomPercent = Math.round(Math.random() * 100);
    const randomCost = Math.round(Math.random() * 10000) / 100;

    tmpData[i] = {
      id: 'id_' + i,
      num: i,
      title: 'Task ' + i,
      duration: Math.round(Math.random() * 100) + '',
      percentComplete: randomPercent,
      percentCompleteNumber: randomPercent,
      start: new Date(randomYear, randomMonth, randomDay),
      finish: new Date(randomYear, randomMonth + 1, randomDay),
      cost: i % 33 === 0 ? -randomCost : randomCost,
      effortDriven: i % 5 === 0,
    };
  }
  dataset.value = tmpData;
}

function clearGroupsAndSelects() {
  clearGroupingSelects();
  clearGrouping();
}

function clearGroupingSelects() {
  selectedGroupingFields.value.forEach((_g, i) => (selectedGroupingFields.value[i] = ''));
  selectedGroupingFields.value = [...selectedGroupingFields.value]; // force dirty checking
}

function clearGrouping(invalidateRows = true) {
  draggableGroupingPlugin?.clearDroppedGroups();
  if (invalidateRows) {
    vueGrid.slickGrid?.invalidate(); // invalidate all rows and re-render
  }
}

function collapseAllGroups() {
  vueGrid.dataView.collapseAllGroups();
}

function expandAllGroups() {
  vueGrid.dataView.expandAllGroups();
}

function exportToExcel() {
  excelExportService.exportToExcel({
    filename: 'Export',
    format: 'xlsx',
  });
}

function groupByDurationOrderByCount(sortedByCount = false) {
  durationOrderByCount = sortedByCount;
  clearGrouping(false);

  if (draggableGroupingPlugin?.setDroppedGroups) {
    showPreHeader();
    draggableGroupingPlugin.setDroppedGroups('duration');

    // you need to manually add the sort icon(s) in UI
    const sortColumns = sortedByCount ? [] : [{ columnId: 'duration', sortAsc: true }];
    vueGrid.slickGrid?.setSortColumns(sortColumns);
    vueGrid.slickGrid?.invalidate(); // invalidate all rows and re-render
  }
}

function groupByDurationEffortDriven() {
  clearGrouping(false);
  if (draggableGroupingPlugin?.setDroppedGroups) {
    showPreHeader();
    draggableGroupingPlugin.setDroppedGroups(['duration', 'effortDriven']);
    vueGrid.slickGrid?.invalidate(); // invalidate all rows and re-render
  }
}

function groupByFieldName() {
  clearGrouping();
  if (draggableGroupingPlugin?.setDroppedGroups) {
    showPreHeader();

    // get the field names from Group By select(s) dropdown, but filter out any empty fields
    const groupedFields = selectedGroupingFields.value.filter((g) => g !== '');
    if (groupedFields.length === 0) {
      clearGrouping();
    } else {
      draggableGroupingPlugin.setDroppedGroups(groupedFields);
    }
    vueGrid.slickGrid.invalidate(); // invalidate all rows and re-render
  }
}

function onGroupChanged(change: { caller?: string; groupColumns: Grouping[] }) {
  const caller = change?.caller ?? [];
  const groups = change?.groupColumns ?? [];

  if (Array.isArray(selectedGroupingFields.value) && Array.isArray(groups) && groups.length > 0) {
    // update all Group By select dropdown
    selectedGroupingFields.value.forEach((_g, i) => (selectedGroupingFields.value[i] = groups[i]?.getter ?? ''));
    selectedGroupingFields.value = [...selectedGroupingFields.value]; // force dirty checking
  } else if (groups.length === 0 && caller === 'remove-group') {
    clearGroupingSelects();
  }
}

function showPreHeader() {
  vueGrid.slickGrid.setPreHeaderPanelVisibility(true);
}

function setFiltersDynamically() {
  // we can Set Filters Dynamically (or different filters) afterward through the FilterService
  vueGrid.filterService.updateFilters([
    { columnId: 'percentComplete', operator: '>=', searchTerms: ['55'] },
    { columnId: 'cost', operator: '<', searchTerms: ['80'] },
  ]);
}

function setSortingDynamically() {
  vueGrid.sortService.updateSorting([
    // orders matter, whichever is first in array will be the first sorted column
    { columnId: 'percentComplete', direction: 'ASC' },
  ]);
}

function toggleDraggableGroupingRow() {
  clearGroupsAndSelects();
  vueGrid.slickGrid.setTopHeaderPanelVisibility(!vueGrid.slickGrid.getOptions().showTopHeaderPanel);
}

function toggleDarkMode() {
  darkMode.value = !darkMode.value;
  toggleBodyBackground();
  vueGrid.slickGrid?.setOptions({ darkMode: darkMode.value });
}

function toggleBodyBackground() {
  if (darkMode.value) {
    document.querySelector<HTMLDivElement>('.panel-wm-content')!.classList.add('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'dark';
  } else {
    document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
  }
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
  queueMicrotask(() => vueGrid.resizerService.resizeGrid());
}

function vueGridReady(grid: SlickgridVueInstance) {
  vueGrid = grid;
}
</script>

<template>
  <h2>
    Example 18: Draggable Grouping & Aggregators
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example18.vue"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon ms-1" data-test="toggle-dark-mode" @click="toggleDarkMode()">
      <span class="mdi mdi-theme-light-dark"></span>
      <span>Toggle Dark Mode</span>
    </button>
  </h2>

  <div class="subtitle">
    <ul>
      <li>
        <a href="https://ghiscoding.gitbook.io/slickgrid-vue/grid-functionalities/grouping-aggregators" target="_blank">Wiki docs</a>
      </li>
      <li>This example shows 3 ways of grouping</li>
      <ol>
        <li>
          Drag any Column Header on the top placeholder to group by that column (support moti-columns grouping by adding more columns to the
          drop area).
        </li>
        <li>Use buttons and defined functions to group by whichever field you want</li>
        <li>Use the Select dropdown to group, the position of the Selects represent the grouping level</li>
      </ol>
      <li>Fully dynamic and interactive multi-level grouping with filtering and aggregates ovor 50'000 items</li>
      <li>Each grouping level can have its own aggregates (over child rows, child groups, or all descendant rows)..</li>
      <li>Use "Aggregators" and "GroupTotalFormatters" directly from Slickgrid-Vue</li>
    </ul>
  </div>

  <div class="form-inline">
    <div class="row">
      <div class="col-sm-12">
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="add-5k-rows-btn" @click="loadData(5000)">5K rows</button>
        <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="add-50k-rows-btn" @click="loadData(50000)">
          50K rows
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="clear-grouping-btn" @click="clearGroupsAndSelects()">
          <i class="mdi mdi-close"></i> Clear grouping
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="collapse-all-btn" @click="collapseAllGroups()">
          <i class="mdi mdi-arrow-collapse"></i> Collapse all groups
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="expand-all-btn" @click="expandAllGroups()">
          <i class="mdi mdi-arrow-expand"></i> Expand all groups
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" @click="toggleDraggableGroupingRow()">
          Toggle Draggable Grouping Row
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" @click="exportToExcel()">
          <i class="mdi mdi-file-excel-outline text-success"></i> Export to Excel
        </button>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-sort-value-btn"
          @click="groupByDurationOrderByCount(false)"
        >
          Group by duration &amp; sort groups by value
        </button>
        <button
          class="btn btn-outline-secondary btn-xs btn-icon mx-1"
          data-test="group-duration-sort-count-btn"
          @click="groupByDurationOrderByCount(true)"
        >
          Group by duration &amp; sort groups by count
        </button>
        <button
          class="btn btn-outline-secondary btn-xs btn-icon"
          data-test="group-duration-effort-btn"
          @click="groupByDurationEffortDriven()"
        >
          Group by Duration then Effort-Driven
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon mx-1" data-test="set-dynamic-filter" @click="setFiltersDynamically()">
          <span class="mdi mdi-filter-outline"></span>
          <span> Set Filters Dynamically </span>
        </button>
        <button class="btn btn-outline-secondary btn-xs btn-icon" data-test="set-dynamic-sorting" @click="setSortingDynamically()">
          <span class="mdi mdi-sort-ascending"></span>
          <span> Set Sorting Dynamically </span>
        </button>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-sm-12">
        <div class="form-row">
          <div class="row form-group">
            <label for="field1" class="col-sm-3 mb-2">Group by field(s)</label>
            <div v-for="(groupField, index) in selectedGroupingFields" :key="index" class="form-group col-md-3 grouping-selects">
              <select class="form-select" :value="groupField" @change="groupByFieldName()">
                <option :value="''">...</option>
                <option v-for="(column, colIdx) in columnDefinitions" :key="colIdx" :value="column.id">{{ column.name }}</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-1 mb-1">
    <hr />
  </div>

  <slickgrid-vue
    v-model:options="gridOptions"
    v-model:columns="columnDefinitions"
    v-model:data="dataset"
    grid-id="grid18"
    @onVueGridCreated="vueGridReady($event.detail)"
  >
  </slickgrid-vue>
</template>
