// frameworks/angular-slickgrid/src/demos/examples/example37.component.ts
import { Component, type OnDestroy, type OnInit } from '@angular/core';
import { type AngularGridInstance, type Column, Editors, type GridOption, type OnCellChangeEventArgs } from '../../library';

const NB_ITEMS = 100;

@Component({
  templateUrl: './example37.component.html',
  standalone: false,
})
export class Example37Component implements OnDestroy, OnInit {
  private _darkMode = false;
  angularGrid!: AngularGridInstance;
  columnDefinitions: Column[] = [];
  gridOptions!: GridOption;
  dataset!: any[];
  hideSubTitle = false;

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    this.updateAllTotals();
  }

  ngOnInit(): void {
    this.defineGrid();

    // mock a dataset
    this.dataset = this.loadData(NB_ITEMS);
  }

  ngOnDestroy() {
    document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
  }

  /* Define grid Options and Columns */
  defineGrid() {
    const columnDefs: Column[] = [];
    for (let i = 0; i < 10; i++) {
      columnDefs.push({
        id: i,
        name: String.fromCharCode('A'.charCodeAt(0) + i),
        field: String(i),
        type: 'number',
        width: 58,
        editor: { model: Editors.integer },
      });
    }
    this.columnDefinitions = columnDefs;

    this.gridOptions = {
      autoEdit: true,
      autoCommitEdit: true,
      editable: true,
      darkMode: this._darkMode,
      gridHeight: 450,
      gridWidth: 800,
      enableCellNavigation: true,
      rowHeight: 30,
      createFooterRow: true,
      showFooterRow: true,
      footerRowHeight: 28,
    };
  }

  loadData(itemCount: number) {
    // mock a dataset
    const datasetTmp: any[] = [];
    for (let i = 0; i < itemCount; i++) {
      const d = (datasetTmp[i] = {} as any);
      d.id = i;
      for (let j = 0; j < this.columnDefinitions.length; j++) {
        d[j] = Math.round(Math.random() * 10);
      }
    }

    return datasetTmp;
  }

  handleOnCellChange(_e: Event, args: OnCellChangeEventArgs) {
    this.updateTotal(args.cell);
  }

  handleOnColumnsReordered() {
    this.updateAllTotals();
  }

  toggleDarkMode() {
    this._darkMode = !this._darkMode;
    this.toggleBodyBackground();
    this.angularGrid.slickGrid?.setOptions({ darkMode: this._darkMode });
    this.updateAllTotals();
  }

  toggleBodyBackground() {
    if (this._darkMode) {
      document.querySelector<HTMLDivElement>('.panel-wm-content')!.classList.add('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'dark';
    } else {
      document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
      document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
    }
  }

  updateAllTotals() {
    let columnIdx = this.angularGrid.slickGrid?.getColumns().length || 0;
    while (columnIdx--) {
      this.updateTotal(columnIdx);
    }
  }

  updateTotal(cell: number) {
    const columnId = this.angularGrid.slickGrid?.getColumns()[cell].id as number;

    let total = 0;
    let i = this.dataset.length;
    while (i--) {
      total += parseInt(this.dataset[i][columnId], 10) || 0;
    }
    const columnElement = this.angularGrid.slickGrid?.getFooterRowColumn(columnId);
    if (columnElement) {
      columnElement.textContent = `Sum: ${total}`;
    }
  }

  toggleSubTitle() {
    this.hideSubTitle = !this.hideSubTitle;
    const action = this.hideSubTitle ? 'add' : 'remove';
    document.querySelector('.subtitle')?.classList[action]('hidden');
    this.angularGrid.resizerService.resizeGrid(0);
  }
}

<div id="demo-container" class="container-fluid">
  <h2>
    Example 37: Footer Totals Row
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="toggleDarkMode()" data-test="toggle-dark-mode">
      <span class="mdi mdi-theme-light-dark"></span>
      <span>Toggle Dark Mode</span>
    </button>
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example37.component.ts"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
  </h2>

  <div class="subtitle">Display a totals row at the end of the grid.</div>

  <angular-slickgrid
    gridId="grid37"
    [columns]="columnDefinitions"
    [options]="gridOptions"
    [dataset]="dataset"
    (onAngularGridCreated)="angularGridReady($event.detail)"
    (onCellChange)="handleOnCellChange($event.detail.eventData, $event.detail.args)"
    (onColumnsReordered)="handleOnColumnsReordered()"
  >
  </angular-slickgrid>
</div>

// demos/vue/src/components/Example37.vue
<script setup lang="ts">
import {
  type GridOption,
  type OnCellChangeEventArgs,
  type SlickgridVueInstance,
  type Column,
  Editors,
  FieldType,
  SlickgridVue,
} from 'slickgrid-vue';
import { onBeforeMount, onMounted, onUnmounted, ref } from 'vue';

const NB_ITEMS = 100;
const gridOptions = ref<GridOption>();
const columnDefinitions = ref<Column[]>([]);
const dataset = ref<any[]>([]);
const isDarkMode = ref(false);
const showSubTitle = ref(true);
let vueGrid!: SlickgridVueInstance;

onBeforeMount(() => {
  defineGrid();
});

onMounted(() => {
  // populate the dataset once the grid is ready
  dataset.value = loadData(NB_ITEMS);
  updateAllTotals();
});

onUnmounted(() => {
  document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
  document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
});

/* Define grid Options and Columns */
function defineGrid() {
  const columnDefs: Column[] = [];
  for (let i = 0; i < 10; i++) {
    columnDefs.push({
      id: i,
      name: String.fromCharCode('A'.charCodeAt(0) + i),
      field: String(i),
      type: FieldType.number,
      width: 58,
      editor: { model: Editors.integer },
    });
  }
  columnDefinitions.value = columnDefs;

  gridOptions.value = {
    autoEdit: true,
    autoCommitEdit: true,
    editable: true,
    darkMode: isDarkMode.value,
    gridHeight: 450,
    gridWidth: 800,
    enableCellNavigation: true,
    rowHeight: 30,
    createFooterRow: true,
    showFooterRow: true,
    footerRowHeight: 28,
  };
}

function loadData(itemCount: number) {
  // mock a dataset
  const datasetTmp: any[] = [];
  for (let i = 0; i < itemCount; i++) {
    const d = (datasetTmp[i] = {} as any);
    d.id = i;
    for (let j = 0; j < columnDefinitions.value.length; j++) {
      d[j] = Math.round(Math.random() * 10);
    }
  }

  return datasetTmp;
}

function handleOnCellChange(_e: Event, args: OnCellChangeEventArgs) {
  updateTotal(args.cell);
}

function handleOnColumnsReordered() {
  updateAllTotals();
}

function updateAllTotals() {
  let columnIdx = vueGrid.slickGrid?.getColumns().length || 0;
  while (columnIdx--) {
    updateTotal(columnIdx);
  }
}

function updateTotal(cell: number) {
  const columnId = vueGrid.slickGrid?.getColumns()[cell].id as number;

  let total = 0;
  let i = dataset.value.length;
  while (i--) {
    total += parseInt(dataset.value[i][columnId], 10) || 0;
  }
  const columnElement = vueGrid.slickGrid?.getFooterRowColumn(columnId);
  if (columnElement) {
    columnElement.textContent = `Sum: ${total}`;
  }
}

function toggleDarkMode() {
  isDarkMode.value = !isDarkMode.value;
  toggleBodyBackground();
  vueGrid.slickGrid?.setOptions({ darkMode: isDarkMode.value });
  updateAllTotals();
}

function toggleBodyBackground() {
  if (isDarkMode.value) {
    document.querySelector<HTMLDivElement>('.panel-wm-content')!.classList.add('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'dark';
  } else {
    document.querySelector('.panel-wm-content')!.classList.remove('dark-mode');
    document.querySelector<HTMLDivElement>('#demo-container')!.dataset.bsTheme = 'light';
  }
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
  queueMicrotask(() => vueGrid.resizerService.resizeGrid());
}

function vueGridReady(grid: SlickgridVueInstance) {
  vueGrid = grid;
}
</script>

<template>
  <h2>
    Example 37: Footer Totals Row
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example37.vue"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon ms-1" data-test="toggle-dark-mode" @click="toggleDarkMode()">
      <span class="mdi mdi-theme-light-dark"></span>
      <span>Toggle Dark Mode</span>
    </button>
  </h2>

  <div class="subtitle">Display a totals row at the end of the grid.</div>

  <slickgrid-vue
    v-model:options="gridOptions"
    v-model:columns="columnDefinitions as Column[]"
    v-model:data="dataset"
    grid-id="grid37"
    @onCellChange="handleOnCellChange($event.detail.eventData, $event.detail.args)"
    @onColumnsReordered="handleOnColumnsReordered()"
    @onVueGridCreated="vueGridReady($event.detail)"
  >
  </slickgrid-vue>
</template>
