// demos/react/src/examples/slickgrid/Example14.tsx
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { PdfExportService } from '@slickgrid-universal/pdf-export';
import React, { useEffect, useRef, useState } from 'react';
import { SlickgridReact, type Column, type GridOption, type ItemMetadata, type SlickgridReactInstance } from 'slickgrid-react';

const Example14: React.FC = () => {
  const [gridOptions1, setGridOptions1] = useState<GridOption | undefined>(undefined);
  const [gridOptions2, setGridOptions2] = useState<GridOption | undefined>(undefined);
  const [isColspanSpreading, setIsColspanSpreading] = useState<boolean>(false);
  const [columns1, setColumns1] = useState<Column[]>([]);
  const [columns2, setColumns2] = useState<Column[]>([]);
  const [dataset1, setDataset1] = useState<any[]>([]);
  const [dataset2, setDataset2] = useState<any[]>([]);
  const reactGridRef1 = useRef<SlickgridReactInstance | null>(null);
  const reactGridRef2 = useRef<SlickgridReactInstance | null>(null);
  const [hideSubTitle, setHideSubTitle] = useState(false);

  useEffect(() => {
    defineGrid1();
    defineGrid2();
    setDataset1(getData(500));
    setDataset2(getData(500));
  }, []);

  function reactGrid1Ready(reactGrid: SlickgridReactInstance) {
    reactGridRef1.current = reactGrid;
  }

  function reactGrid2Ready(reactGrid: SlickgridReactInstance) {
    reactGridRef2.current = reactGrid;
  }

  function defineGrid1() {
    const columns1: Column[] = [
      { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
      { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
      { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
      { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
      { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
      { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
    ];

    const gridOptions1: GridOption = {
      enableAutoResize: false,
      enableCellNavigation: true,
      enableColumnReorder: false,
      enableSorting: true,
      createPreHeaderPanel: true,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 28,
      rowHeight: 33,
      gridHeight: 275,
      gridWidth: 800,
      enableExcelExport: true,
      excelExportOptions: {
        exportWithFormatter: false,
      },
      enablePdfExport: true,
      externalResources: [new ExcelExportService(), new PdfExportService()],
      explicitInitialization: true,
      dataView: {
        globalItemMetadataProvider: {
          getRowMetadata: (item: any, row: number) => renderDifferentColspan(item, row),
        },
      },
      headerMenu: {
        hidePinColumnCommand: false,
        hidePinningColumnsCommand: false,
      },
      gridMenu: {
        iconButtonContainer: 'preheader', // we can display the grid menu icon in either the preheader or in the column header (default)
      },
    };

    setColumns1(columns1);
    setGridOptions1(gridOptions1);
  }

  function defineGrid2() {
    const columns2: Column[] = [
      {
        id: 'sel',
        name: '#',
        field: 'num',
        behavior: 'select',
        cssClass: 'cell-selection',
        width: 40,
        resizable: false,
        selectable: false,
      },
      { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
      { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
      { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
      { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
      { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
      { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
    ];

    const gridOptions2 = {
      enableCellNavigation: true,
      enableColumnReorder: false,
      createPreHeaderPanel: true,
      showPreHeaderPanel: true,
      preHeaderPanelHeight: 25,
      explicitInitialization: true,
      gridHeight: 275,
      gridWidth: 800,
      rowHeight: 33,
      pinning: { columns: { left: 2 } },
      enableExcelExport: true,
      excelExportOptions: {
        exportWithFormatter: false,
      },
      externalResources: [new ExcelExportService(), new PdfExportService()],
      gridMenu: { hideClearPinningCommand: false },
      headerMenu: { hidePinColumnCommand: false, hidePinningColumnsCommand: false },
    };

    setColumns2(columns2);
    setGridOptions2(gridOptions2);
  }

  function getData(count: number) {
    // Set up some test columns.
    const mockDataset: any[] = [];
    for (let i = 0; i < count; i++) {
      mockDataset[i] = {
        id: i,
        num: i,
        title: 'Task ' + i,
        duration: '5 days with some long text to test column span',
        percentComplete: Math.round(Math.random() * 100),
        start: '01/01/2009',
        finish: '01/05/2009',
        effortDriven: i % 5 === 0,
      };
    }
    return mockDataset;
  }

  function setPinnedColumns2(pinnedCols: number) {
    reactGridRef2.current?.slickGrid.setOptions({ pinning: { columns: { left: pinnedCols } } });
    const updatedGridOptions = reactGridRef2.current?.slickGrid.getOptions();
    setGridOptions2(updatedGridOptions);
  }

  /**
   * A callback to render different row column span
   * Your callback will always have the "item" argument which you can use to decide on the colspan
   * Your return must always be in the form of:: return { columns: {}}
   */
  function renderDifferentColspan(item: any, row: number): ItemMetadata {
    if (item.id % 2 === 1 || row % 2 === 1) {
      return {
        columns: {
          duration: {
            colspan: 3, // "duration" will span over 3 columns
          },
        },
      };
    }
    return {
      columns: {
        0: {
          colspan: '*', // starting at column index 0, we will span accross all column (*)
        },
      },
    };
  }

  function spreadColspan() {
    const isSpreading = !isColspanSpreading;
    setIsColspanSpreading(isSpreading);
    reactGridRef1.current?.slickGrid?.setOptions({ spreadHiddenColspan: isSpreading });
    reactGridRef1.current?.slickGrid?.resetActiveCell();
    reactGridRef1.current?.slickGrid?.invalidate();
  }

  return !gridOptions1 ? (
    ''
  ) : (
    <div id="demo-container" className="container-fluid">
      <h2>
        Example 14: Column Span & Header Grouping
        <span className="float-end font18">
          see&nbsp;
          <a
            target="_blank"
            href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/react/src/examples/slickgrid/Example14.tsx"
          >
            <span className="mdi mdi-link-variant"></span> code
          </a>
        </span>
        <button
          className="ms-2 btn btn-outline-secondary btn-sm btn-icon"
          type="button"
          data-test="toggle-subtitle"
          onClick={() => setHideSubTitle(!hideSubTitle)}
        >
          <span className="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
        </button>
      </h2>
      {hideSubTitle ? null : (
        <div className="subtitle">
          This example demonstrates how to easily span a row over multiple columns & how to group header titles.
          <ul>
            <li>
              Note that you can add Sort but remember that it will sort by the data which the row contains, even if the data is visually
              hidden by colspan it will still sort it
            </li>
          </ul>
        </div>
      )}

      <h3>
        Grid 1 <small>(with Header Grouping &amp; Colspan)</small>
        <button
          className="btn btn-outline-secondary btn-sm btn-icon ms-2"
          onClick={() => spreadColspan()}
          data-test="spread-colspan-button"
          title="Should we always spread the same visible column count with or without hidden columns?"
        >
          <span>Toggle Spreading of ColSpan with/without Hidden Columns</span>
        </button>
      </h3>

      <SlickgridReact
        gridId="grid1"
        columns={columns1}
        options={gridOptions1}
        dataset={dataset1}
        onReactGridCreated={($event) => reactGrid1Ready($event.detail)}
      />

      <hr />

      <h3>
        Grid 2 <small>(with Header Grouping &amp; Pinned Columns)</small>
      </h3>

      <div className="col-sm 12">
        <button
          className="btn btn-outline-secondary btn-sm btn-icon"
          onClick={() => setPinnedColumns2(-1)}
          data-test="remove-pinned-column-button"
        >
          <i className="mdi mdi-close"></i> Remove Pinned Columns
        </button>
        <button
          className="btn btn-outline-secondary btn-sm btn-icon mx-1"
          onClick={() => setPinnedColumns2(2)}
          data-test="set-3pinned-columns"
        >
          <i className="mdi mdi-pin-outline"></i> Set 3 Pinned Columns
        </button>
      </div>

      <SlickgridReact
        gridId="grid2"
        columns={columns2}
        options={gridOptions2}
        dataset={dataset2}
        onReactGridCreated={($event) => reactGrid2Ready($event.detail)}
      />
    </div>
  );
};

export default Example14;

// demos/vue/src/components/Example14.vue
<script setup lang="ts">
import { ExcelExportService } from '@slickgrid-universal/excel-export';
import { PdfExportService } from '@slickgrid-universal/pdf-export';
import { SlickgridVue, type Column, type GridOption, type ItemMetadata, type SlickgridVueInstance } from 'slickgrid-vue';
import { onBeforeMount, ref, type Ref } from 'vue';

const NB_ITEMS = 500;
const gridOptions1 = ref<GridOption>();
const gridOptions2 = ref<GridOption>();
const columns1: Ref<Column[]> = ref([]);
const columns2: Ref<Column[]> = ref([]);
const dataset1 = ref<any[]>([]);
const dataset2 = ref<any[]>([]);
const showSubTitle = ref(true);
let isColspanSpreading = ref(false);
let vueGrid1!: SlickgridVueInstance;
let vueGrid2!: SlickgridVueInstance;

onBeforeMount(() => {
  definedGrid1();
  definedGrid2();

  // populate the dataset once the grid is ready
  dataset1.value = getData(NB_ITEMS);
  dataset2.value = getData(NB_ITEMS);
});

function definedGrid1() {
  columns1.value = [
    { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
    { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
    { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
    { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
    { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
    { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
  ];

  gridOptions1.value = {
    enableAutoResize: false,
    enableCellNavigation: true,
    enableColumnReorder: false,
    enableSorting: true,
    createPreHeaderPanel: true,
    showPreHeaderPanel: true,
    preHeaderPanelHeight: 28,
    gridHeight: 275,
    gridWidth: 800,
    rowHeight: 33,
    enablePdfExport: true,
    enableExcelExport: true,
    excelExportOptions: {
      exportWithFormatter: false,
    },
    externalResources: [new ExcelExportService(), new PdfExportService()],
    explicitInitialization: true,
    dataView: {
      globalItemMetadataProvider: {
        getRowMetadata: (item: any, row: number) => renderDifferentColspan(item, row),
      },
    },
    gridMenu: {
      iconButtonContainer: 'preheader', // we can display the grid menu icon in either the preheader or in the column header (default)
    },
    spreadHiddenColspan: isColspanSpreading.value,
  };
}

function definedGrid2() {
  columns2.value = [
    {
      id: 'sel',
      name: '#',
      field: 'num',
      behavior: 'select',
      cssClass: 'cell-selection',
      width: 40,
      resizable: false,
      selectable: false,
    },
    { id: 'title', name: 'Title', field: 'title', sortable: true, columnGroup: 'Common Factor' },
    { id: 'duration', name: 'Duration', field: 'duration', columnGroup: 'Common Factor' },
    { id: 'start', name: 'Start', field: 'start', columnGroup: 'Period' },
    { id: 'finish', name: 'Finish', field: 'finish', columnGroup: 'Period' },
    { id: '%', name: '% Complete', field: 'percentComplete', selectable: false, columnGroup: 'Analysis' },
    { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', type: 'boolean', columnGroup: 'Analysis' },
  ];

  gridOptions2.value = {
    enableCellNavigation: true,
    enableColumnReorder: false,
    createPreHeaderPanel: true,
    showPreHeaderPanel: true,
    preHeaderPanelHeight: 25,
    explicitInitialization: true,
    gridHeight: 275,
    gridWidth: 800,
    rowHeight: 33,
    pinning: { columns: { left: 2 } },
    enablePdfExport: true,
    enableExcelExport: true,
    excelExportOptions: {
      exportWithFormatter: false,
    },
    externalResources: [new ExcelExportService(), new PdfExportService()],
    gridMenu: { hideClearPinningCommand: false },
    headerMenu: { hidePinColumnCommand: false, hidePinningColumnsCommand: false },
  };
}

function getData(count: number) {
  // Set up some test columns.
  const mockDataset: any[] = [];
  for (let i = 0; i < count; i++) {
    mockDataset[i] = {
      id: i,
      num: i,
      title: 'Task ' + i,
      duration: '5 days',
      percentComplete: Math.round(Math.random() * 100),
      start: '01/01/2009',
      finish: '01/05/2009',
      effortDriven: i % 5 === 0,
    };
  }
  return mockDataset;
}

function setPinnedColumns2(pinnedCols: number) {
  vueGrid2.slickGrid.setOptions({
    pinning: {
      columns: {
        left: pinnedCols >= 0 ? pinnedCols : [],
      },
    },
  });
  gridOptions2.value = vueGrid2.slickGrid.getOptions();
}

/**
 * A callback to render different row column span
 * Your callback will always have the "item" argument which you can use to decide on the colspan
 * Your return must always be in the form of:: return { columns: {}}
 */
function renderDifferentColspan(item: any, row: number): ItemMetadata {
  if (item.id % 2 === 1 || row % 2 === 1) {
    return {
      columns: {
        duration: {
          colspan: 3, // "duration" will span over 3 columns
        },
      },
    };
  }
  return {
    columns: {
      0: {
        colspan: '*', // starting at column index 0, we will span accross all column (*)
      },
    },
  };
}

function spreadColspan() {
  isColspanSpreading.value = !isColspanSpreading.value;
  vueGrid1.slickGrid?.setOptions({ spreadHiddenColspan: isColspanSpreading.value });
  vueGrid1.slickGrid?.resetActiveCell();
  vueGrid1.slickGrid?.invalidate();
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
  queueMicrotask(() => {
    vueGrid1.resizerService.resizeGrid();
    vueGrid2.resizerService.resizeGrid();
  });
}

function vueGrid1Ready(grid: SlickgridVueInstance) {
  vueGrid1 = grid;
}
function vueGrid2Ready(grid: SlickgridVueInstance) {
  vueGrid2 = grid;
}
</script>

<template>
  <h2>
    Example 14: Column Span & Header Grouping
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example14.vue"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    This example demonstrates how to easily span a row over multiple columns & how to group header titles.
    <ul>
      <li>
        Note that you can add Sort but remember that it will sort by the data which the row contains, even if the data is visually hidden by
        colspan it will still sort it
      </li>
    </ul>
  </div>

  <h3>
    Grid 1 <small>(with Header Grouping &amp; Colspan)</small>
    <button
      class="btn btn-outline-secondary btn-sm btn-icon ms-2"
      @click="spreadColspan()"
      data-test="spread-colspan-button"
      title="Should we always spread the same visible column count with or without hidden columns?"
    >
      <span>Toggle Spreading of ColSpan with/without Hidden Columns</span>
    </button>
  </h3>

  <slickgrid-vue
    v-model:options="gridOptions1!"
    v-model:columns="columns1"
    v-model:dataset="dataset1"
    grid-id="grid1"
    @onVueGridCreated="vueGrid1Ready($event.detail)"
  >
  </slickgrid-vue>

  <hr />

  <h3>Grid 2 <small>(with Header Grouping &amp; Pinned Columns)</small></h3>

  <div class="col-sm 12">
    <button class="btn btn-outline-secondary btn-sm btn-icon" data-test="remove-pinned-column-button" @click="setPinnedColumns2(-1)">
      <i class="mdi mdi-close"></i> Remove Pinned Columns
    </button>
    <button class="btn btn-outline-secondary btn-sm btn-icon ms-1" data-test="set-3pinned-columns" @click="setPinnedColumns2(2)">
      <i class="mdi mdi-pin-outline"></i> Set 3 Pinned Columns
    </button>
  </div>

  <slickgrid-vue
    v-model:options="gridOptions2!"
    v-model:columns="columns2"
    v-model:dataset="dataset2"
    grid-id="grid2"
    @onVueGridCreated="vueGrid2Ready($event.detail)"
  >
  </slickgrid-vue>
</template>
