// frameworks/angular-slickgrid/src/demos/examples/example26.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

import {
  AngularGridInstance,
  AngularUtilService,
  Column,
  Editors,
  FieldType,
  Filters,
  Formatters,
  GridOption,
  OnEventArgs,
  SlickGlobalEditorLock,
} from '../../library';
import { EditorNgSelectComponent } from './editor-ng-select.component';
import { CustomAngularComponentEditor } from './custom-angularComponentEditor';
import { CustomAngularComponentFilter } from './custom-angularComponentFilter';
import { CustomTitleFormatterComponent } from './custom-titleFormatter.component';
import { FilterNgSelectComponent } from './filter-ng-select.component';
import { CustomButtonFormatterComponent } from './custom-buttonFormatter.component';

const NB_ITEMS = 100;

@Component({
  templateUrl: './example26.component.html',
  styleUrls: ['./example26.component.scss'],
  encapsulation: ViewEncapsulation.None,
  providers: [AngularUtilService],
  standalone: false,
})
export class Example26Component implements OnInit {
  private _commandQueue: any[] = [];
  angularGrid!: AngularGridInstance;
  columnDefinitions: Column[] = [];
  gridOptions!: GridOption;
  dataset!: any[];
  gridObj: any;
  isAutoEdit = true;
  alertWarning: any;
  updatedObject: any;
  selectedLanguage = 'en';
  assignees = [
    { id: '', name: '' },
    { id: '1', name: 'John' },
    { id: '2', name: 'Pierre' },
    { id: '3', name: 'Paul' },
  ];

  constructor(
    private angularUtilService: AngularUtilService,
    private translate: TranslateService
  ) {}

  ngOnInit(): void {
    this.prepareGrid();
  }

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    this.gridObj = angularGrid.slickGrid;
  }

  prepareGrid() {
    this.columnDefinitions = [
      {
        id: 'title',
        name: 'Title',
        field: 'title',
        minWidth: 100,
        filterable: true,
        sortable: true,
        type: FieldType.string,
        editor: {
          model: Editors.longText,
          minLength: 5,
          maxLength: 255,
        },
        onCellChange: (e: Event, args: OnEventArgs) => {
          console.log(args);
          this.alertWarning = `Updated Title: ${args.dataContext.title}`;
        },
      },
      {
        id: 'title2',
        name: 'Title with Angular Component',
        field: 'title',
        minWidth: 100,
        sortable: true,
        type: FieldType.string,
        // loading formatter, text to display while Post Render gets processed
        formatter: () => '...',

        // if the component needs to stay and be interactive after rendering
        asyncPostRender: this.renderInteractiveAngularComponent.bind(this),
        params: {
          component: CustomButtonFormatterComponent,
          angularUtilService: this.angularUtilService,
        },
      },
      {
        id: 'assignee',
        name: 'Assignee',
        field: 'assignee',
        minWidth: 100,
        filterable: true,
        sortable: true,
        filter: {
          model: CustomAngularComponentFilter, // create a new instance to make each Filter independent from each other
          collection: this.assignees,
          params: {
            component: FilterNgSelectComponent,
          },
        },
        queryFieldFilter: 'assignee.id', // for a complex object it's important to tell the Filter which field to query and our CustomAngularComponentFilter returns the "id" property
        queryFieldSorter: 'assignee.name',
        formatter: Formatters.complexObject,
        params: {
          complexFieldLabel: 'assignee.name',
        },
        exportWithFormatter: true,
        editor: {
          model: CustomAngularComponentEditor,
          collection: this.assignees,
          params: {
            component: EditorNgSelectComponent,
          },
        },
        onCellChange: (e: Event, args: OnEventArgs) => {
          console.log(args);
          this.alertWarning = `Updated Title: ${args.dataContext.title}`;
        },
      },
      {
        id: 'assignee2',
        name: 'Assignee with Angular Component',
        field: 'assignee',
        minWidth: 125,
        filterable: true,
        sortable: true,
        filter: {
          model: CustomAngularComponentFilter, // create a new instance to make each Filter independent from each other
          collection: this.assignees,
          params: {
            component: FilterNgSelectComponent,
          },
        },
        queryFieldFilter: 'assignee.id', // for a complex object it's important to tell the Filter which field to query and our CustomAngularComponentFilter returns the "id" property
        queryFieldSorter: 'assignee.name',

        // loading formatter, text to display while Post Render gets processed
        formatter: () => '...',

        // to load an Angular Component, you cannot use a Formatter since Angular needs at least 1 cycle to render everything
        // you can use a PostRenderer but you will visually see the data appearing,
        // which is why it's still better to use regular Formatter instead of Angular Component
        asyncPostRender: this.renderAngularComponent.bind(this),
        params: {
          component: CustomTitleFormatterComponent,
          angularUtilService: this.angularUtilService,
          complexFieldLabel: 'assignee.name', // for the exportCustomFormatter
        },
        exportCustomFormatter: Formatters.complexObject,
      },
      {
        id: 'complete',
        name: '% Complete',
        field: 'percentComplete',
        minWidth: 100,
        filterable: true,
        formatter: Formatters.multiple,
        type: FieldType.number,
        editor: {
          model: Editors.singleSelect,

          // We can also add HTML text to be rendered (any bad script will be sanitized) but we have to opt-in, else it will be sanitized
          enableRenderHtml: true,
          collection: Array.from(Array(101).keys()).map((k) => ({
            value: k,
            label: k,
            symbol: '<i class="mdi mdi-percent-outline" style="color:cadetblue"></i>',
          })),
          customStructure: {
            value: 'value',
            label: 'label',
            labelSuffix: 'symbol',
          },
          editorOptions: {
            maxHeight: 400,
          },
        },
        filter: {
          model: Filters.slider,
          operator: '>=',
          filterOptions: { hideSliderNumber: false },
        },
        params: {
          formatters: [Formatters.collectionEditor, Formatters.percentCompleteBar],
        },
      },
      {
        id: 'start',
        name: 'Start',
        field: 'start',
        minWidth: 100,
        filterable: true,
        filter: { model: Filters.compoundDate },
        formatter: Formatters.dateIso,
        exportWithFormatter: true,
        sortable: true,
        type: FieldType.date,
        editor: {
          model: Editors.date,
        },
      },
      {
        id: 'finish',
        name: 'Finish',
        field: 'finish',
        minWidth: 100,
        filterable: true,
        sortable: true,
        filter: { model: Filters.compoundDate },
        formatter: Formatters.dateIso,
        exportWithFormatter: true,
        type: FieldType.date,
        editor: {
          model: Editors.date,
        },
      },
      {
        id: 'action',
        name: 'Action',
        field: 'id',
        maxWidth: 100,
        formatter: () => `<div class="cell-menu-dropdown">Action<i class="mdi mdi-chevron-down"></i></div>`,
        cellMenu: {
          commandTitle: 'Commands',
          commandItems: [
            {
              command: 'help',
              title: 'Help',
              iconCssClass: 'mdi mdi-help-circle text-info',
              positionOrder: 66,
              action: () => alert('Please Help!'),
            },
            {
              command: 'delete-row',
              title: 'Delete Row',
              positionOrder: 64,
              iconCssClass: 'mdi mdi-close color-danger',
              cssClass: 'red',
              textCssClass: 'text-italic color-danger-light',
              action: (_event, args) => this.angularGrid.gridService.deleteItemById(args.dataContext.id),
            },
          ],
        },
      },
    ];

    this.gridOptions = {
      asyncEditorLoading: false,
      autoEdit: this.isAutoEdit,
      autoCommitEdit: false,
      autoResize: {
        container: '#demo-container',
        rightPadding: 10,
      },
      headerRowHeight: 45,
      rowHeight: 45, // increase row height so that the ng-select fits in the cell
      editable: true,
      enableCellMenu: true,
      enableCellNavigation: true,
      enableColumnPicker: true,
      enableExcelCopyBuffer: true,
      enableFiltering: true,
      enableAsyncPostRender: true, // for the Angular PostRenderer, don't forget to enable it
      asyncPostRenderDelay: 0, // also make sure to remove any delay to render it
      editCommandHandler: (item, column, editCommand) => {
        this._commandQueue.push(editCommand);
        editCommand.execute();
      },
      i18n: this.translate,
      params: {
        angularUtilService: this.angularUtilService, // provide the service to all at once (Editor, Filter, AsyncPostRender)
      },
    };

    this.dataset = this.mockData(NB_ITEMS);
  }

  mockData(itemCount: number, startingIndex = 0) {
    // mock a dataset
    const tempDataset = [];
    for (let i = startingIndex; i < startingIndex + itemCount; i++) {
      const randomYear = 2000 + Math.floor(Math.random() * 10);
      const randomMonth = Math.floor(Math.random() * 11);
      const randomDay = Math.floor(Math.random() * 29);
      const randomPercent = Math.round(Math.random() * 100);

      tempDataset.push({
        id: i,
        title: 'Task ' + i,
        assignee: i % 3 ? this.assignees[3] : i % 2 ? this.assignees[2] : this.assignees[1],
        duration: Math.round(Math.random() * 100) + '',
        percentComplete: randomPercent,
        percentCompleteNumber: randomPercent,
        start: new Date(randomYear, randomMonth, randomDay),
        finish: new Date(randomYear, randomMonth + 1, randomDay),
        effortDriven: i % 5 === 0,
      });
    }
    return tempDataset;
  }

  onCellChanged(e: Event, args: any) {
    this.updatedObject = args.item;
  }

  onCellClicked(e: Event, args: any) {
    const metadata = this.angularGrid.gridService.getColumnFromEventArguments(args);
    console.log(metadata);

    if (metadata.columnDef.id === 'edit') {
      this.alertWarning = `open a modal window to edit: ${metadata.dataContext.title}`;

      // highlight the row, to customize the color, you can change the SASS variable $row-highlight-background-color
      this.angularGrid.gridService.highlightRow(args.row, 1500);

      // you could also select the row, when using "enableCellNavigation: true", it automatically selects the row
      // this.angularGrid.gridService.setSelectedRow(args.row);
    } else if (metadata.columnDef.id === 'delete') {
      if (confirm('Are you sure?')) {
        this.angularGrid.gridService.deleteItemById(metadata.dataContext.id);
      }
    }
  }

  onCellValidationError(e: Event, args: any) {
    alert(args.validationResults.msg);
  }

  changeAutoCommit() {
    this.gridOptions.autoCommitEdit = !this.gridOptions.autoCommitEdit;
    this.gridObj.setOptions({
      autoCommitEdit: this.gridOptions.autoCommitEdit,
    });
    return true;
  }

  setAutoEdit(isAutoEdit: boolean) {
    this.isAutoEdit = isAutoEdit;
    this.gridObj.setOptions({ autoEdit: isAutoEdit }); // change the grid option dynamically
    return true;
  }

  undo() {
    const command = this._commandQueue.pop();
    if (command && SlickGlobalEditorLock.cancelCurrentEdit()) {
      command.undo();
      this.gridObj.gotoCell(command.row, command.cell, false);
    }
  }

  renderAngularComponent(cellNode: HTMLElement, row: number, dataContext: any, colDef: Column) {
    if (colDef.params.component) {
      // the last 2 arguments of createAngularComponent() are optional
      // but when they are provided, that is the DOM target (cellNode) and the dataContext,
      // the util will render everything for you without too much delay
      const componentOutput = this.angularUtilService.createAngularComponent(colDef.params.component, cellNode, { item: dataContext });
      componentOutput.componentRef.destroy(); // cleanup no longer needed temp component
    }
  }

  renderInteractiveAngularComponent(cellNode: HTMLElement, row: number, dataContext: any, colDef: Column) {
    if (colDef.params.component) {
      this.angularUtilService.createInteractiveAngularComponent(colDef.params.component, cellNode, { item: dataContext });
    }
  }

  /* Create an Action Dropdown Menu */
  deleteCell(rowNumber: number) {
    const item = this.angularGrid.dataView.getItem(rowNumber);
    this.angularGrid.gridService.deleteItemById(item.id);
  }
}

<div id="demo-container" class="container-fluid">
  <h2>
    Example 26: Use of Angular Components
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/frameworks/angular-slickgrid/src/demos/examples/example26.component.ts"
        >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" (click)="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    <h3>Filters, Editors, AsyncPostRender with Angular Components</h3>
    Grid with usage of Angular Components as Editor &amp; AsyncPostRender (similar to Formatter).
    <ul>
      <li>Support of Angular Component as Custom Editor (click on any "Assignee" name cell)</li>
      <ul>
        <li>
          That column uses <a href="https://github.com/ng-select/ng-select" target="_blank">ng-select</a> as a custom editor as an Angular
          Component
        </li>
        <li>
          Increased Grid Options "rowHeight" &amp; "headerRowHeight" to 45 so that the "ng-select" fits in the cell. Ideally it would be
          better to override the ng-select css styling to change it's max height
        </li>
      </ul>
      <li>Support of Angular Component as Custom Filter ("Assignee" columns), which also uses "ng-select"</li>
      <li>The 2nd "Assignee" column (showing in bold text) uses "asyncPostRender" with an Angular Component</li>
      <ul>
        <li>Why can't we use Angular Component as Customer Formatter and why do I see a slight delay in loading the data?</li>
        <li>
          It's totally normal since SlickGrid Formatters only accept strings (synchronously), so we cannot use that (Angular requires at
          least 1 full cycle to render the element), so we are left with SlickGrid "asyncPostRender" and it works but as the name suggest
          it's async users might see noticeable delay in loading the data
        </li>
      </ul>
      <li>
        The 2nd "Title" showing an interactive component, which is not destroyed after first rendering but stays active. Click on the button
        to see the title alerted
      </li>
    </ul>
  </div>

  <div class="col-sm-6">
    <label>autoEdit setting: </label>
    <span id="radioAutoEdit">
      <label class="radio-inline control-label" for="radioTrue">
        <input type="radio" name="inlineRadioOptions" id="radioTrue" checked [value]="isAutoEdit" (change)="setAutoEdit(true)" /> ON
        (single-click)
      </label>
      <label class="radio-inline control-label" for="radioFalse">
        <input type="radio" name="inlineRadioOptions" id="radioFalse" [value]="isAutoEdit" (change)="setAutoEdit(false)" /> OFF
        (double-click)
      </label>
    </span>
    <div class="row col-sm-12">
      <span>
        <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="undo()">
          <i class="mdi mdi-undo"></i>
          Undo last edit(s)
        </button>
        <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="angularGrid.filterService.clearFilters()">Clear Filters</button>
        <button class="btn btn-outline-secondary btn-sm btn-icon" (click)="angularGrid.sortService.clearSorting()">Clear Sorting</button>
        <label class="checkbox-inline control-label" for="autoCommitEdit">
          <input
            type="checkbox"
            id="autoCommitEdit"
            data-test="auto-commit"
            [checked]="gridOptions.autoCommitEdit"
            (click)="changeAutoCommit()"
            />
          Auto Commit Edit
        </label>
      </span>
    </div>
  </div>

  <div class="col-sm-6">
    @if (updatedObject) {
      <div class="alert alert-info"><strong>Updated Item:</strong> {{ updatedObject | json }}</div>
    }
    @if (alertWarning) {
      <div class="alert alert-warning"><strong>Updated Item:</strong> {{ alertWarning }}</div>
    }
  </div>

  <div class="col-sm-12">
    <angular-slickgrid
      gridId="grid26"
      [columns]="columnDefinitions"
      [options]="gridOptions"
      [dataset]="dataset"
      (onAngularGridCreated)="angularGridReady($event.detail)"
      (onCellChange)="onCellChanged($event.detail.eventData, $event.detail.args)"
      (onClick)="onCellClicked($event.detail.eventData, $event.detail.args)"
      (onValidationError)="onCellValidationError($event.detail.eventData, $event.detail.args)"
      >
    </angular-slickgrid>
  </div>
</div>

// demos/vue/src/components/Example26.vue
<script setup lang="ts">
import {
  type GridOption,
  type SlickgridVueInstance,
  type Column,
  type EditCommand,
  Editors,
  FieldType,
  Filters,
  Formatters,
  type OnEventArgs,
  OperatorType,
  SlickGlobalEditorLock,
  SlickgridVue,
  type ViewModelBindableInputData,
} from 'slickgrid-vue';
import { ComponentPublicInstance, createApp, onBeforeMount, ref } from 'vue';

import { CustomVueComponentEditor } from './custom-viewModelEditor';
import { CustomVueComponentFilter } from './custom-viewModelFilter';
import CustomTitleFormatter from './CustomTitleFormatterComponent.vue';
import EditorSelect from './SelectEditorComponent.vue';
import FilterSelect from './SelectFilterComponent.vue';

type AppData = Record<string, unknown>;

const NB_ITEMS = 500;
const gridOptions = ref<GridOption>();
const columnDefinitions = ref<Column[]>([]);
const dataset = ref<any[]>([]);
const showSubTitle = ref(true);
let vueGrid!: SlickgridVueInstance;
const _commandQueue: EditCommand[] = [];
const updatedObject = ref<any>();
const isAutoEdit = ref(true);
const alertWarning = ref<any>();
const assignees = ref([
  { id: '', name: '' },
  { id: '1', name: 'John' },
  { id: '2', name: 'Pierre' },
  { id: '3', name: 'Paul' },
]);

onBeforeMount(() => {
  defineGrid();
  // mock some data (different in each dataset)
  dataset.value = mockData(NB_ITEMS);
});

/* Define grid Options and Columns */
function defineGrid() {
  columnDefinitions.value = [
    {
      id: 'title',
      name: 'Title',
      field: 'title',
      filterable: true,
      sortable: true,
      type: FieldType.string,
      editor: {
        model: Editors.longText,
        minLength: 5,
        maxLength: 255,
      },
      minWidth: 100,
      onCellChange: (_e: Event, args: OnEventArgs) => {
        console.log(args);
        alertWarning.value = `Updated Title: ${args.dataContext.title}`;
      },
    },
    {
      id: 'assignee',
      name: 'Assignee',
      field: 'assignee',
      minWidth: 100,
      filterable: true,
      sortable: true,
      filter: {
        model: CustomVueComponentFilter,
        collection: assignees.value,
        params: {
          component: FilterSelect,
        },
      },
      queryFieldFilter: 'assignee.id', // for a complex object it's important to tell the Filter which field to query and our CustomAureliaComponentFilter returns the "id" property
      queryFieldSorter: 'assignee.name',
      formatter: Formatters.complexObject,
      params: {
        complexFieldLabel: 'assignee.name',
      },
      exportWithFormatter: true,
      editor: {
        model: CustomVueComponentEditor,
        collection: assignees.value,
        params: {
          component: EditorSelect,
        },
      },
      onCellChange: (_e: Event, args: OnEventArgs) => {
        console.log(args);
        alertWarning.value = `Updated Title: ${args.dataContext.title}`;
      },
    },
    {
      id: 'assignee2',
      name: 'Assignee with Vue Component',
      field: 'assignee',
      minWidth: 125,
      filterable: true,
      sortable: true,
      filter: {
        model: CustomVueComponentFilter,
        collection: assignees.value,
        params: {
          component: FilterSelect,
        },
      },
      queryFieldFilter: 'assignee.id', // for a complex object it's important to tell the Filter which field to query and our CustomVueComponentFilter returns the "id" property
      queryFieldSorter: 'assignee.name',

      // loading formatter, text to display while Post Render gets processed
      formatter: () => '...',

      // to load a Vue Component, you cannot use a Formatter since Vue needs at least 1 cycle to render everything
      // you can use a PostRenderer but you will visually see the data appearing,
      // which is why it's still better to use regular Formatter instead of Vue Component
      asyncPostRender: renderVueComponent,
      params: {
        component: CustomTitleFormatter,
        // templateUrl: PLATFORM.moduleName('examples/slickgrid/custom-title-formatter'), // CustomTitleFormatterCustomElement,
        complexFieldLabel: 'assignee.name', // for the exportCustomFormatter
      },
      exportCustomFormatter: Formatters.complexObject,
    },
    {
      id: 'duration',
      name: 'Duration (days)',
      field: 'duration',
      filterable: true,
      minWidth: 100,
      sortable: true,
      type: FieldType.number,
      filter: { model: Filters.slider, filterOptions: { hideSliderNumber: false } },
      editor: {
        model: Editors.slider,
        minValue: 0,
        maxValue: 100,
        // editorOptions: { hideSliderNumber: true },
      },
      /*
        editor: {
          // default is 0 decimals, if no decimals is passed it will accept 0 or more decimals
          // however if you pass the "decimalPlaces", it will validate with that maximum
          model: Editors.float,
          minValue: 0,
          maxValue: 365,
          // the default validation error message is in English but you can override it by using "errorMessage"
          // errorMessage: i18n.tr('INVALID_FLOAT', { maxDecimal: 2 }),
          params: { decimalPlaces: 2 },
        },
        */
    },
    {
      id: 'complete',
      name: '% Complete',
      field: 'percentComplete',
      filterable: true,
      formatter: Formatters.multiple,
      type: FieldType.number,
      editor: {
        // We can also add HTML text to be rendered (any bad script will be sanitized) but we have to opt-in, else it will be sanitized
        enableRenderHtml: true,
        collection: Array.from(Array(101).keys()).map((k) => ({
          value: k,
          label: k,
          symbol: '<i class="mdi mdi-percent-outline" style="color:cadetblue"></i>',
        })),
        customStructure: {
          value: 'value',
          label: 'label',
          labelSuffix: 'symbol',
        },
        collectionSortBy: {
          property: 'label',
          sortDesc: true,
        },
        collectionFilterBy: {
          property: 'value',
          value: 0,
          operator: OperatorType.notEqual,
        },
        model: Editors.singleSelect,
      },
      minWidth: 100,
      params: {
        formatters: [Formatters.collectionEditor, Formatters.percentCompleteBar],
      },
    },
    {
      id: 'start',
      name: 'Start',
      field: 'start',
      filterable: true,
      filter: { model: Filters.compoundDate },
      formatter: Formatters.dateIso,
      sortable: true,
      minWidth: 100,
      type: FieldType.date,
      editor: {
        model: Editors.date,
      },
    },
    {
      id: 'finish',
      name: 'Finish',
      field: 'finish',
      filterable: true,
      filter: { model: Filters.compoundDate },
      formatter: Formatters.dateIso,
      sortable: true,
      minWidth: 100,
      type: FieldType.date,
      editor: {
        model: Editors.date,
      },
    },
  ];

  gridOptions.value = {
    asyncEditorLoading: false,
    autoEdit: isAutoEdit.value,
    autoCommitEdit: false,
    autoResize: {
      container: '#demo-container',
      rightPadding: 10,
    },
    rowHeight: 45, // increase row height so that the custom elements fits in the cell
    editable: true,
    enableCellNavigation: true,
    enableColumnPicker: true,
    enableExcelCopyBuffer: true,
    enableFiltering: true,
    enableAsyncPostRender: true, // for the Vue PostRenderer, don't forget to enable it
    asyncPostRenderDelay: 0, // also make sure to remove any delay to render it
    editCommandHandler: (_item, _column, editCommand) => {
      _commandQueue.push(editCommand);
      editCommand.execute();
    },
    // params: {
    //   aureliaUtilService: aureliaUtilService // provide the service to all at once (Editor, Filter, AsyncPostRender)
    // }
  };
}

function mockData(count: number) {
  // mock a dataset
  const tempDataset: any[] = [];
  for (let i = 0; i < count; i++) {
    const randomYear = 2000 + Math.floor(Math.random() * 10);
    const randomMonth = Math.floor(Math.random() * 11);
    const randomDay = Math.floor(Math.random() * 29);
    const randomPercent = Math.round(Math.random() * 100);

    tempDataset.push({
      id: i,
      title: 'Task ' + i,
      assignee: i % 3 ? assignees.value[2] : i % 2 ? assignees.value[1] : assignees.value[0],
      duration: Math.round(Math.random() * 100) + '',
      percentComplete: randomPercent,
      percentCompleteNumber: randomPercent,
      start: new Date(randomYear, randomMonth, randomDay),
      finish: new Date(randomYear, randomMonth + 1, randomDay),
      effortDriven: i % 5 === 0,
    });
  }
  return tempDataset;
}

function onCellChanged(_e: Event, args: any) {
  console.log('onCellChange', args);
  updatedObject.value = { ...args.item };
}

function onCellClicked(_e: Event, args: any) {
  const metadata = vueGrid.gridService.getColumnFromEventArguments(args);
  console.log(metadata);

  if (metadata.columnDef.id === 'edit') {
    alertWarning.value = `open a modal window to edit: ${metadata.dataContext.title}`;

    // highlight the row, to customize the color, you can change the SASS variable $row-highlight-background-color
    vueGrid.gridService.highlightRow(args.row, 1500);

    // you could also select the row, when using "enableCellNavigation: true", it automatically selects the row
    // vueGrid.gridService.setSelectedRow(args.row);
  } else if (metadata.columnDef.id === 'delete') {
    if (confirm('Are you sure?')) {
      vueGrid.gridService.deleteItemById(metadata.dataContext.id);
      alertWarning.value = `Deleted: ${metadata.dataContext.title}`;
    }
  }
}

function onCellValidation(_e: Event, args: any) {
  alert(args.validationResults.msg);
}

function changeAutoCommit() {
  gridOptions.value!.autoCommitEdit = !gridOptions.value!.autoCommitEdit;
  vueGrid.slickGrid.setOptions({
    autoCommitEdit: gridOptions.value!.autoCommitEdit,
  });
  return true;
}

function renderVueComponent(cellNode: HTMLElement, _row: number, dataContext: any, colDef: Column) {
  const component = colDef.params?.component;
  if (component && cellNode) {
    const bindableData = {
      model: dataContext,
      grid: vueGrid.slickGrid,
    } as AppData & ViewModelBindableInputData;

    const tmpDiv = document.createElement('div');
    const app = createApp(component, bindableData);
    const instance = app.mount(tmpDiv) as ComponentPublicInstance;
    cellNode.replaceChildren(instance.$el);
  }
}

function setAutoEdit(isAutoEdit: boolean) {
  isAutoEdit = isAutoEdit;
  vueGrid.slickGrid.setOptions({
    autoEdit: isAutoEdit,
  });
  return true;
}

function undo() {
  const command = _commandQueue.pop();
  if (command && SlickGlobalEditorLock.cancelCurrentEdit()) {
    command.undo();
    vueGrid.slickGrid.gotoCell(command.row, command.cell, false);
  }
}

function toggleSubTitle() {
  showSubTitle.value = !showSubTitle.value;
  const action = showSubTitle.value ? 'remove' : 'add';
  document.querySelector('.subtitle')?.classList[action]('hidden');
  queueMicrotask(() => vueGrid.resizerService.resizeGrid());
}

function vueGridReady(grid: SlickgridVueInstance) {
  vueGrid = grid;
}
</script>

<template>
  <h2>
    Example 26: Use of Vue Components
    <span class="float-end">
      <a
        style="font-size: 18px"
        target="_blank"
        href="https://github.com/ghiscoding/slickgrid-universal/blob/master/demos/vue/src/components/Example26.vue"
      >
        <span class="mdi mdi-link-variant"></span> code
      </a>
    </span>
    <button class="ms-2 btn btn-outline-secondary btn-sm btn-icon" type="button" data-test="toggle-subtitle" @click="toggleSubTitle()">
      <span class="mdi mdi-information-outline" title="Toggle example sub-title details"></span>
    </button>
  </h2>

  <div class="subtitle">
    <h3>Filters, Editors, AsyncPostRender with Vue Components</h3>
    Grid with usage of Vue Components as Editor &amp; AsyncPostRender (similar to Formatter).
    <ul>
      <li>Support of Vue Component as Custom Editor (click on any "Assignee" name cell)</li>
      <ul>
        <li>That column uses a simple select drodown wrapped in an Vue Component</li>
        <li>Increased Grid Options "rowHeight" &amp; "headerRowHeight" to 45 so that the Custom Element fits in the cell.</li>
      </ul>
      <li>Support of Vue Component as Custom Filter ("Assignee" columns), which also uses Custom Element</li>
      <li>The 2nd "Assignee" column (showing in bold text) uses "asyncPostRender" with an Vue Component</li>
      <ul>
        <li>Why can't we use Vue Component as Customer Formatter and why do I see a slight delay in loading the data?</li>
        <li>
          It's totally normal since SlickGrid Formatters only accept strings (synchronously), so we cannot use that (Vue requires at least 1
          full cycle to render the element), so we are left with SlickGrid "asyncPostRender" and it works but as the name suggest it's async
          users might see noticeable delay in loading the data
        </li>
      </ul>
    </ul>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <label>autoEdit setting</label>
      <br />
      <span id="radioAutoEdit">
        <div class="row">
          <div class="col">
            <label class="radio-inline control-label me-1" for="radioTrue">
              <input type="radio" name="inlineRadioOptions" id="radioTrue" checked v-model="isAutoEdit" @click="setAutoEdit(true)" />
              ON (single-click)
            </label>
            <label class="radio-inline control-label" for="radioFalse">
              <input type="radio" name="inlineRadioOptions" id="radioFalse" v-model="isAutoEdit" @click="setAutoEdit(false)" />
              OFF (double-click)
            </label>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <button class="btn btn-outline-secondary btn-sm btn-icon me-1" @click="undo()">
              <i class="mdi mdi-undo"></i>
              Undo last edit(s)
            </button>
            <label class="checkbox-inline control-label" for="autoCommitEdit">
              <input
                type="checkbox"
                id="autoCommitEdit"
                data-test="auto-edit-checkbox"
                v-model="gridOptions!.autoCommitEdit"
                @click="changeAutoCommit()"
              />
              Auto Commit Edit
            </label>
          </div>
        </div>
      </span>
      <div class="row" style="margin-top: 5px">
        <div class="col">
          <button class="btn btn-outline-secondary btn-sm btn-icon" data-test="clear-filters" @click="vueGrid.filterService.clearFilters()">
            Clear Filters
          </button>
          <button
            class="btn btn-outline-secondary btn-sm btn-icon mx-1"
            data-test="clear-sorting"
            @click="vueGrid.sortService.clearSorting()"
          >
            Clear Sorting
          </button>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="alert alert-info" v-show="updatedObject"><strong>Updated Item:</strong> {{ JSON.stringify(updatedObject, null, 2) }}</div>
      <div class="alert alert-warning" v-show="alertWarning">
        {{ alertWarning }}
      </div>
    </div>
  </div>

  <slickgrid-vue
    grid-id="grid26"
    v-model:options="gridOptions"
    v-model:columns="columnDefinitions as Column[]"
    v-model:data="dataset"
    @onCellChange.trigger="onCellChanged($event.detail.eventData, $event.detail.args)"
    @on@click="onCellClicked($event.detail.eventData, $event.detail.args)"
    @onVueGridCreated="vueGridReady($event.detail)"
  >
  </slickgrid-vue>
</template>
