// demos/react/src/examples/slickgrid/Example19-preload.tsx
import { forwardRef, useEffect } from 'react';

export const Example19Preload = forwardRef((props: any, ref: any) => {
  useEffect(() => {
    return () => {
      console.log('Preload unmounted');
    };
  }, []);

  return (
    <div ref={ref} className="container-fluid d-flex align-items-center" style={{ marginTop: '10px' }}>
      <i className="mdi mdi-sync mdi-spin mdi-50px"></i>
      <h4>Loading...</h4>
    </div>
  );
});

// demos/vue/src/components/Example19Preload.vue
<script setup lang="ts">
import { onUnmounted } from 'vue';

onUnmounted(() => {
  console.log('unmounting preload');
});
</script>
<template>
  <div class="container-fluid d-flex align-items-center" style="margin-top: 10px">
    <i class="mdi mdi-sync mdi-spin mdi-50px"></i>
    <h4>Loading...</h4>
  </div>
</template>
<style lang="scss"></style>
