// frameworks/angular-slickgrid/src/demos/examples/home.component.ts
import { Component } from '@angular/core';

@Component({ templateUrl: './home.component.html' })
export class HomeComponent {}

<div class="container">
  <h2>Angular-Slickgrid - Demo Site</h2>
  <div class="subtitle">This site is to demo multiple usage of Angular-Slickgrid, choose an example from the left side menu</div>

  <hr />

  <h4>Quick intro</h4>
  <p>
    One of the best JavaScript datagrid
    <a href="https://github.com/mleibman/SlickGrid" target="_blank">SlickGrid</a> which was originally developed by &#64;mleibman is now
    available to Angular. I have tried, and used, a few datagrids and SlickGrid beats most of them in terms of functionalities and
    performance (it can easily handle a million row).
  </p>
  <h4>Documentation</h4>
  <p>
    The documentation is powered by GitBook and can be found at this link
    <a href="https://ghiscoding.gitbook.io/angular-slickgrid" target="_blank">Angular-Slickgrid - Documentation</a>, so be sure to consult
    it before opening any new issue.
    <br />
    The
    <a href="https://ghiscoding.gitbook.io/angular-slickgrid/getting-started/quick-start" target="_blank">HOWTO - Quick Start</a>
    is the best starting point to get going with this library.
  </p>

  <hr />
  Like my work? You can support me with caffeine :)

  <br /><br />

  <a href="https://ko-fi.com/ghiscoding" target="_blank">
    <img
      height="36"
      width="140"
      style="border: 0px; height: 36px"
      src="https://storage.ko-fi.com/cdn/kofi3.png?v=6"
      border="0"
      alt="Buy Me a Coffee at ko-fi.com"
    />
  </a>
</div>

// demos/vue/src/Home.vue
<script setup lang="ts"></script>
<template>
  <h2>Slickgrid-Vue - Demo Site</h2>
  <div class="subtitle">This site is to demo multiple usage of Slickgrid-Vue, choose an example from the left side menu</div>

  <hr />

  <h4>Quick intro</h4>
  <p>
    One of the best javascript datagrid
    <a href="https://github.com/mleibman/SlickGrid" target="_blank">SlickGrid</a> which was originally developed by &#64;mleibman is now
    available to Angular. I have tried, and used, a few datagrids and SlickGrid beats most of them in terms of functionalities and
    performance (it can easily even handle a million row).
  </p>
  <h4>Documentation</h4>
  <p>
    The documentation is powered by GitBook and can be found at this link
    <a href="https://ghiscoding.gitbook.io/slickgrid-vue" target="_blank">Slickgrid-Vue - Documentation</a>, so be sure to consult it before
    opening any new issue.
    <br />
    The
    <a href="https://ghiscoding.gitbook.io/slickgrid-vue/getting-started/quick-start" target="_blank">HOWTO - Quick Start</a>
    is the best starting point to get going with this library.
  </p>

  <hr />
  Like my work? You can support me with caffeine :)

  <br /><br />

  <a href="https://ko-fi.com/ghiscoding" target="_blank">
    <img
      height="36"
      style="border: 0px; height: 36px"
      src="https://az743702.vo.msecnd.net/cdn/kofi2.png?v=0"
      border="0"
      alt="Buy Me a Coffee at ko-fi.com"
    />
  </a>
</template>
