// demos/vue/src/components/ExampleDetailPreload.vue
<script setup lang="ts">
import { onUnmounted } from 'vue';

onUnmounted(() => {
  console.log('unmounting preload');
});
</script>
<template>
  <div class="container-fluid d-flex align-items-center" style="margin-top: 10px">
    <i class="mdi mdi-sync mdi-spin font-50px"></i>
    <h4>Loading...</h4>
  </div>
</template>
<style lang="scss"></style>

// demos/react-fluent/src/examples/slickgrid/Example-detail-preload.tsx
import { useEffect } from 'react';

export const ExampleDetailPreload = (props: any) => {
  const { ref } = props;
  useEffect(() => {
    return () => {
      console.log('Preload unmounted');
    };
  }, []);

  return (
    <div ref={ref} className="container-fluid d-flex align-items-center" style={{ marginTop: '10px' }}>
      <h4>Loading...</h4>
    </div>
  );
};
