// demos/vue/src/App.vue
<script setup lang="ts">
import { useTranslation } from 'i18next-vue';
import { onMounted, provide } from 'vue';
import VueLogo from './assets/vue.svg?url';
import { routes } from './router/index.js';

provide('i18next', useTranslation().i18next);

onMounted(() => {
  setTimeout(() => {
    const linkElm = document.querySelector('.nav-link.active');
    linkElm?.scrollIntoView({ block: 'nearest' });
  }, 0);
});
</script>

<template>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand ms-2" href="https://github.com/ghiscoding/slickgrid-universal/tree/master/frameworks/slickgrid-vue">
      <i class="mdi mdi-github"></i>
      <span class="ms-2">Slickgrid-Vue</span>
    </a>
    <img :src="VueLogo" class="logo" height="28" />
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-target="#navbarContent"
      aria-controls="navbarContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="github-button-container">
      <a href="https://github.com/ghiscoding/slickgrid-universal">
        <img src="https://img.shields.io/github/stars/ghiscoding/slickgrid-universal?style=social" />
      </a>
    </div>

    <div id="navbarContent" class="navbar-collapse collapse justify-content-end me-2">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://ghiscoding.gitbook.io/slickgrid-vue/" target="_blank"> Documentation </a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="panel-wm">
    <section id="panel-left" class="panel-wm-left">
      <ul class="well nav nav-pills nav-stacked">
        <li class="nav-item fw-bold nav-docs">
          <a class="nav-link" href="https://ghiscoding.gitbook.io/slickgrid-vue/" target="_blank"> 📘 Documentation </a>
        </li>
        <li v-for="(route, index) in routes" :key="index" class="nav-item">
          <RouterLink v-if="route.name !== 'root' && route.name !== 'home'" class="nav-link" active-class="active" :to="route.path">{{
            route.name
          }}</RouterLink>
        </li>
      </ul>
    </section>
    <section class="panel-wm-content">
      <div id="demo-container">
        <RouterView />
      </div>
    </section>
  </div>
</template>

// frameworks/angular-slickgrid/src/demos/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  imports: [RouterLink, RouterLinkActive, RouterOutlet],
})
export class AppComponent implements OnInit {
  title = 'Angular-Slickgrid';

  ngOnInit() {
    // scroll to active link route, there's probably a better way to do this but couldn't find lifecycle for it
    setTimeout(() => {
      const linkElm = document.querySelector('.nav-link.active');
      linkElm?.scrollIntoView({ block: 'nearest' });
    }, 45);
  }
}

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a
    class="navbar-brand ms-2"
    href="https://github.com/ghiscoding/slickgrid-universal/tree/master/frameworks/angular-slickgrid"
    target="_blank"
  >
    <i class="mdi mdi-github me-1"></i>
    <span>Angular-SlickGrid</span>
  </a>
  <img src="assets/angular-logo2.png" class="logo" height="32" alt="image" />
  <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-target="#navbarContent"
    aria-controls="navbarContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="github-button-container">
    <a href="https://github.com/ghiscoding/slickgrid-universal" target="_blank">
      <img src="https://img.shields.io/github/stars/ghiscoding/slickgrid-universal?style=social" alt="github stars" />
    </a>
  </div>

  <div class="navbar-collapse collapse justify-content-end me-2" id="navbarContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" [routerLink]="['/home']"> Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://ghiscoding.gitbook.io/angular-slickgrid/" target="_blank"> Documentation </a>
      </li>
    </ul>
  </div>
</nav>

<div>
  <div class="panel-wm">
    <section id="panel-left" class="panel-wm-left">
      <ul class="well nav nav-pills nav-stacked">
        <li class="nav-item fw-bold nav-docs">
          <a class="nav-link" href="https://ghiscoding.gitbook.io/angular-slickgrid/" target="_blank"> 📘 Documentation </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example01']">1- Basic Grid / 2 Grids</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example02']">2- Formatters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example03']">3- Editors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example04']">4- Client Side Sort/Filter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example05']">5- Backend Server with OData</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example06']">6- Backend Server with GraphQL</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example07']">7- Header Button Plugin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example08']">8- Header Menu Plugin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example09']">9- Grid Menu (hamburger menu)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example10']">10- Row Selection / 2 Grids</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example11']">11- Add/Update/Highlight Datagrid Item</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example12']">12- Localization (i18n)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example13']">13- Grouping &amp; Aggregator</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example14']">14- Column Span</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example15']">15- Grid State &amp; Local Storage</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example16']">16- Row Move</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example17']">17- Create Grid from CSV </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example18']">18- Draggable Grouping</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example19']">19- Row Detail View</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example20']">20- Frozen Columns/Rows</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example21']">21- Grid AutoHeight (full height)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example22']">22- within Bootstrap Tabs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example23']">23- Filter by Range of Values</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example24']">24- Cell & Context Menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example25']"> 25- GraphQL without Pagination </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example26']">26- Use of Angular Components</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example27']"> 27- Tree Data (Parent/Child) </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example28']"> 28- Tree Data (Hierarchical) </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example29']"> 29- Custom header &amp; footer templates </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example30']"> 30- Composite Editor Modal </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example31']">31- Backend Server Custom Paging</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example32']"> 32- Resize by Cell Content </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example33']"> 33- Regular & Custom Tooltip </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example34']"> 34- Real-Time Trading Platform </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example35']"> 35- Row Based Editing </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example36']"> 36- Excel Export Formulas </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example37']"> 37- Footer Totals Row </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example38']"> 38- Infinite Scroll with OData </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example39']"> 39- Infinite Scroll with GraphQL </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example40']"> 40- Infinite Scroll from JSON data </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example41']"> 41- Drag & Drop </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example42']">42- Custom Pagination </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example43']">43- Colspan/Rowspan (timesheets)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example44']">44- Colspan/Rowspan (large data)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example45']">45- Row Detail with inner Grid</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example46']">46- Tree Data with Lazy Loading</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example47']">47- Row Detail with Grouping</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example48']">48- Hybrid Selection Model</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example49']">49- Spreadsheet Drag-Fill</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example50']">50- Master/Detail Grids</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example51']">51- Menus with Slots</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example52']">52- SQL Backend Service</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example53']">53- Custom Filter Bar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example54']">54- AI / Web MCP Toolkit</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example55']">55- Variable Row Height (provider)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example56']">56- Variable Row Height (metadata)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" [routerLink]="['/example57']">57- RTL (Right-to-Left)</a>
        </li>
      </ul>
    </section>

    <section class="panel-wm-content">
      <div id="demo-container">
        <router-outlet></router-outlet>
      </div>
    </section>
  </div>
</div>
